#!/usr/bin/env python3
"""Blind panel writer for exp 268 (reasoning line): nhoppanel268.

Backwards questions about a value that has its own facts.
Writes artifacts/claude-nhoppanel268-20260923/panel.jsonl (70 items).

Every sentence below was composed fresh for this panel. Fictional names only.
Teach forms used: "A's R is B." only (verified: the base stores this shape
for every relation used here; "The R of A is B." does not store, so it is
never used).

Item schema:
  {"id": "n268-001", "family", "setup": [...], "question", "gold": [...], "note"}
- id: n268-001 .. n268-070
- family: one of reverse_chain, reverse_nochain, uncued_reverse,
  forward_chain, forward_1hop, abstain
- setup: 1-4 teach strings, each its own turn
- question: one question string
- gold: JSON list of strings; every string must appear in a right reply;
  [] means the right reply is an abstain
- note: writer note (design intent, never shown to the agent)

Families and counts:
  reverse_chain  24, reverse_nochain 10, uncued_reverse 8,
  forward_chain 12, forward_1hop 10, abstain 6  (= 70)

Usage:
  uv run --offline --no-project --python 3.12 --with torch --with numpy \
    python -B artifacts/claude-nhoppanel268-20260923/make_panel.py
writes panel.jsonl next to itself.
"""

from __future__ import annotations

import json
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent

ITEMS: list[dict] = [
    # ---------------- reverse_chain (24) ----------------
    {"id": "n268-001", "family": "reverse_chain",
     "setup": ["Alba's spouse is Bren.", "Bren's employer is Halwick Labs."],
     "question": "Whose spouse is Bren?", "gold": ["Alba"],
     "note": "spouse chain; plain Whose-shape"},
    {"id": "n268-002", "family": "reverse_chain",
     "setup": ["Cade's spouse is Dov.", "Dov's mother is Elin."],
     "question": "Who is married to Dov?", "gold": ["Cade"],
     "note": "spouse chain; married-shape"},
    {"id": "n268-003", "family": "reverse_chain",
     "setup": ["Finn's spouse is Gala.", "Hux's spouse is Gala.",
               "Gala's boss is Ivor."],
     "question": "Whose spouse is Gala?", "gold": ["Finn", "Hux"],
     "note": "spouse chain; two subjects share the value"},
    {"id": "n268-004", "family": "reverse_chain",
     "setup": ["Joss's wife is Kira.", "Kira's friend is Lem."],
     "question": "Who is married to Kira?", "gold": ["Joss"],
     "note": "wife chain; married-shape"},
    {"id": "n268-005", "family": "reverse_chain",
     "setup": ["Quill Harbor's author is Marla.", "Marla's spouse is Doren."],
     "question": "What has Marla written?", "gold": ["Quill Harbor"],
     "note": "author chain; what-has-written shape"},
    {"id": "n268-006", "family": "reverse_chain",
     "setup": ["Velvet Cartography's author is Nia.",
               "Nia's employer is Bromley Press."],
     "question": "What did Nia write?", "gold": ["Velvet Cartography"],
     "note": "author chain; what-did-write shape"},
    {"id": "n268-007", "family": "reverse_chain",
     "setup": ["Salt Meridian's author is Oren.",
               "Cinder Atlas's author is Oren.", "Oren's friend is Pam."],
     "question": "What has Oren written?",
     "gold": ["Salt Meridian", "Cinder Atlas"],
     "note": "author chain; two books share the author"},
    {"id": "n268-008", "family": "reverse_chain",
     "setup": ["Hollow Orchard's author is Quinn Vale.",
               "Quinn Vale's mother is Rosa."],
     "question": "What did Quinn Vale write?", "gold": ["Hollow Orchard"],
     "note": "author chain; two-word author name"},
    {"id": "n268-009", "family": "reverse_chain",
     "setup": ["Bromley Press's founder is Sade.", "Sade's spouse is Tilda."],
     "question": "What did Sade found?", "gold": ["Bromley Press"],
     "note": "founder chain; what-did-found shape"},
    {"id": "n268-010", "family": "reverse_chain",
     "setup": ["Halwick Labs's founder is Ulf.", "Ulf's boss is Vonn."],
     "question": "What did Ulf found?", "gold": ["Halwick Labs"],
     "note": "founder chain; lab founder"},
    {"id": "n268-011", "family": "reverse_chain",
     "setup": ["Copper Finch's founder is Wren.",
               "Tin Sparrow's founder is Wren.", "Wren's neighbour is Xana."],
     "question": "What did Wren found?",
     "gold": ["Copper Finch", "Tin Sparrow"],
     "note": "founder chain; two companies share the founder"},
    {"id": "n268-012", "family": "reverse_chain",
     "setup": ["Lumen Bakery's founder is Yuri Hale.",
               "Yuri Hale's friend is Zara."],
     "question": "What did Yuri Hale found?", "gold": ["Lumen Bakery"],
     "note": "founder chain; two-word founder name"},
    {"id": "n268-013", "family": "reverse_chain",
     "setup": ["Doren's employer is Halwick Labs.",
               "Halwick Labs's founder is Petra."],
     "question": "Whose employer is Halwick Labs?", "gold": ["Doren"],
     "note": "employer chain; Whose-employer shape"},
    {"id": "n268-014", "family": "reverse_chain",
     "setup": ["Elin's employer is Bromley Press.",
               "Bromley Press's founder is Sade Marsh."],
     "question": "Who works for Bromley Press?", "gold": ["Elin"],
     "note": "employer chain; who-works-for shape"},
    {"id": "n268-015", "family": "reverse_chain",
     "setup": ["Farah's employer is Copper Finch.",
               "Gus's employer is Copper Finch.",
               "Copper Finch's founder is Wren Cole."],
     "question": "Whose employer is Copper Finch?",
     "gold": ["Farah", "Gus"],
     "note": "employer chain; two workers share the employer"},
    {"id": "n268-016", "family": "reverse_chain",
     "setup": ["Hana's employer is Lumen Bakery.",
               "Lumen Bakery's founder is Yuri."],
     "question": "Who works for Lumen Bakery?", "gold": ["Hana"],
     "note": "employer chain; bakery employer"},
    {"id": "n268-017", "family": "reverse_chain",
     "setup": ["Ivor's parent is Joss.", "Joss's spouse is Kira."],
     "question": "Whose parent is Joss?", "gold": ["Ivor"],
     "note": "parent chain; Whose-parent shape"},
    {"id": "n268-018", "family": "reverse_chain",
     "setup": ["Lem's parent is Mona.", "Nate's parent is Mona.",
               "Mona's friend is Orla."],
     "question": "Whose parent is Mona?", "gold": ["Lem", "Nate"],
     "note": "parent chain; two children share the parent"},
    {"id": "n268-019", "family": "reverse_chain",
     "setup": ["Pia's child is Quinn.", "Quinn's employer is Halwick Labs."],
     "question": "Whose child is Quinn?", "gold": ["Pia"],
     "note": "child chain; Whose-child shape"},
    {"id": "n268-020", "family": "reverse_chain",
     "setup": ["Moonlit Parade's composer is Rafi.",
               "Paper Lantern's composer is Rafi.", "Rafi's spouse is Suki."],
     "question": "What did Rafi compose?",
     "gold": ["Moonlit Parade", "Paper Lantern"],
     "note": "composer chain; two works share the composer"},
    {"id": "n268-021", "family": "reverse_chain",
     "setup": ["Brass Comet's composer is Tariq Vale.",
               "Tariq Vale's boss is Uma."],
     "question": "What did Tariq Vale compose?", "gold": ["Brass Comet"],
     "note": "composer chain; two-word composer name"},
    {"id": "n268-022", "family": "reverse_chain",
     "setup": ["Glass Anthem's composer is Vesa.", "Vesa's mother is Willa."],
     "question": "Whose composer is Vesa?", "gold": ["Glass Anthem"],
     "note": "composer chain; Whose-composer shape"},
    {"id": "n268-023", "family": "reverse_chain",
     "setup": ["Xana's child is Yusuf.", "Yusuf's friend is Zane."],
     "question": "Whose child is Yusuf?", "gold": ["Xana"],
     "note": "child chain; friend second link"},
    {"id": "n268-024", "family": "reverse_chain",
     "setup": ["Ada Bly's parent is Bram.", "Bram's employer is Copper Finch."],
     "question": "Whose parent is Bram?", "gold": ["Ada Bly"],
     "note": "parent chain; two-word child name"},
    # ---------------- reverse_nochain (10) ----------------
    {"id": "n268-025", "family": "reverse_nochain",
     "setup": ["Bram's spouse is Cleo."],
     "question": "Whose spouse is Cleo?", "gold": ["Bram"],
     "note": "no chain on the value; Whose-shape"},
    {"id": "n268-026", "family": "reverse_nochain",
     "setup": ["Dax's wife is Elif."],
     "question": "Who is married to Elif?", "gold": ["Dax"],
     "note": "no chain; married-shape"},
    {"id": "n268-027", "family": "reverse_nochain",
     "setup": ["Fog Ledger's author is Greta."],
     "question": "What has Greta written?", "gold": ["Fog Ledger"],
     "note": "no chain; author written-shape"},
    {"id": "n268-028", "family": "reverse_nochain",
     "setup": ["Stone Mill's founder is Haldor."],
     "question": "What did Haldor found?", "gold": ["Stone Mill"],
     "note": "no chain; founder-shape"},
    {"id": "n268-029", "family": "reverse_nochain",
     "setup": ["Ilsa's employer is Northwind Traders."],
     "question": "Whose employer is Northwind Traders?", "gold": ["Ilsa"],
     "note": "no chain; employer-shape"},
    {"id": "n268-030", "family": "reverse_nochain",
     "setup": ["Joren's parent is Kara."],
     "question": "Whose parent is Kara?", "gold": ["Joren"],
     "note": "no chain; parent-shape"},
    {"id": "n268-031", "family": "reverse_nochain",
     "setup": ["Lior's child is Mara Vale."],
     "question": "Whose child is Mara Vale?", "gold": ["Lior"],
     "note": "no chain; child-shape, two-word value"},
    {"id": "n268-032", "family": "reverse_nochain",
     "setup": ["Silent Harbor's composer is Ned."],
     "question": "What did Ned compose?", "gold": ["Silent Harbor"],
     "note": "no chain; composer-shape"},
    {"id": "n268-033", "family": "reverse_nochain",
     "setup": ["Opal's husband is Perrin."],
     "question": "Who is married to Perrin?", "gold": ["Opal"],
     "note": "no chain; husband married-shape"},
    {"id": "n268-034", "family": "reverse_nochain",
     "setup": ["Rhea's spouse is Sam."],
     "question": "Who is married to Sam?", "gold": ["Rhea"],
     "note": "no chain; spouse married-shape"},
    # ---------------- uncued_reverse (8) ----------------
    {"id": "n268-035", "family": "uncued_reverse",
     "setup": ["Tess's boss is Udo.", "Udo's friend is Vera."],
     "question": "Whose boss is Udo?", "gold": ["Tess"],
     "note": "boss with a value chain"},
    {"id": "n268-036", "family": "uncued_reverse",
     "setup": ["Wade's boss is Xenia."],
     "question": "Whose boss is Xenia?", "gold": ["Wade"],
     "note": "boss without a value chain"},
    {"id": "n268-037", "family": "uncued_reverse",
     "setup": ["Yara's mother is Zola.", "Zola's employer is Halwick Labs."],
     "question": "Whose mother is Zola?", "gold": ["Yara"],
     "note": "mother with a value chain"},
    {"id": "n268-038", "family": "uncued_reverse",
     "setup": ["Abel's mother is Cora."],
     "question": "Whose mother is Cora?", "gold": ["Abel"],
     "note": "mother without a value chain"},
    {"id": "n268-039", "family": "uncued_reverse",
     "setup": ["Dalia's friend is Emmett.", "Emmett's spouse is Farah."],
     "question": "Whose friend is Emmett?", "gold": ["Dalia"],
     "note": "friend with a value chain"},
    {"id": "n268-040", "family": "uncued_reverse",
     "setup": ["Garen's friend is Hester."],
     "question": "Whose friend is Hester?", "gold": ["Garen"],
     "note": "friend without a value chain"},
    {"id": "n268-041", "family": "uncued_reverse",
     "setup": ["Iris's neighbour is Jalen.", "Jalen's boss is Koda."],
     "question": "Whose neighbour is Jalen?", "gold": ["Iris"],
     "note": "neighbour with a value chain"},
    {"id": "n268-042", "family": "uncued_reverse",
     "setup": ["Lena's neighbour is Milo."],
     "question": "Whose neighbour is Milo?", "gold": ["Lena"],
     "note": "neighbour without a value chain"},
    # ---------------- forward_chain (12) ----------------
    {"id": "n268-043", "family": "forward_chain",
     "setup": ["Aldo's spouse is Bel.", "Bel's employer is Halwick Labs."],
     "question": "Who is Aldo's spouse's employer?",
     "gold": ["Halwick Labs"],
     "note": "forward two-step over spouse then employer"},
    {"id": "n268-044", "family": "forward_chain",
     "setup": ["Cato's mother is Del.", "Del's boss is Ernie."],
     "question": "Who is Cato's mother's boss?", "gold": ["Ernie"],
     "note": "forward two-step over mother then boss"},
    {"id": "n268-045", "family": "forward_chain",
     "setup": ["Faye's friend is Gus.", "Gus's spouse is Hana."],
     "question": "Who is Faye's friend's spouse?", "gold": ["Hana"],
     "note": "forward two-step over friend then spouse"},
    {"id": "n268-046", "family": "forward_chain",
     "setup": ["Ivo's employer is Copper Finch.",
               "Copper Finch's founder is Wren."],
     "question": "Who is Ivo's employer's founder?", "gold": ["Wren"],
     "note": "forward two-step over employer then founder"},
    {"id": "n268-047", "family": "forward_chain",
     "setup": ["Juno's parent is Kip.", "Kip's mother is Lark."],
     "question": "Who is Juno's parent's mother?", "gold": ["Lark"],
     "note": "forward two-step over parent then mother"},
    {"id": "n268-048", "family": "forward_chain",
     "setup": ["Moe's wife is Nell.", "Nell's friend is Otto."],
     "question": "Who is Moe's wife's friend?", "gold": ["Otto"],
     "note": "forward two-step over wife then friend"},
    {"id": "n268-049", "family": "forward_chain",
     "setup": ["Paz's husband is Quin.", "Quin's employer is Bromley Press."],
     "question": "Who is Paz's husband's employer?",
     "gold": ["Bromley Press"],
     "note": "forward two-step over husband then employer"},
    {"id": "n268-050", "family": "forward_chain",
     "setup": ["Rhea's boss is Sol.", "Sol's spouse is Tove."],
     "question": "Who is Rhea's boss's spouse?", "gold": ["Tove"],
     "note": "forward two-step over boss then spouse"},
    {"id": "n268-051", "family": "forward_chain",
     "setup": ["Ulric's neighbour is Vera.", "Vera's mother is Wren."],
     "question": "Who is Ulric's neighbour's mother?", "gold": ["Wren"],
     "note": "forward two-step over neighbour then mother"},
    {"id": "n268-052", "family": "forward_chain",
     "setup": ["Xan's child is Yara.", "Yara's boss is Zeke."],
     "question": "Who is Xan's child's boss?", "gold": ["Zeke"],
     "note": "forward two-step over child then boss"},
    {"id": "n268-053", "family": "forward_chain",
     "setup": ["Salt Meridian's author is Oren.", "Oren's spouse is Pam."],
     "question": "Who is Salt Meridian's author's spouse?", "gold": ["Pam"],
     "note": "forward two-step from a book through its author"},
    {"id": "n268-054", "family": "forward_chain",
     "setup": ["Lumen Bakery's founder is Yuri.", "Yuri's friend is Zara."],
     "question": "Who is Lumen Bakery's founder's friend?", "gold": ["Zara"],
     "note": "forward two-step from a company through its founder"},
    # ---------------- forward_1hop (10) ----------------
    {"id": "n268-055", "family": "forward_1hop",
     "setup": ["Ari's spouse is Blaine."],
     "question": "Who is Ari's spouse?", "gold": ["Blaine"],
     "note": "single hop; spouse"},
    {"id": "n268-056", "family": "forward_1hop",
     "setup": ["Fog Ledger's author is Greta."],
     "question": "Who wrote Fog Ledger?", "gold": ["Greta"],
     "note": "single hop; author wrote-shape"},
    {"id": "n268-057", "family": "forward_1hop",
     "setup": ["Stone Mill's founder is Haldor."],
     "question": "Who founded Stone Mill?", "gold": ["Haldor"],
     "note": "single hop; founder founded-shape"},
    {"id": "n268-058", "family": "forward_1hop",
     "setup": ["Ilsa's employer is Northwind Traders."],
     "question": "Who is Ilsa's employer?", "gold": ["Northwind Traders"],
     "note": "single hop; employer"},
    {"id": "n268-059", "family": "forward_1hop",
     "setup": ["Joren's parent is Kara."],
     "question": "Who is Joren's parent?", "gold": ["Kara"],
     "note": "single hop; parent"},
    {"id": "n268-060", "family": "forward_1hop",
     "setup": ["Silent Harbor's composer is Ned."],
     "question": "Who composed Silent Harbor?", "gold": ["Ned"],
     "note": "single hop; composer composed-shape"},
    {"id": "n268-061", "family": "forward_1hop",
     "setup": ["Opal's husband is Perrin."],
     "question": "Who is Opal's husband?", "gold": ["Perrin"],
     "note": "single hop; husband"},
    {"id": "n268-062", "family": "forward_1hop",
     "setup": ["Dalia's friend is Emmett."],
     "question": "Who is Dalia's friend?", "gold": ["Emmett"],
     "note": "single hop; friend"},
    {"id": "n268-063", "family": "forward_1hop",
     "setup": ["Tess's boss is Udo."],
     "question": "Who is Tess's boss?", "gold": ["Udo"],
     "note": "single hop; boss"},
    {"id": "n268-064", "family": "forward_1hop",
     "setup": ["Yara's mother is Zola."],
     "question": "Who is Yara's mother?", "gold": ["Zola"],
     "note": "single hop; mother"},
    # ---------------- abstain (6) ----------------
    {"id": "n268-065", "family": "abstain",
     "setup": ["Viggo's spouse is Wren.", "Wren's employer is Halwick Labs."],
     "question": "Whose spouse is Xerxes?", "gold": [],
     "note": "value never taught; right reply abstains"},
    {"id": "n268-066", "family": "abstain",
     "setup": ["Ysolde's mother is Zane."],
     "question": "Who is married to Quintus?", "gold": [],
     "note": "name never taught; right reply abstains"},
    {"id": "n268-067", "family": "abstain",
     "setup": ["Cinder Works's founder is Blaze."],
     "question": "What did Coriander found?", "gold": [],
     "note": "founder never taught; right reply abstains"},
    {"id": "n268-068", "family": "abstain",
     "setup": ["Dusk's author is Ember."],
     "question": "What has Falstaff written?", "gold": [],
     "note": "author never taught; right reply abstains"},
    {"id": "n268-069", "family": "abstain",
     "setup": ["Gale's boss is Harbor."],
     "question": "Who is Icarus's employer?", "gold": [],
     "note": "worker never taught; right reply abstains"},
    {"id": "n268-070", "family": "abstain",
     "setup": ["Juniper's friend is Kelp.", "Kelp's spouse is Lark."],
     "question": "Whose parent is Morrow?", "gold": [],
     "note": "parent never taught; right reply abstains"},
]


def main() -> int:
    assert len(ITEMS) == 70, len(ITEMS)
    ids = [it["id"] for it in ITEMS]
    assert ids == [f"n268-{i:03d}" for i in range(1, 71)], ids[:5]
    from collections import Counter
    counts = Counter(it["family"] for it in ITEMS)
    expect = {"reverse_chain": 24, "reverse_nochain": 10,
              "uncued_reverse": 8, "forward_chain": 12,
              "forward_1hop": 10, "abstain": 6}
    assert dict(counts) == expect, dict(counts)
    for it in ITEMS:
        assert set(it) == {"id", "family", "setup", "question", "gold",
                           "note"}, set(it)
        assert 1 <= len(it["setup"]) <= 4, it["id"]
        assert isinstance(it["question"], str) and it["question"]
        assert isinstance(it["gold"], list)
        assert all(isinstance(g, str) for g in it["gold"])
    out = OUT_DIR / "panel.jsonl"
    with open(out, "w", encoding="utf-8") as f:
        for it in ITEMS:
            f.write(json.dumps(it, ensure_ascii=False) + "\n")
    print(f"Wrote {out} ({len(ITEMS)} items, {dict(counts)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
