"""Verifier-written held-out probes for 138m vs 138l. Turn prefixes: T| teach/correct (write allowed), Q| no write allowed. R = restart."""
import json
R="__RESTART__"
U="USER"
P=[]
def d(id,feat,turns,expect,note=""): P.append({"id":id,"feature":feat,"turns":turns,"expect_stored":expect,"note":note})
# a. identity: 16 wordings
for i,t in enumerate(["what's ur name","who made u","are you a person?","are you a robot","Are you an AI?","whats yuor name?","who built you","Who created you?","what should i call you","Do you have a name?","who is your creator?","what are you exactly?","tell me ur name pls","Who programmed you?","are u human"],1):
    d(f"A{i:02d}","identity",["Q|"+t],[])
d("A16","identity",["T|My name is Corvin.","Q|and what's your name?"],[[U,"name","Corvin"]],"must say Premonition, not Corvin")
# near-misses: must NOT get identity answer
d("N01","identity-nearmiss",["T|Tomas's boss is Mirela.","Q|What's Tomas's name?"],[["Tomas","boss","Mirela"]])
d("N02","identity-nearmiss",["T|Tomas lives in Varne.","Q|Who built Tomas's house?"],[["Tomas","city","Varne"]])
d("N03","identity-nearmiss",["Q|Who made the cake?"],[])
d("N04","identity-nearmiss",["Q|What is your favourite colour?"],[])
d("N05","identity-nearmiss",["Q|Who built the bridge in Harlow?"],[])
d("N06","identity-nearmiss",["T|Tomas's boss is Mirela.","Q|What is the name of Tomas's boss?"],[["Tomas","boss","Mirela"]],"should answer Mirela")
d("N07","identity-nearmiss",["Q|Who made Yarrow's dress?"],[])
d("N08","identity-nearmiss",["Q|Are you busy?"],[])
d("N09","identity-nearmiss",["Q|What's your city?"],[])
d("N10","identity-nearmiss",["Q|What is Quenby's name?"],[])
# b. user name line
d("B01","username",["T|My name is Pippa.","Q|What's my name?"],[[U,"name","Pippa"]])
d("B02","username",["T|Call me Ruthven.","Q|what is my name"],[[U,"name","Ruthven"]])
d("B03","username",["T|I'm Sabella.","Q|do you know my name?"],[[U,"name","Sabella"]])
d("B04","username",["T|My name is Oswin.","Q|Tell me what my name is."],[[U,"name","Oswin"]])
d("B05","username",["T|My name is Oswin.","Q|What do people call me?"],[[U,"name","Oswin"]])
d("B06","username",["T|my name's Delphine","Q|whats my name"],[[U,"name","Delphine"]])
d("B07","username",["T|My name is Hollis.","T|Actually, my name is Harlan.","Q|What is my name?"],[[U,"name","Harlan"]])
d("B08","username",["T|My name is Hollis.","T|No, my name is Harlan, not Hollis.","Q|what's my name?"],[[U,"name","Harlan"]])
d("B09","username",["Q|What's my name?"],[])
d("B10","username",["Q|do you know who I am?"],[])
d("B11","username",["T|My name is Wren.","Q|Say my name."],[[U,"name","Wren"]])
d("B12","username",["T|My name is Wren.","Q|Do you remember my name?"],[[U,"name","Wren"]])
d("B13","username",["T|My name is Isolde.","Q|Who am I?"],[[U,"name","Isolde"]])
d("B14","username",["T|My name is Isolde.","Q|What did I say my name was?"],[[U,"name","Isolde"]])
d("B15","username",["T|Please call me Fenna.","Q|What's my name?"],[[U,"name","Fenna"]])
d("B16","username",["T|My name is Marek.","Q|Who made your notebook?"],[[U,"name","Marek"]],"USER leak check")
d("B17","username",["T|My name is Marek.","Q|What do you know about me?"],[[U,"name","Marek"]],"USER leak check")
d("B18","username",["Q|Repeat my name."],[])
d("B19","username",["T|My name is Tamsin.","Q|what's my name again"],[[U,"name","Tamsin"]])
d("B20","username",["T|My name is Tamsin.","Q|can you tell me my name?"],[[U,"name","Tamsin"]])
# c. decline: parseable, no fact
d("C01","decline",["T|Tomas's boss is Mirela.","Q|What is Tomas's city?"],[["Tomas","boss","Mirela"]],"unknown relation of known person")
d("C02","decline",["Q|Who is Garrick's boss?"],[],"unknown person")
d("C03","decline",["T|Tomas's boss is Mirela.","Q|Who is Yarrow's boss?"],[["Tomas","boss","Mirela"]],"relation known for others")
d("C04","decline",["T|Belisande lives in Oxmoor.","Q|Where does Corvin live?"],[["Belisande","city","Oxmoor"]],"relation known for others")
d("C05","decline",["T|Belisande lives in Oxmoor.","Q|Where does Belisande work?"],[["Belisande","city","Oxmoor"]],"unknown relation of known person")
d("C06","decline",["T|Tomas's sister is Liesl.","Q|who is tomas's brother?"],[["Tomas","sister","Liesl"]],"unknown relation of known person")
d("C07","decline",["Q|What is Pell's job?"],[],"unknown person")
d("C08","decline",["T|Ada's job is baker.","Q|What is Ada's favourite colour?"],[["Ada","job","baker"]],"unknown relation of known person")
d("C09","decline",["Q|Where was Bramwell born?"],[],"unknown person")
d("C10","decline",["T|Corvin's mother is Hesper.","Q|Who is Hesper's mother?"],[["Corvin","mother","Hesper"]],"relation known for others")
d("C11","decline",["T|Corvin's mother is Hesper.","Q|Who is Corvin's father?"],[["Corvin","mother","Hesper"]],"unknown relation of known person")
d("C12","decline",["Q|Where does Pell live?"],[],"unknown person")
d("C13","decline",["T|Brisa works for Halvex.","Q|Who does Dace work for?"],[["Brisa","employer","Halvex"]],"relation known for others")
d("C14","decline",["Q|Who is Tomas married to?"],[],"unknown person")
# d. polite wrappers
d("D01","polite",["T|Please remember that Tomas's boss is Mirela.","Q|Who is Tomas's boss?"],[["Tomas","boss","Mirela"]])
d("D02","polite",["T|Tomas's boss is Mirela.","Q|Could you tell me who Tomas's boss is?"],[["Tomas","boss","Mirela"]])
d("D03","polite",["T|Tomas's boss is Mirela.","Q|Do you mind telling me who Tomas's boss is?"],[["Tomas","boss","Mirela"]])
d("D04","polite",["T|Could you please remember that Yarrow lives in Keld?","Q|Where does Yarrow live?"],[["Yarrow","city","Keld"]])
d("D05","polite",["T|Yarrow lives in Keld.","Q|Please tell me where Yarrow lives."],[["Yarrow","city","Keld"]])
d("D06","polite",["Q|Could you tell me who Quenby's boss is?"],[])
d("D07","polite",["T|My name is Pippa.","Q|Do you mind telling me my name?"],[[U,"name","Pippa"]])
d("D08","polite",["T|Tomas's boss is Mirela.","Q|Please, who is Tomas's boss?"],[["Tomas","boss","Mirela"]])
d("D09","polite",["T|Tomas's boss is Mirela.","T|Please note that Tomas's boss is actually Ostrander.","Q|Who is Tomas's boss?"],[["Tomas","boss","Ostrander"]])
d("D10","polite",["T|Please, Kestrel's job is fisher.","Q|could you tell me Kestrel's job please?"],[["Kestrel","job","fisher"]])
# e. small talk
for i,t in enumerate(["hi","how are you?","how's it going","what's up?","thanks!","hello there","thank you so much","hey, how are you doing?"],1):
    d(f"E{i:02d}","smalltalk",["Q|"+t],[])
d("E09","smalltalk",["T|Tomas's boss is Mirela.","Q|thanks","Q|how's it going?","Q|Who is Tomas's boss?"],[["Tomas","boss","Mirela"]])
d("E10","smalltalk",["Q|Hi! What's your name?"],[])
# f. restarts
d("R01","restart",["T|Tomas's boss is Mirela.",R,"Q|Who is Tomas's boss?","Q|What is Tomas's city?"],[["Tomas","boss","Mirela"]])
d("R02","restart",["T|My name is Pippa.",R,"Q|What's my name?"],[[U,"name","Pippa"]])
d("R03","restart",["T|My name is Pippa.","T|Actually my name is Perrin.",R,"Q|What is my name?"],[[U,"name","Perrin"]])
d("R04","restart",["T|Yarrow lives in Keld.","T|No, Yarrow lives in Dunmore.",R,"Q|Where does Yarrow live?"],[["Yarrow","city","Dunmore"]])
d("R05","restart",["Q|hi","Q|how are you?",R,"Q|What's my name?","Q|Who is Tomas's boss?"],[])
d("R06","restart",["Q|Who made you?","T|Corvin's mother is Hesper.",R,"Q|what's your name","Q|Who is Corvin's mother?","Q|Who is Corvin's father?"],[["Corvin","mother","Hesper"]])
d("R07","restart",["T|Please remember that Tomas's job is carpenter.",R,"Q|Could you tell me Tomas's job?"],[["Tomas","job","carpenter"]])
# controls
d("K01","control",["T|Ada's mother is Lisbet.","Q|Who is Ada's mother?"],[["Ada","mother","Lisbet"]])
d("K02","control",["T|Ada's mother is Lisbet.","Q|Ada's mother is Moira.","Q|Who is Ada's mother?"],[["Ada","mother","Lisbet"]],"conflict must ask, not overwrite")
d("K03","control",["T|Bram's boss is Ivo.","T|Ivo's city is Tallow.","Q|What is the city of Bram's boss?"],[["Bram","boss","Ivo"],["Ivo","city","Tallow"]])
d("K04","control",["T|Kestrel's job is fisher.","Q|What is Kestrel's job?"],[["Kestrel","job","fisher"]])
d("K05","control",["T|Nell lives in Orrin.","Q|Where does Nell live?"],[["Nell","city","Orrin"]])
d("K06","control",["T|Nell's boss is Tam.","T|No, Nell's boss is Wick.","Q|Who is Nell's boss?"],[["Nell","boss","Wick"]])
d("K07","control",["T|Fitch works for Grobal.","Q|Who does Fitch work for?"],[["Fitch","employer","Grobal"]])
d("K08","control",["T|Juno was born in Ashby.","Q|Where was Juno born?"],[["Juno","place_of_birth","Ashby"]])
d("K09","control",["T|Hale's sister is Orla.","T|Orla's husband is Dunstan.","Q|Who is Hale's sister's husband?"],[["Hale","sister","Orla"],["Orla","husband","Dunstan"]])
d("K10","control",["T|Pim's favourite colour is teal.","Q|What is Pim's favourite colour?"],[["Pim","favourite_colour","teal"]])
d("K11","control",["T|Tove's boss is Anselm.","Q|Is Tove's boss Anselm?"],[["Tove","boss","Anselm"]])
json.dump(P,open("probes.json","w"),indent=1)
from collections import Counter; print(len(P),Counter(p["feature"] for p in P))
