#!/usr/bin/env python3
"""invpanel138nb panel writer. Builds panel.jsonl (70 items). All sentences fresh fictional."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "panel.jsonl"

ITEMS = [
    # whose_R 14: 8 single + 6 double. Relations across 9 rels, max 3.
    {"id": "i138nb-001", "family": "whose_R", "setup": ["Petra's boss is Harlan."], "question": "Whose boss is Harlan?", "gold": ["Petra"], "backwards": True, "stored_after_setup": [["Petra", "boss", "Harlan"]], "note": "single-subject backwards lookup"},
    {"id": "i138nb-002", "family": "whose_R", "setup": ["Darin Cole's mother is Selma."], "question": "Whose mother is Selma?", "gold": ["Darin Cole"], "backwards": True, "stored_after_setup": [["Darin Cole", "mother", "Selma"]], "note": "single-subject backwards lookup"},
    {"id": "i138nb-003", "family": "whose_R", "setup": ["Kessa's father is Bram."], "question": "Whose father is Bram?", "gold": ["Kessa"], "backwards": True, "stored_after_setup": [["Kessa", "father", "Bram"]], "note": "single-subject backwards lookup"},
    {"id": "i138nb-004", "family": "whose_R", "setup": ["Theo Marsh's doctor is Ilsa."], "question": "Whose doctor is Ilsa?", "gold": ["Theo Marsh"], "backwards": True, "stored_after_setup": [["Theo Marsh", "doctor", "Ilsa"]], "note": "single-subject backwards lookup"},
    {"id": "i138nb-005", "family": "whose_R", "setup": ["Wren's coach is Pavel."], "question": "Whose coach is Pavel?", "gold": ["Wren"], "backwards": True, "stored_after_setup": [["Wren", "coach", "Pavel"]], "note": "single-subject backwards lookup"},
    {"id": "i138nb-006", "family": "whose_R", "setup": ["Nadia Frost's teacher is Orson."], "question": "Whose teacher is Orson?", "gold": ["Nadia Frost"], "backwards": True, "stored_after_setup": [["Nadia Frost", "teacher", "Orson"]], "note": "single-subject backwards lookup"},
    {"id": "i138nb-007", "family": "whose_R", "setup": ["Colm's employer is Halcyon Books."], "question": "Whose employer is Halcyon Books?", "gold": ["Colm"], "backwards": True, "stored_after_setup": [["Colm", "employer", "Halcyon Books"]], "note": "single-subject backwards lookup"},
    {"id": "i138nb-008", "family": "whose_R", "setup": ["Vera Lynn's wife is Odette."], "question": "Whose wife is Odette?", "gold": ["Vera Lynn"], "backwards": True, "stored_after_setup": [["Vera Lynn", "wife", "Odette"]], "note": "single-subject backwards lookup"},
    {"id": "i138nb-009", "family": "whose_R", "setup": ["Juno's boss is Harlan.", "Felix Grant's boss is Harlan."], "question": "Whose boss is Harlan?", "gold": ["Juno", "Felix Grant"], "backwards": True, "stored_after_setup": [["Juno", "boss", "Harlan"], ["Felix Grant", "boss", "Harlan"]], "note": "two subjects share the value"},
    {"id": "i138nb-010", "family": "whose_R", "setup": ["Mira Sol's boss is Kern.", "Dov's boss is Kern."], "question": "Whose boss is Kern?", "gold": ["Mira Sol", "Dov"], "backwards": True, "stored_after_setup": [["Mira Sol", "boss", "Kern"], ["Dov", "boss", "Kern"]], "note": "two subjects share the value"},
    {"id": "i138nb-011", "family": "whose_R", "setup": ["Alba's mother is Selma.", "Ruth Ann's mother is Selma."], "question": "Whose mother is Selma?", "gold": ["Alba", "Ruth Ann"], "backwards": True, "stored_after_setup": [["Alba", "mother", "Selma"], ["Ruth Ann", "mother", "Selma"]], "note": "two subjects share the value"},
    {"id": "i138nb-012", "family": "whose_R", "setup": ["Sten's father is Bram.", "Hugo Vale's father is Bram."], "question": "Whose father is Bram?", "gold": ["Sten", "Hugo Vale"], "backwards": True, "stored_after_setup": [["Sten", "father", "Bram"], ["Hugo Vale", "father", "Bram"]], "note": "two subjects share the value"},
    {"id": "i138nb-013", "family": "whose_R", "setup": ["Ida's friend is Nils.", "Clara Moon's friend is Nils."], "question": "Whose friend is Nils?", "gold": ["Ida", "Clara Moon"], "backwards": True, "stored_after_setup": [["Ida", "friend", "Nils"], ["Clara Moon", "friend", "Nils"]], "note": "two subjects share the value"},
    {"id": "i138nb-014", "family": "whose_R", "setup": ["Otto Reed's friend is Sana.", "Lida's friend is Sana."], "question": "Whose friend is Sana?", "gold": ["Otto Reed", "Lida"], "backwards": True, "stored_after_setup": [["Otto Reed", "friend", "Sana"], ["Lida", "friend", "Sana"]], "note": "two subjects share the value"},
    # lives_born 10: 5 lives + 5 born, 4 double.
    {"id": "i138nb-015", "family": "lives_born", "setup": ["Bram's city is Alderport."], "question": "Who lives in Alderport?", "gold": ["Bram"], "backwards": True, "stored_after_setup": [["Bram", "city", "Alderport"]], "note": "city to resident lookup"},
    {"id": "i138nb-016", "family": "lives_born", "setup": ["June Park's city is Brynwick."], "question": "Who lives in Brynwick?", "gold": ["June Park"], "backwards": True, "stored_after_setup": [["June Park", "city", "Brynwick"]], "note": "city to resident lookup"},
    {"id": "i138nb-017", "family": "lives_born", "setup": ["Sella's city is Alderport.", "Corvin Dale's city is Alderport."], "question": "Who lives in Alderport?", "gold": ["Sella", "Corvin Dale"], "backwards": True, "stored_after_setup": [["Sella", "city", "Alderport"], ["Corvin Dale", "city", "Alderport"]], "note": "two residents share the city"},
    {"id": "i138nb-018", "family": "lives_born", "setup": ["Tilda's city is Marlowe."], "question": "Who lives in Marlowe?", "gold": ["Tilda"], "backwards": True, "stored_after_setup": [["Tilda", "city", "Marlowe"]], "note": "city to resident lookup"},
    {"id": "i138nb-019", "family": "lives_born", "setup": ["Edvin's city is Kestrel Bay.", "Maren Holt's city is Kestrel Bay."], "question": "Who lives in Kestrel Bay?", "gold": ["Edvin", "Maren Holt"], "backwards": True, "stored_after_setup": [["Edvin", "city", "Kestrel Bay"], ["Maren Holt", "city", "Kestrel Bay"]], "note": "two residents share the city"},
    {"id": "i138nb-020", "family": "lives_born", "setup": ["Oskar's birthplace is Vennor."], "question": "Who was born in Vennor?", "gold": ["Oskar"], "backwards": True, "stored_after_setup": [["Oskar", "birthplace", "Vennor"]], "note": "birthplace to person lookup"},
    {"id": "i138nb-021", "family": "lives_born", "setup": ["Lena Marsh's birthplace is Gullhaven."], "question": "Who was born in Gullhaven?", "gold": ["Lena Marsh"], "backwards": True, "stored_after_setup": [["Lena Marsh", "birthplace", "Gullhaven"]], "note": "birthplace to person lookup"},
    {"id": "i138nb-022", "family": "lives_born", "setup": ["Pavel's birthplace is Vennor.", "Sonia Rill's birthplace is Vennor."], "question": "Who was born in Vennor?", "gold": ["Pavel", "Sonia Rill"], "backwards": True, "stored_after_setup": [["Pavel", "birthplace", "Vennor"], ["Sonia Rill", "birthplace", "Vennor"]], "note": "two people share the birthplace"},
    {"id": "i138nb-023", "family": "lives_born", "setup": ["Dara's birthplace is Plumstead."], "question": "Who was born in Plumstead?", "gold": ["Dara"], "backwards": True, "stored_after_setup": [["Dara", "birthplace", "Plumstead"]], "note": "birthplace to person lookup"},
    {"id": "i138nb-024", "family": "lives_born", "setup": ["Ivo Lind's birthplace is Cairnhill.", "Bessa's birthplace is Cairnhill."], "question": "Who was born in Cairnhill?", "gold": ["Ivo Lind", "Bessa"], "backwards": True, "stored_after_setup": [["Ivo Lind", "birthplace", "Cairnhill"], ["Bessa", "birthplace", "Cairnhill"]], "note": "two people share the birthplace"},
    # has_as 6: 4 single + 2 double.
    {"id": "i138nb-025", "family": "has_as", "setup": ["Farah's dentist is Quin."], "question": "Who has Quin as their dentist?", "gold": ["Farah"], "backwards": True, "stored_after_setup": [["Farah", "dentist", "Quin"]], "note": "has-as phrasing backwards lookup"},
    {"id": "i138nb-026", "family": "has_as", "setup": ["Emmett Stone's doctor is Wrenley."], "question": "Who has Wrenley as his doctor?", "gold": ["Emmett Stone"], "backwards": True, "stored_after_setup": [["Emmett Stone", "doctor", "Wrenley"]], "note": "has-as phrasing backwards lookup"},
    {"id": "i138nb-027", "family": "has_as", "setup": ["Priya Nair's teacher is Hollis."], "question": "Who has Hollis as her teacher?", "gold": ["Priya Nair"], "backwards": True, "stored_after_setup": [["Priya Nair", "teacher", "Hollis"]], "note": "has-as phrasing backwards lookup"},
    {"id": "i138nb-028", "family": "has_as", "setup": ["Garran's coach is Vesper."], "question": "Who has Vesper as their coach?", "gold": ["Garran"], "backwards": True, "stored_after_setup": [["Garran", "coach", "Vesper"]], "note": "has-as phrasing backwards lookup"},
    {"id": "i138nb-029", "family": "has_as", "setup": ["Tilda Frost's neighbour is Bramwell.", "Ondine's neighbour is Bramwell."], "question": "Who has Bramwell as their neighbour?", "gold": ["Tilda Frost", "Ondine"], "backwards": True, "stored_after_setup": [["Tilda Frost", "neighbour", "Bramwell"], ["Ondine", "neighbour", "Bramwell"]], "note": "two subjects share the value"},
    {"id": "i138nb-030", "family": "has_as", "setup": ["Sarella's husband is Corvin.", "Mira Patel's husband is Corvin."], "question": "Who has Corvin as her husband?", "gold": ["Sarella", "Mira Patel"], "backwards": True, "stored_after_setup": [["Sarella", "husband", "Corvin"], ["Mira Patel", "husband", "Corvin"]], "note": "two subjects share the value"},
    # verb_backwards 10: 7 single + 3 double.
    {"id": "i138nb-031", "family": "verb_backwards", "setup": ["Devon Rill's manager is Sorrel."], "question": "Who does Sorrel manage?", "gold": ["Devon Rill"], "backwards": True, "stored_after_setup": [["Devon Rill", "manager", "Sorrel"]], "note": "verb backwards lookup"},
    {"id": "i138nb-032", "family": "verb_backwards", "setup": ["Kira's manager is Sorrel.", "Bram Noble's manager is Sorrel."], "question": "Who does Sorrel manage?", "gold": ["Kira", "Bram Noble"], "backwards": True, "stored_after_setup": [["Kira", "manager", "Sorrel"], ["Bram Noble", "manager", "Sorrel"]], "note": "two subjects share the value"},
    {"id": "i138nb-033", "family": "verb_backwards", "setup": ["Elif Demir's teacher is Voss."], "question": "Who does Voss teach?", "gold": ["Elif Demir"], "backwards": True, "stored_after_setup": [["Elif Demir", "teacher", "Voss"]], "note": "verb backwards lookup"},
    {"id": "i138nb-034", "family": "verb_backwards", "setup": ["Noa's coach is Tam."], "question": "Who does Tam coach?", "gold": ["Noa"], "backwards": True, "stored_after_setup": [["Noa", "coach", "Tam"]], "note": "verb backwards lookup"},
    {"id": "i138nb-035", "family": "verb_backwards", "setup": ["Hollis Ray's employer is Copperline Press."], "question": "Who works at Copperline Press?", "gold": ["Hollis Ray"], "backwards": True, "stored_after_setup": [["Hollis Ray", "employer", "Copperline Press"]], "note": "verb backwards lookup"},
    {"id": "i138nb-036", "family": "verb_backwards", "setup": ["Sanne's employer is Copperline Press.", "Viggo Lund's employer is Copperline Press."], "question": "Who works at Copperline Press?", "gold": ["Sanne", "Viggo Lund"], "backwards": True, "stored_after_setup": [["Sanne", "employer", "Copperline Press"], ["Viggo Lund", "employer", "Copperline Press"]], "note": "two subjects share the value"},
    {"id": "i138nb-037", "family": "verb_backwards", "setup": ["The Amber Lighthouse's composer is Delphine."], "question": "What did Delphine compose?", "gold": ["The Amber Lighthouse"], "backwards": True, "stored_after_setup": [["The Amber Lighthouse", "composer", "Delphine"]], "note": "work title to composer lookup"},
    {"id": "i138nb-038", "family": "verb_backwards", "setup": ["The Copper Fox's author is Isolde."], "question": "What did Isolde write?", "gold": ["The Copper Fox"], "backwards": True, "stored_after_setup": [["The Copper Fox", "author", "Isolde"]], "note": "work title to author lookup"},
    {"id": "i138nb-039", "family": "verb_backwards", "setup": ["The Silent Orchard's author is Isolde.", "Willowfall's author is Isolde."], "question": "What did Isolde write?", "gold": ["The Silent Orchard", "Willowfall"], "backwards": True, "stored_after_setup": [["The Silent Orchard", "author", "Isolde"], ["Willowfall", "author", "Isolde"]], "note": "two works share the author"},
    {"id": "i138nb-040", "family": "verb_backwards", "setup": ["The Pale Meridian's painter is Cressida."], "question": "What did Cressida paint?", "gold": ["The Pale Meridian"], "backwards": True, "stored_after_setup": [["The Pale Meridian", "painter", "Cressida"]], "note": "work title to painter lookup"},
    # my_backwards 4.
    {"id": "i138nb-041", "family": "my_backwards", "setup": ["My boss is Ansel.", "Rhea's boss is Ansel."], "question": "Whose boss is Ansel?", "gold": ["Rhea"], "backwards": True, "stored_after_setup": [["you", "boss", "Ansel"], ["Rhea", "boss", "Ansel"]], "note": "reply must also refer to the user with your or you"},
    {"id": "i138nb-042", "family": "my_backwards", "setup": ["My doctor is Fenwick.", "Jonas Pike's doctor is Fenwick."], "question": "Whose doctor is Fenwick?", "gold": ["Jonas Pike"], "backwards": True, "stored_after_setup": [["you", "doctor", "Fenwick"], ["Jonas Pike", "doctor", "Fenwick"]], "note": "reply must also refer to the user with your or you"},
    {"id": "i138nb-043", "family": "my_backwards", "setup": ["My city is Harborton.", "Sable's city is Harborton."], "question": "Who lives in Harborton?", "gold": ["Sable"], "backwards": True, "stored_after_setup": [["you", "city", "Harborton"], ["Sable", "city", "Harborton"]], "note": "reply must also refer to the user with your or you"},
    {"id": "i138nb-044", "family": "my_backwards", "setup": ["My friend is Talia.", "Moss Hart's friend is Talia."], "question": "Whose friend is Talia?", "gold": ["Moss Hart"], "backwards": True, "stored_after_setup": [["you", "friend", "Talia"], ["Moss Hart", "friend", "Talia"]], "note": "reply must also refer to the user with your or you"},
    # no_match 8.
    {"id": "i138nb-045", "family": "no_match", "setup": ["Elsa's mother is Greta."], "question": "Whose boss is Greta?", "gold": [], "backwards": True, "stored_after_setup": [["Elsa", "mother", "Greta"]], "note": "value taught under another relation; must abstain"},
    {"id": "i138nb-046", "family": "no_match", "setup": ["Casper Holt's city is Dunmere."], "question": "Who was born in Dunmere?", "gold": [], "backwards": True, "stored_after_setup": [["Casper Holt", "city", "Dunmere"]], "note": "value taught under another relation; must abstain"},
    {"id": "i138nb-047", "family": "no_match", "setup": ["Ines's doctor is Farid."], "question": "Whose dentist is Farid?", "gold": [], "backwards": True, "stored_after_setup": [["Ines", "doctor", "Farid"]], "note": "value taught under another relation; must abstain"},
    {"id": "i138nb-048", "family": "no_match", "setup": ["Rurik's employer is Saltline Yarns."], "question": "Who lives in Saltline Yarns?", "gold": [], "backwards": True, "stored_after_setup": [["Rurik", "employer", "Saltline Yarns"]], "note": "value taught under another relation; must abstain"},
    {"id": "i138nb-049", "family": "no_match", "setup": ["Hedda Vale's teacher is Ludo."], "question": "Who does Ludo manage?", "gold": [], "backwards": True, "stored_after_setup": [["Hedda Vale", "teacher", "Ludo"]], "note": "value taught under another relation; must abstain"},
    {"id": "i138nb-050", "family": "no_match", "setup": ["Filip's birthplace is Ostrell."], "question": "Who lives in Ostrell?", "gold": [], "backwards": True, "stored_after_setup": [["Filip", "birthplace", "Ostrell"]], "note": "value taught under another relation; must abstain"},
    {"id": "i138nb-051", "family": "no_match", "setup": ["Soraya's husband is Kent."], "question": "Whose friend is Kent?", "gold": [], "backwards": True, "stored_after_setup": [["Soraya", "husband", "Kent"]], "note": "value taught under another relation; must abstain"},
    {"id": "i138nb-052", "family": "no_match", "setup": ["Bramwell's coach is Odile."], "question": "Who does Odile teach?", "gold": [], "backwards": True, "stored_after_setup": [["Bramwell", "coach", "Odile"]], "note": "value taught under another relation; must abstain"},
    # unknown_value 4.
    {"id": "i138nb-053", "family": "unknown_value", "setup": ["Tilda's boss is Marta."], "question": "Whose boss is Zell?", "gold": [], "backwards": True, "stored_after_setup": [["Tilda", "boss", "Marta"]], "note": "asked value never taught; must abstain"},
    {"id": "i138nb-054", "family": "unknown_value", "setup": ["Fenna's city is Larkspur."], "question": "Who lives in Quillhaven?", "gold": [], "backwards": True, "stored_after_setup": [["Fenna", "city", "Larkspur"]], "note": "asked value never taught; must abstain"},
    {"id": "i138nb-055", "family": "unknown_value", "setup": ["Edda's teacher is Roscoe."], "question": "Who does Merritt teach?", "gold": [], "backwards": True, "stored_after_setup": [["Edda", "teacher", "Roscoe"]], "note": "asked value never taught; must abstain"},
    {"id": "i138nb-056", "family": "unknown_value", "setup": ["Lorne's friend is Sabine."], "question": "Whose friend is Xanthe?", "gold": [], "backwards": True, "stored_after_setup": [["Lorne", "friend", "Sabine"]], "note": "asked value never taught; must abstain"},
    # forward_control 10.
    {"id": "i138nb-057", "family": "forward_control", "setup": ["Aldis's boss is Petra."], "question": "Who is Aldis's boss?", "gold": ["Petra"], "backwards": False, "stored_after_setup": [["Aldis", "boss", "Petra"]], "note": "forward control question"},
    {"id": "i138nb-058", "family": "forward_control", "setup": ["Nora Bliss's mother is Tilda."], "question": "Who is Nora Bliss's mother?", "gold": ["Tilda"], "backwards": False, "stored_after_setup": [["Nora Bliss", "mother", "Tilda"]], "note": "forward control question"},
    {"id": "i138nb-059", "family": "forward_control", "setup": ["Kellen's city is Fernhill."], "question": "Where does Kellen live?", "gold": ["Fernhill"], "backwards": False, "stored_after_setup": [["Kellen", "city", "Fernhill"]], "note": "forward control question"},
    {"id": "i138nb-060", "family": "forward_control", "setup": ["Ilsa Fay's birthplace is Norbury."], "question": "Where was Ilsa Fay born?", "gold": ["Norbury"], "backwards": False, "stored_after_setup": [["Ilsa Fay", "birthplace", "Norbury"]], "note": "forward control question"},
    {"id": "i138nb-061", "family": "forward_control", "setup": ["Rook's doctor is Eamon."], "question": "Who is Rook's doctor?", "gold": ["Eamon"], "backwards": False, "stored_after_setup": [["Rook", "doctor", "Eamon"]], "note": "forward control question"},
    {"id": "i138nb-062", "family": "forward_control", "setup": ["Sable Wren's teacher is Fitch."], "question": "Who is Sable Wren's teacher?", "gold": ["Fitch"], "backwards": False, "stored_after_setup": [["Sable Wren", "teacher", "Fitch"]], "note": "forward control question"},
    {"id": "i138nb-063", "family": "forward_control", "setup": ["Tam's employer is Brindle Press."], "question": "Who is Tam's employer?", "gold": ["Brindle Press"], "backwards": False, "stored_after_setup": [["Tam", "employer", "Brindle Press"]], "note": "forward control question"},
    {"id": "i138nb-064", "family": "forward_control", "setup": ["The Briar Lantern's author is Vesper."], "question": "Who is The Briar Lantern's author?", "gold": ["Vesper"], "backwards": False, "stored_after_setup": [["The Briar Lantern", "author", "Vesper"]], "note": "forward control question"},
    {"id": "i138nb-065", "family": "forward_control", "setup": ["Odile's friend is Marco."], "question": "Who is Odile's friend?", "gold": ["Marco"], "backwards": False, "stored_after_setup": [["Odile", "friend", "Marco"]], "note": "forward control question"},
    {"id": "i138nb-066", "family": "forward_control", "setup": ["Jasper Vale's coach is Linnea."], "question": "Who is Jasper Vale's coach?", "gold": ["Linnea"], "backwards": False, "stored_after_setup": [["Jasper Vale", "coach", "Linnea"]], "note": "forward control question"},
    # teach_control 4.
    {"id": "i138nb-067", "family": "teach_control", "setup": ["Maren's dentist is Ossa."], "question": "Quill's dentist is Runa.", "gold": [], "backwards": False, "stored_after_setup": [["Maren", "dentist", "Ossa"]], "note": "statement turn; stores its own triple"},
    {"id": "i138nb-068", "family": "teach_control", "setup": ["Anya Sol's city is Eastvale."], "question": "Bram Kite's city is Westvale.", "gold": [], "backwards": False, "stored_after_setup": [["Anya Sol", "city", "Eastvale"]], "note": "statement turn; stores its own triple"},
    {"id": "i138nb-069", "family": "teach_control", "setup": ["Finn's friend is Gala."], "question": "Tove's friend is Homer.", "gold": [], "backwards": False, "stored_after_setup": [["Finn", "friend", "Gala"]], "note": "statement turn; stores its own triple"},
    {"id": "i138nb-070", "family": "teach_control", "setup": ["The Hollow Crown's painter is Miro."], "question": "Duskhaven's painter is Petra Quinn.", "gold": [], "backwards": False, "stored_after_setup": [["The Hollow Crown", "painter", "Miro"]], "note": "statement turn; stores its own triple"},
]


def main():
    assert len(ITEMS) == 70, len(ITEMS)
    from collections import Counter
    c = Counter(x["family"] for x in ITEMS)
    expect = {"whose_R": 14, "lives_born": 10, "has_as": 6, "verb_backwards": 10, "my_backwards": 4, "no_match": 8, "unknown_value": 4, "forward_control": 10, "teach_control": 4}
    assert dict(c) == expect, c
    ids = [x["id"] for x in ITEMS]
    assert ids == [f"i138nb-{i:03d}" for i in range(1, 71)], ids[:5]
    OUT.write_text("".join(json.dumps(x, ensure_ascii=False) + "\n" for x in ITEMS), encoding="utf-8")
    print(f"wrote {OUT} {len(ITEMS)} items")


if __name__ == "__main__":
    main()
