# Follow-up controls to classify the failures found in dialogs.py. Fictional names only.
C, E, L, B = "city", "employer", "language", "place_of_birth"
D = [
 ("c00", "retraction, one-word, same phrasing",
  [("Ines works at Brindlecorp.", None),
   ("That's not true, Ines doesn't work at Brindlecorp.", None),
   ("Where does Ines work?", "")], [("ines", E, "brindlecorp")]),
 ("c01", "retraction, multi-word, bare negation",
  [("Ines da Varrow works at Brindlecorp.", None),
   ("Ines da Varrow doesn't work at Brindlecorp.", None),
   ("Where does Ines da Varrow work?", "")], [("ines da varrow", E, "brindlecorp")]),
 ("c02", "retraction, one-word, bare negation",
  [("Ines works at Brindlecorp.", None),
   ("Ines doesn't work at Brindlecorp.", None),
   ("Where does Ines work?", "")], [("ines", E, "brindlecorp")]),
 ("c03", "retraction, multi-word, 'that's wrong'",
  [("Ines da Varrow works at Brindlecorp.", None),
   ("That's wrong.", None),
   ("Where does Ines da Varrow work?", "")], [("ines da varrow", E, "brindlecorp")]),
 ("c04", "retraction, one-word, 'that's wrong'",
  [("Ines works at Brindlecorp.", None),
   ("That's wrong.", None),
   ("Where does Ines work?", "")], [("ines", E, "brindlecorp")]),
 ("c05", "question wordings, one-word",
  [("Tessa speaks Norric.", None), ("Tessa was born in Harrowby.", None),
   ("Which language does Tessa speak?", "Norric"),
   ("In which city was Tessa born?", "Harrowby"),
   ("What does Tessa speak?", "Norric")],
  [("tessa", L, "norric"), ("tessa", B, "harrowby")]),
 ("c06", "lowercase d' vs capital D'",
  [("Pierre d'Arvenne lives in Dunmere.", None),
   ("Pierre D'Arvenne speaks Norric.", None),
   ("Where does Pierre d'Arvenne live?", "Dunmere"),
   ("What language does Pierre D'Arvenne speak?", "Norric")],
  [("pierre d'arvenne", C, "dunmere"), ("pierre d'arvenne", L, "norric")]),
 ("c07", "Osterby 'why' quirk, one-word",
  [("Brannoc lives in Osterby.", None), ("Where does Brannoc live?", "Osterby")],
  [("brannoc", C, "osterby")]),
]
