# Fresh verifier dialogs for 232c. Fictional names only.
# Each dialog: (id, note, turns, allowed_triples)
# turn = (text, gold) ; gold None = teach/other turn, "" = must abstain (no value), str = value expected.
C, E, L, B = "city", "employer", "language", "place_of_birth"
D = [
 ("v00", "van der; several city wordings; capitalised particle",
  [("Oskar van der Brelling lives in Quellport.", None),
   ("Where does Oskar van der Brelling live?", "Quellport"),
   ("What city does Oskar van der Brelling live in?", "Quellport"),
   ("Where does Oskar Van der Brelling live?", "Quellport"),
   ("Where does Oskar Brelling live?", "")],
  [("oskar van der brelling", C, "quellport")]),
 ("v01", "de la; works at; employer wordings",
  [("Lucia de la Farrow works at Brindlecorp.", None),
   ("Where does Lucia de la Farrow work?", "Brindlecorp"),
   ("Who does Lucia de la Farrow work for?", "Brindlecorp"),
   ("What is Lucia de la Farrow's employer?", "Brindlecorp"),
   ("Where does Lucia Farrow work?", "")],
  [("lucia de la farrow", E, "brindlecorp")]),
 ("v02", "bin + ibn; speaks + born",
  [("Tariq bin Qasrel speaks Veltish.", None),
   ("Yusra ibn Hadrel was born in Farrowgate.", None),
   ("What language does Tariq bin Qasrel speak?", "Veltish"),
   ("Which language does Tariq bin Qasrel speak?", "Veltish"),
   ("Where was Yusra ibn Hadrel born?", "Farrowgate"),
   ("What is Yusra ibn Hadrel's birthplace?", "Farrowgate"),
   ("Where was Tariq bin Qasrel born?", "")],
  [("tariq bin qasrel", L, "veltish"), ("yusra ibn hadrel", B, "farrowgate")]),
 ("v03", "al + ap; works for + lives in",
  [("Samir al Venhouri works for Coldmere Mills.", None),
   ("Rhys ap Gwenlor lives in Tillmarsh.", None),
   ("Who does Samir al Venhouri work for?", "Coldmere Mills"),
   ("Where does Samir al Venhouri work?", "Coldmere Mills"),
   ("Where does Rhys ap Gwenlor live?", "Tillmarsh"),
   ("What city does Rhys ap Gwenlor live in?", "Tillmarsh"),
   ("Where does Rhys ap Gwenlor work?", "")],
  [("samir al venhouri", E, "coldmere mills"), ("rhys ap gwenlor", C, "tillmarsh")]),
 ("v04", "O', d', Mac (split) and MacX",
  [("Niamh O'Tallory lives in Dunmere.", None),
   ("Pierre d'Arvenne speaks Norric.", None),
   ("Callum Mac Brennal was born in Harrowby.", None),
   ("Eilidh MacTavel works at Quillworks.", None),
   ("Where does Niamh O'Tallory live?", "Dunmere"),
   ("What language does Pierre d'Arvenne speak?", "Norric"),
   ("Where was Callum Mac Brennal born?", "Harrowby"),
   ("Where does Eilidh MacTavel work?", "Quillworks")],
  [("niamh o'tallory", C, "dunmere"), ("pierre d'arvenne", L, "norric"),
   ("callum mac brennal", B, "harrowby"), ("eilidh mactavel", E, "quillworks")]),
 ("v05", "hyphenated names",
  [("Anna-Lise Vorren-Tash works at Quillworks.", None),
   ("Jean-Marc de Villetard lives in Osterby.", None),
   ("Where does Anna-Lise Vorren-Tash work?", "Quillworks"),
   ("Where does Jean-Marc de Villetard live?", "Osterby"),
   ("Where does Jean-Marc de Villetard work?", "")],
  [("anna-lise vorren-tash", E, "quillworks"), ("jean-marc de villetard", C, "osterby")]),
 ("v06", "3- and 4-word names",
  [("Maria Elena Quistado lives in Farrowgate.", None),
   ("Pieter van den Holtzer speaks Veltish.", None),
   ("Ana Sofia da Corvel was born in Tillmarsh.", None),
   ("Where does Maria Elena Quistado live?", "Farrowgate"),
   ("What language does Pieter van den Holtzer speak?", "Veltish"),
   ("Where was Ana Sofia da Corvel born?", "Tillmarsh"),
   ("Where was Maria Elena Quistado born?", "")],
  [("maria elena quistado", C, "farrowgate"), ("pieter van den holtzer", L, "veltish"),
   ("ana sofia da corvel", B, "tillmarsh")]),
 ("v07", "von; all five verbs over two people; wordings",
  [("Emil von Tarrow lives in Quellmoor.", None),
   ("Emil von Tarrow was born in Harrowby.", None),
   ("Emil von Tarrow speaks Norric.", None),
   ("Greta von Tarrow works at Brindlecorp.", None),
   ("Where does Emil von Tarrow live?", "Quellmoor"),
   ("In which city was Emil von Tarrow born?", "Harrowby"),
   ("What does Emil von Tarrow speak?", "Norric"),
   ("Where does Greta von Tarrow work?", "Brindlecorp"),
   ("Where does Emil von Tarrow work?", ""),
   ("Where does Greta von Tarrow live?", "")],
  [("emil von tarrow", C, "quellmoor"), ("emil von tarrow", B, "harrowby"),
   ("emil von tarrow", L, "norric"), ("greta von tarrow", E, "brindlecorp")]),
 ("v08", "shared particle + surname",
  [("Liesl van Dorrick lives in Quellport.", None),
   ("Maarten van Dorrick lives in Tillmarsh.", None),
   ("Where does Liesl van Dorrick live?", "Quellport"),
   ("Where does Maarten van Dorrick live?", "Tillmarsh"),
   ("Where does Joost van Dorrick live?", "")],
  [("liesl van dorrick", C, "quellport"), ("maarten van dorrick", C, "tillmarsh")]),
 ("v09", "shared first name + particle, different surnames",
  [("Omar bin Rashel works at Brindlecorp.", None),
   ("Omar bin Kaddel works at Quillworks.", None),
   ("Where does Omar bin Rashel work?", "Brindlecorp"),
   ("Where does Omar bin Kaddel work?", "Quillworks"),
   ("Where does Omar bin Sallow work?", "")],
  [("omar bin rashel", E, "brindlecorp"), ("omar bin kaddel", E, "quillworks")]),
 ("v10", "one-word and multi-word sharing a first name",
  [("Tessa lives in Dunmere.", None),
   ("Tessa de la Morrow lives in Quellport.", None),
   ("Where does Tessa live?", "Dunmere"),
   ("Where does Tessa de la Morrow live?", "Quellport"),
   ("Brannoc speaks Norric.", None),
   ("What language does Brannoc speak?", "Norric")],
  [("tessa", C, "dunmere"), ("tessa de la morrow", C, "quellport"), ("brannoc", L, "norric")]),
 ("v11", "one-word only (reply parity)",
  [("Brannoc lives in Tillmarsh.", None),
   ("Brannoc works at Quillworks.", None),
   ("Brannoc speaks Norric.", None),
   ("Brannoc was born in Harrowby.", None),
   ("Where does Brannoc live?", "Tillmarsh"),
   ("Who does Brannoc work for?", "Quillworks"),
   ("What language does Brannoc speak?", "Norric"),
   ("Where was Brannoc born?", "Harrowby"),
   ("Where does Selwyn live?", "")],
  [("brannoc", C, "tillmarsh"), ("brannoc", E, "quillworks"), ("brannoc", L, "norric"),
   ("brannoc", B, "harrowby")]),
 ("v12", "correction on multi-word",
  [("Oskar van Heerlend lives in Delmoor.", None),
   ("No, Oskar van Heerlend lives in Quellport.", None),
   ("Where does Oskar van Heerlend live?", "Quellport")],
  [("oskar van heerlend", C, "delmoor"), ("oskar van heerlend", C, "quellport")]),
 ("v13", "retraction on multi-word",
  [("Ines da Varrow works at Brindlecorp.", None),
   ("That's not true, Ines da Varrow doesn't work at Brindlecorp.", None),
   ("Where does Ines da Varrow work?", "")],
  [("ines da varrow", E, "brindlecorp")]),
 ("v14", "forget on multi-word",
  [("Rafael de Sollan speaks Veltish.", None),
   ("Rafael de Sollan lives in Osterby.", None),
   ("Forget Rafael de Sollan's language.", None),
   ("What language does Rafael de Sollan speak?", ""),
   ("Where does Rafael de Sollan live?", "Osterby")],
  [("rafael de sollan", L, "veltish"), ("rafael de sollan", C, "osterby")]),
 ("v15", "TRAP compound subjects and/with/or",
  [("Anna van Dijkel and Piet live in Delmoor.", None),
   ("Marta de la Pell with Joris lives in Osterby.", None),
   ("Kees ter Hollum or Dina ter Hollum works at Quillworks.", None),
   ("Where does Anna van Dijkel live?", ""),
   ("Where does Piet live?", ""),
   ("Where does Marta de la Pell live?", ""),
   ("Where does Dina ter Hollum work?", "")],
  []),
 ("v16", "TRAP names longer than 4 words",
  [("Tomas de la Vega Ruizal Brandt lives in Farrowgate.", None),
   ("Juan Carlos de la Mondreva lives in Osterby.", None),
   ("Where does Tomas de la Vega Ruizal Brandt live?", ""),
   ("Where does Juan Carlos de la Mondreva live?", ""),
   ("Where does Mondreva live?", "")],
  []),
 ("v17", "TRAP names containing 'do'",
  [("Joao do Riomar lives in Quellport.", None),
   ("Ana do Carvel speaks Norric.", None),
   ("Where does Joao do Riomar live?", "Quellport"),
   ("What language does Ana do Carvel speak?", "Norric")],
  [("joao do riomar", C, "quellport"), ("ana do carvel", L, "norric")]),
 ("v18", "TRAP untaught verbs for a stored multi-word name",
  [("Hendrik van Lorrel lives in Tillmarsh.", None),
   ("Where does Hendrik van Lorrel work?", ""),
   ("What language does Hendrik van Lorrel speak?", ""),
   ("Where was Hendrik van Lorrel born?", ""),
   ("Who does Hendrik van Lorrel work for?", ""),
   ("Where does Hendrik van Lorrel live?", "Tillmarsh")],
  [("hendrik van lorrel", C, "tillmarsh")]),
 ("v19", "TRAP mixed: and-subject with shared particle, then legit teach",
  [("Sven al Harrow and Liv al Harrow speak Norric.", None),
   ("Liv al Harrow lives in Osterby.", None),
   ("What language does Liv al Harrow speak?", ""),
   ("What language does Sven al Harrow speak?", ""),
   ("Where does Liv al Harrow live?", "Osterby"),
   ("Where does Sven al Harrow live?", "")],
  [("liv al harrow", C, "osterby")]),
]
