#!/usr/bin/env python3
"""H5 (Director helper, 2026-09-28): code-made panel generator for the first joined test (reader -> learned reasoner ->
talker, chat messages). Spec: artifacts/claude-dir-h5-e2e-glue-20260928/PANEL-SPEC.md. Marks: artifacts/claude-dir-h4-e2e-20260928/
PASSMARKS.md (H4). Pure python 3, no torch, no numpy.

What this file does
  * makes every fact, name, puzzle, square layout, gold answer and label BY CODE (fictional names from syllables);
  * writes NO natural-language wording. Every sentence a user "says" is a WORDING SLOT, to be filled later by GPT-6 Luna
    or GLM from the exact prompt in LUNA-PROMPT-SPEC.md. Grids, tables and number lists are code-rendered blocks that
    the wording never touches;
  * for rehearsal (dev mode only) fills each slot with a code-made PLUMBING string ("[DEV-PLUMBING] fact owner=... rel=...").
    That is a key=value dump, not chat, and no Claude-written sentence. It is for wiring tests only.

Modes
  dev     seeds are the fixed DEV_SEEDS below. Plumbing text fills the slots. Safe to run and to read.
  sealed  seeds come from --seeds-file (JSON {"h1": int, "h2": int}); refuses the dev seeds; writes NO wording (only
          wording_jobs.jsonl and skeleton.json); truth goes to --truth-dir. THE SEALED PANEL IS GENERATED BY THE DIRECTOR,
          NOT BY H5; H5 never ran this mode.

Commands
  python -B scripts/claude_dir_h5_panel.py selftest
  python -B scripts/claude_dir_h5_panel.py make --mode dev --profile dev6 --out DIR         (6-life rehearsal sample)
  python -B scripts/claude_dir_h5_panel.py make --mode dev --profile dev60 --out DIR        (full-size structure, dev seeds, for scorer tests)
  python -B scripts/claude_dir_h5_panel.py make --mode sealed --seeds-file S.json --out DIR --truth-dir TDIR
  python -B scripts/claude_dir_h5_panel.py merge --skeleton DIR/skeleton.json --wording W.jsonl --out DIR --truth-dir TDIR
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import random
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = Path(__file__).resolve().parent
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

DEV_SEEDS = {"h1": 585101, "h2": 585102, "dev6": 585103}
AVOID_FILE = ROOT / "artifacts/claude-lis320-20260926/avoid_names_dev.txt"
REL_FILE = ROOT / "design/v3/60-listener/relation-names.txt"

# ------------------------------------------------------------------------------------------------ lexicons (single words, no sentences)
ONSET = ["b", "d", "f", "g", "k", "l", "m", "n", "p", "r", "s", "t", "v", "z", "br", "kl", "dr", "fl", "gr", "pr", "sk", "tr", "th", "sh", "ch"]
NUC = ["a", "e", "i", "o", "u", "ae", "ia", "ou"]
CODA = ["", "", "n", "r", "l", "m", "s", "th", "x"]
PLACE_SUFFIX = ["ford", "ton", "vale", "haven", "mere", "wick", "burn"]
ORG_SUFFIX = ["Works", "Group", "Supply", "Labs", "Trading"]
SCHOOL_SUFFIX = ["Academy", "College", "Institute"]
PERSON_RELS = ["sister", "brother", "cousin", "friend", "boss", "neighbour", "colleague", "teacher", "coach", "doctor", "mentor"]
PLACE_RELS = ["city", "hometown"]
ORG_RELS = ["employer"]
SCHOOL_RELS = ["school"]
NAMED_OWNER_RELS = ["employer", "city", "hometown", "school"]      # relations told about a named third person
TOPICS = ["weather", "weekend", "food", "music", "sleep", "commute", "hobby", "travel", "sports", "books", "coffee", "movies"]
NUM_ASKS = ["sum", "largest", "count_items"]
SQ_LOOK_ASKS = ["title", "count_blanks", "most_clues_row", "comment"]
PRONOUNS = ["she", "he", "they"]

# practice layouts (gr-1's names; rendered here by this file's own code) and held-out separators (gr-9's TEST marks +3 fresh)
SEEN_LAYOUTS = ["row", "bare", "pipe", "comma", "md", "latex", "label", "colhead"]
HELD_MARKS_FALLBACK = ["§", "$", "£", "%", "¶", "!", "!!", "'", '"', "`", "''", "¡", "‖", "⁂"]

PROFILES = {   # per 30-life half; dev6 = the rehearsal sample (6 lives)
    "half": {"lives": 30, "solve5": 10, "solve6": 10, "solve7": 5, "broken": 6, "sq_lookalike": 6, "num_lookalike": 10,
             "ask_plain": 15, "ask_corrected": None, "ask_backref": None, "ask_never": 15, "smalltalk": 20},
    "dev6": {"lives": 6, "solve5": 2, "solve6": 2, "solve7": 1, "broken": 1, "sq_lookalike": 1, "num_lookalike": 2,
             "ask_plain": 2, "ask_corrected": 2, "ask_backref": 2, "ask_never": 3, "smalltalk": 4},
}
ITEM_KEYS = ["solve5", "solve6", "solve7", "broken", "sq_lookalike", "num_lookalike",
             "ask_plain", "ask_corrected", "ask_backref", "ask_never", "smalltalk"]


def held_marks() -> tuple[list[str], str]:
    """gr-9's TEST separator marks (never trained on, never in its dev set) if that module imports, else the fallback list."""
    try:
        import claude_gr9 as G
        return list(G.split_seps()[2]) + ["¡", "‖", "⁂"], "claude_gr9.split_seps()[2] + 3 fresh"
    except Exception as e:  # pragma: no cover
        return HELD_MARKS_FALLBACK, "fallback list (%s)" % type(e).__name__


def read_rels() -> set[str]:
    return set(REL_FILE.read_text().split())


def avoid_names() -> set[str]:
    if AVOID_FILE.is_file():
        return {x.strip().lower() for x in AVOID_FILE.read_text().splitlines() if x.strip()}
    return set()


# ------------------------------------------------------------------------------------------------ fictional words
class Words:
    """Unique fictional names/places/orgs for one life. Names never equal an entry of the avoid list, a common word list
    (if the box has /usr/share/dict/words) or another word of the same life; first letters of persons differ."""

    def __init__(self, rng, avoid):
        self.rng, self.avoid, self.used, self.firsts = rng, set(avoid), set(), set()
        p = Path("/usr/share/dict/words")
        self.dict = {w.strip().lower() for w in p.read_text(errors="ignore").splitlines()} if p.is_file() else set()

    def _syl(self):
        r = self.rng
        return r.choice(ONSET) + r.choice(NUC) + r.choice(CODA)

    def _base(self):
        for _ in range(1000):
            w = self._syl() + self._syl() + (self._syl() if self.rng.random() < 0.3 else "")
            if 5 <= len(w) <= 9 and w.lower() not in self.avoid and w.lower() not in self.dict and w.lower() not in self.used \
                    and not any(w.lower() in u or u in w.lower() for u in self.used):
                return w
        raise RuntimeError("could not draw a fresh word")

    def person(self):
        for _ in range(200):
            w = self._base()
            if w[0].lower() not in self.firsts:
                self.firsts.add(w[0].lower())
                self.used.add(w.lower())
                return w.capitalize()
        raise RuntimeError("could not draw a person")

    def place(self):
        w = self._base() + self.rng.choice(PLACE_SUFFIX)
        self.used.add(w.lower())
        return w.capitalize()

    def org(self):
        w = self._base()
        self.used.add(w.lower())
        return w.capitalize() + " " + self.rng.choice(ORG_SUFFIX)

    def school(self):
        w = self._base()
        self.used.add(w.lower())
        return w.capitalize() + " " + self.rng.choice(SCHOOL_SUFFIX)

    def value_for(self, rel):
        if rel in PERSON_RELS:
            return self.person()
        if rel in PLACE_RELS:
            return self.place()
        if rel in ORG_RELS:
            return self.org()
        if rel in SCHOOL_RELS:
            return self.school()
        raise KeyError(rel)


# ------------------------------------------------------------------------------------------------ Latin squares
def random_latin(rng, s):
    grid = [[0] * s for _ in range(s)]
    rows = [set() for _ in range(s)]
    cols = [set() for _ in range(s)]

    def fill(k):
        if k == s * s:
            return True
        r, c = divmod(k, s)
        opts = [v for v in range(1, s + 1) if v not in rows[r] and v not in cols[c]]
        rng.shuffle(opts)
        for v in opts:
            grid[r][c] = v
            rows[r].add(v)
            cols[c].add(v)
            if fill(k + 1):
                return True
            rows[r].discard(v)
            cols[c].discard(v)
        grid[r][c] = 0
        return False
    assert fill(0)
    return grid


def count_solutions(puz, limit=2):
    s = len(puz)
    g = [row[:] for row in puz]
    for line in list(g) + [list(col) for col in zip(*g)]:
        cl = [v for v in line if v]
        if len(cl) != len(set(cl)):
            return 0                                   # a clue repeated in a row or column: no answer
    rows = [{v for v in row if v} for row in g]
    cols = [{g[r][c] for r in range(s) if g[r][c]} for c in range(s)]
    n = 0

    def go():
        nonlocal n
        best, bopts = None, None
        for r in range(s):
            for c in range(s):
                if g[r][c] == 0:
                    opts = [v for v in range(1, s + 1) if v not in rows[r] and v not in cols[c]]
                    if best is None or len(opts) < len(bopts):
                        best, bopts = (r, c), opts
                        if not opts:
                            return
        if best is None:
            n += 1
            return
        r, c = best
        for v in bopts:
            g[r][c] = v
            rows[r].add(v)
            cols[c].add(v)
            go()
            rows[r].discard(v)
            cols[c].discard(v)
            g[r][c] = 0
            if n >= limit:
                return
    go()
    return n


def make_puzzle(rng, s):
    """(solution, puzzle): values 1..s, 0 = blank; unique solution; every symbol visible at least once."""
    while True:
        sol = random_latin(rng, s)
        puz = [row[:] for row in sol]
        cells = [(r, c) for r in range(s) for c in range(s)]
        rng.shuffle(cells)
        budget = rng.uniform(0.35, 1.0) * s * s * 0.75
        removed = 0
        for r, c in cells:
            keep = puz[r][c]
            puz[r][c] = 0
            if count_solutions(puz) != 1:
                puz[r][c] = keep
            else:
                removed += 1
                if removed >= budget:
                    break
        if {v for row in puz for v in row if v} == set(range(1, s + 1)) and removed >= 3:
            return sol, puz


def break_puzzle(rng, puz):
    """copy a clue of a row into a blank of the same row: a clash, so no answer exists"""
    s = len(puz)
    order = list(range(s))
    rng.shuffle(order)
    for r in order:
        blanks = [c for c in range(s) if puz[r][c] == 0]
        clues = [c for c in range(s) if puz[r][c]]
        if blanks and clues:
            c = rng.choice(blanks)
            out = [row[:] for row in puz]
            out[r][c] = puz[r][rng.choice(clues)]
            return out, {"row": r + 1, "col": c + 1, "value": out[r][c]}
    raise RuntimeError("no row can be broken")


# ------------------------------------------------------------------------------------------------ code-rendered blocks
def _cell(v):
    return "_" if v == 0 else str(v)


def render_grid(grid, layout, rng):
    """text of a grid in one layout. layout = a SEEN_LAYOUTS name or 'sep:<mark>'. Returns (text, description)."""
    m = max(len(r) for r in grid)
    rows = [[_cell(v) for v in r] for r in grid]
    letters = "ABCDEFGHIJ"
    if layout.startswith("sep:"):
        mark = layout[4:]
        sep = rng.choice([" " + mark + " ", mark + " ", mark])
        return "\n".join(sep.join(r) for r in rows), layout
    if layout == "row":
        return "\n".join("Row %d: %s" % (i + 1, " ".join(r)) for i, r in enumerate(rows)), layout
    if layout == "bare":
        return "\n".join(" ".join(r) for r in rows), layout
    if layout == "pipe":
        return "\n".join("| " + " | ".join(r) + " |" for r in rows), layout
    if layout == "comma":
        return "\n".join(", ".join(r) for r in rows), layout
    if layout == "md":
        head = "| " + " | ".join(letters[:m]) + " |\n|" + "---|" * m + "\n"
        return head + "\n".join("| " + " | ".join(r) + " |" for r in rows), layout
    if layout == "latex":
        return "\\begin{array}{%s}\n%s\n\\end{array}" % ("c" * m, "\n".join(" & ".join(r) + " \\\\" for r in rows)), layout
    if layout == "label":
        pre = rng.choice(["{A}: ", "R{i}: ", "{i}) ", "row {i} - "])
        return "\n".join(pre.format(A=letters[i], i=i + 1) + " ".join(r) for i, r in enumerate(rows)), layout + ":" + pre
    if layout == "colhead":
        head = "    " + " ".join(str(i + 1) for i in range(m)) + "\n"
        return head + "\n".join("%d | %s" % (i + 1, " ".join(r)) for i, r in enumerate(rows)), layout
    raise KeyError(layout)


def make_numbers_block(rng, words, ask):
    """number lookalike: a table (rows != columns), a labelled list, or a comma sequence. Returns (text, facts_dict)."""
    kind = rng.choice(["table", "labelled", "sequence"])
    if kind == "table":
        r = rng.choice([3, 4, 5])
        c = rng.choice([x for x in (r - 1, r + 1, r + 2) if x >= 2])
        vals = [[rng.randint(1, 99) for _ in range(c)] for _ in range(r)]
        text, _ = render_grid(vals, rng.choice(["bare", "pipe", "comma", "md"]), rng)
        flat = [v for row in vals for v in row]
    elif kind == "labelled":
        n = rng.randint(4, 8)
        w = Words(rng, set())
        labs = []
        while len(labs) < n:
            x = w.person()
            if x not in labs:
                labs.append(x)
        vals = [rng.randint(1, 99) for _ in range(n)]
        text = "\n".join("%s: %d" % (a, b) for a, b in zip(labs, vals))
        flat = vals
    else:
        n = rng.randint(5, 9)
        flat = [rng.randint(1, 99) for _ in range(n)]
        text = ", ".join(map(str, flat))
    gold = {"sum": sum(flat), "largest": max(flat), "count_items": len(flat)}[ask]
    return text, {"block_kind": kind, "gold_number": gold}


# ------------------------------------------------------------------------------------------------ one life
class Life:
    """Builds the turn list of one life. A turn = {"kind", "slots": {slot_name: contract}, "block": code text or None, ...}
    and a truth row. NO sentence is written here."""

    def __init__(self, life_id, half, rng, avoid, rels):
        self.id, self.half, self.rng, self.rels = life_id, half, rng, rels
        self.w = Words(rng, avoid)
        self.used = set()                    # (owner, rel) already told
        self.persons = {}                    # name -> pronoun
        self.blocks = []                     # list of block = list of (turn, truth)

    def _t(self, kind, **kw):
        return dict(kind=kind, **kw)

    def _fact_turn(self, owner_ref, facts, mode="ASSERT", pronoun=None, note=None):
        t = self._t("fact", owner_ref=owner_ref, facts=facts, mode=mode, pronoun=pronoun,
                    slots={"text": {"must_include": [], "must_not_include": []}})
        # values and (if named) owner names must appear verbatim; pronoun turns must NOT show the owner's name
        for f in facts:
            t["slots"]["text"]["must_include"].append(f["value"])
            if owner_ref == "named" and f["owner"] != "USER":
                t["slots"]["text"]["must_include"].append(f["owner"])
            if owner_ref == "pronoun":
                t["slots"]["text"]["must_not_include"].append(f["owner"])
            if mode == "CORRECT" and f.get("old"):
                t["slots"]["text"]["must_not_include"].append(f["old"])
        return t

    def _pick_rel(self, owner, pool):
        opts = [r for r in pool if (owner, r) not in self.used and r in self.rels]
        assert opts, (owner, pool)
        r = self.rng.choice(opts)
        return r

    def _ask_turn(self, owner, rel, gold, old=None):
        must_not = list(gold) + ([old] if old else [])
        must = [owner] if owner != "USER" else []
        return self._t("ask", owner=owner, rel=rel,
                       slots={"text": {"must_include": must, "must_not_include": must_not}})

    def answerable(self, item):
        rng = self.rng
        if item == "ask_plain":
            if rng.random() < 0.5:
                rel = self._pick_rel("USER", PERSON_RELS + PLACE_RELS + ORG_RELS)
                v = self.w.value_for(rel)
                self.used.add(("USER", rel))
                ft = self._fact_turn("me", [{"owner": "USER", "rel": rel, "value": v, "mode": "ASSERT"}])
                ask = self._ask_turn("USER", rel, [v])
                sub = "me"
            else:
                o = self.w.person()
                self.persons[o] = rng.choice(PRONOUNS)
                rel = self._pick_rel(o, NAMED_OWNER_RELS)
                v = self.w.value_for(rel)
                self.used.add((o, rel))
                ft = self._fact_turn("named", [{"owner": o, "rel": rel, "value": v, "mode": "ASSERT"}])
                ask = self._ask_turn(o, rel, [v])
                sub = "named"
            return [(ft, None), (ask, dict(item=item, owner=ft["facts"][0]["owner"], rel=rel, gold=[v], sub=sub))]
        if item == "ask_corrected":
            named = rng.random() < 0.5
            owner = self.w.person() if named else "USER"
            if named:
                self.persons[owner] = rng.choice(PRONOUNS)
            rel = self._pick_rel(owner, NAMED_OWNER_RELS if named else PERSON_RELS + PLACE_RELS + ORG_RELS)
            v1 = self.w.value_for(rel)
            v2 = self.w.value_for(rel)
            self.used.add((owner, rel))
            ref = "named" if named else "me"
            f1 = self._fact_turn(ref, [{"owner": owner, "rel": rel, "value": v1, "mode": "ASSERT"}])
            f2 = self._fact_turn(ref, [{"owner": owner, "rel": rel, "value": v2, "mode": "CORRECT", "old": v1}], mode="CORRECT")
            ask = self._ask_turn(owner, rel, [v2], old=v1)
            return [(f1, None), (f2, None), (ask, dict(item=item, owner=owner, rel=rel, gold=[v2], old=[v1], sub=ref))]
        if item == "ask_backref":
            name = self.w.person()
            pron = rng.choice(PRONOUNS)
            self.persons[name] = pron
            prel = self._pick_rel("USER", PERSON_RELS)
            self.used.add(("USER", prel))
            intro = self._fact_turn("named", [{"owner": "USER", "rel": prel, "value": name, "mode": "ASSERT"}], pronoun=pron)
            intro["slots"]["text"]["must_include"] = [name]
            rel = self._pick_rel(name, NAMED_OWNER_RELS)
            v = self.w.value_for(rel)
            self.used.add((name, rel))
            ft = self._fact_turn("pronoun", [{"owner": name, "rel": rel, "value": v, "mode": "ASSERT"}], pronoun=pron)
            ask = self._ask_turn(name, rel, [v])
            return [(intro, None), (ft, None), (ask, dict(item=item, owner=name, rel=rel, gold=[v], sub="pronoun", pronoun=pron))]
        if item == "ask_never":
            if rng.random() < 0.5:
                rel = self._pick_rel("USER", PERSON_RELS + PLACE_RELS + ORG_RELS)
                self.used.add(("USER", rel))                  # nobody may tell it later in this life
                ask = self._ask_turn("USER", rel, [])
                return [(ask, dict(item=item, owner="USER", rel=rel, gold=[], sub="me"))]
            name = self.w.person()
            pron = rng.choice(PRONOUNS)
            self.persons[name] = pron
            prel = self._pick_rel("USER", PERSON_RELS)
            self.used.add(("USER", prel))
            intro = self._fact_turn("named", [{"owner": "USER", "rel": prel, "value": name, "mode": "ASSERT"}], pronoun=pron)
            intro["slots"]["text"]["must_include"] = [name]
            rel = self._pick_rel(name, NAMED_OWNER_RELS)
            self.used.add((name, rel))
            ask = self._ask_turn(name, rel, [])
            return [(intro, None), (ask, dict(item=item, owner=name, rel=rel, gold=[], sub="named"))]
        raise KeyError(item)

    def square(self, item, layout):
        rng = self.rng
        s = {"solve5": 5, "solve6": 6, "solve7": 7}.get(item, rng.choice([5, 6]))
        sol, puz = make_puzzle(rng, s)
        truth = dict(item=item, size=s, layout=layout, puzzle=puz)
        if item == "broken":
            puz, clash = break_puzzle(rng, puz)
            truth.update(puzzle=puz, clash=clash, solution=None)
        else:
            truth["solution"] = sol
        if item == "sq_lookalike":
            ak = rng.choice(SQ_LOOK_ASKS)
            truth["ask_kind"] = ak
            truth["gold_blanks"] = sum(v == 0 for r in puz for v in r)
            truth["gold_row_most_clues"] = 1 + max(range(s), key=lambda r: (sum(v != 0 for v in puz[r]), -r))
            ask_kind = ak
        else:
            ask_kind = "solve"
        text, desc = render_grid(puz, layout, rng)
        t = self._t("square", item=item, size=s, block=text, block_layout=desc, ask_kind=ask_kind, order=rng.choice(["lead-block-ask", "ask-block"]),
                    slots={"lead": {"optional": True}, "ask": {}})
        return [(t, truth)]

    def numbers(self):
        ask = self.rng.choice(NUM_ASKS)
        text, info = make_numbers_block(self.rng, self.w, ask)
        t = self._t("numbers", item="num_lookalike", block=text, ask_kind=ask, order=self.rng.choice(["lead-block-ask", "ask-block"]),
                    slots={"lead": {"optional": True}, "ask": {}})
        return [(t, dict(item="num_lookalike", ask_kind=ask, **info))]

    def smalltalk(self):
        topic = self.rng.choice(TOPICS)
        t = self._t("smalltalk", topic=topic, slots={"text": {"must_include": [], "must_not_include": []}})
        return [(t, dict(item="smalltalk", topic=topic))]


# ------------------------------------------------------------------------------------------------ a half / a panel
def split_corrected(total_pairs, half_no):
    """15 corrected + 15 backref over 2 halves: 8/7 and 7/8"""
    return (8, 7) if half_no == 1 else (7, 8)


def make_half(half_no, seed, profile_name, held, prefix):
    P = dict(PROFILES["half" if profile_name in ("half", "dev60") else profile_name])
    if profile_name in ("half", "dev60"):
        P["ask_corrected"], P["ask_backref"] = split_corrected(15, half_no)
    rng = random.Random(seed)
    avoid = avoid_names()
    rels = read_rels()
    for r in PERSON_RELS + PLACE_RELS + ORG_RELS + SCHOOL_RELS:
        assert r in rels, r
    n = P["lives"]
    lives = [Life("%s-l%02d" % (prefix, i + 1), half_no, random.Random(rng.random()), avoid, rels) for i in range(n)]
    # every life gets exactly one answerable ask; the rest of the items are dealt round-robin from a shuffled list
    answ = ["ask_plain"] * P["ask_plain"] + ["ask_corrected"] * P["ask_corrected"] + ["ask_backref"] * P["ask_backref"]
    assert len(answ) == n, (len(answ), n)
    rng.shuffle(answ)
    others = []
    for k in ["solve5", "solve6", "solve7", "broken", "sq_lookalike", "num_lookalike", "ask_never", "smalltalk"]:
        others += [k] * P[k]
    rng.shuffle(others)
    # layouts: alternate seen / held-out over all square-type items, shuffled
    n_sq = sum(P[k] for k in ["solve5", "solve6", "solve7", "broken", "sq_lookalike"])
    lay = ["seen"] * (n_sq // 2) + ["held"] * (n_sq - n_sq // 2)
    rng.shuffle(lay)
    layout_iter = iter(lay)
    per_life = [[] for _ in range(n)]
    start = rng.randrange(n)
    for i, k in enumerate(others):
        per_life[(start + i) % n].append(k)
    out_lives = []
    for i, L in enumerate(lives):
        seq = L.answerable(answ[i])
        for k in per_life[i]:
            if k in ("solve5", "solve6", "solve7", "broken", "sq_lookalike"):
                cls = next(layout_iter)
                layout = rng.choice(SEEN_LAYOUTS) if cls == "seen" else "sep:" + rng.choice(held)
                block = L.square(k, layout)
                block[0][1]["layout_class"] = cls
            elif k == "num_lookalike":
                block = L.numbers()
            elif k == "ask_never":
                block = L.answerable("ask_never")
            else:
                block = L.smalltalk()
            gap = rng.randrange(len(seq) + 1)
            seq[gap:gap] = block
        out_lives.append((L, seq))
    return out_lives


def item_of_turn(t, truth):
    if truth:
        return truth["item"]
    return {"fact": "fact", "ask": "ask"}.get(t["kind"], t["kind"])


# ------------------------------------------------------------------------------------------------ wording (dev plumbing only) and assembly
DEV_TAG = "[DEV-PLUMBING] "


def dev_slot_text(t, slot, contract):
    """code-made key=value dump for rehearsal wiring. NOT chat wording; not a Claude-written sentence."""
    if t["kind"] == "fact":
        f = t["facts"][0]
        who = "me" if t["owner_ref"] == "me" else (f["owner"] if t["owner_ref"] != "pronoun" else t["pronoun"])
        extra = ""
        if t.get("mode") == "CORRECT":
            extra = " mode=CORRECT"
        return DEV_TAG + "fact owner=%s rel=%s value=%s%s" % (who, f["rel"], f["value"], extra) if not (t["owner_ref"] == "named" and f["owner"] == "USER") \
            else DEV_TAG + "fact owner=me rel=%s value=%s pronoun=%s" % (f["rel"], f["value"], t.get("pronoun") or "")
    if t["kind"] == "ask":
        return DEV_TAG + "ask owner=%s rel=%s" % ("me" if t["owner"] == "USER" else t["owner"], t["rel"])
    if t["kind"] == "smalltalk":
        return DEV_TAG + "smalltalk topic=" + t["topic"]
    if t["kind"] in ("square", "numbers"):
        return "" if slot == "lead" else DEV_TAG + "ask kind=" + t["ask_kind"]
    raise KeyError(t["kind"])


def assemble(t, slot_texts):
    """the final chat message for one turn: Luna/dev text for each slot, code blocks untouched"""
    if t["kind"] in ("square", "numbers"):
        lead, ask = slot_texts.get("lead", "").strip(), slot_texts["ask"].strip()
        block = t["block"]
        if t["order"] == "ask-block":
            return (ask + "\n" + block).strip("\n")
        return "\n".join(x for x in (lead, block, ask) if x)
    return slot_texts["text"].strip()


def build_panel(half_specs, mode):
    """half_specs: list of (half_no, seed, profile, prefix). Returns skeleton (no truth), truth rows, lives as dicts."""
    held, held_src = held_marks()
    skeleton, truth_rows, jobs = [], [], []
    for half_no, seed, profile, prefix in half_specs:
        for L, seq in make_half(half_no, seed, profile, held, prefix):
            turns = []
            life_words = sorted({x for x in L.w.used})
            for k, (t, truth) in enumerate(seq):
                tid = "%s-t%02d" % (L.id, k + 1)
                t = dict(t, id=tid, life_id=L.id, half=half_no, turn_no=k + 1)
                turns.append(t)
                row = dict(id=tid, life_id=L.id, half=half_no, turn_no=k + 1, kind=t["kind"])
                if truth:
                    row.update(truth)
                else:
                    row["item"] = item_of_turn(t, None)
                    if t["kind"] == "fact":
                        row["facts"] = t["facts"]
                truth_rows.append(row)
            skeleton.append(dict(life_id=L.id, half=half_no, turns=turns))
            jobs.append(dict(life_id=L.id, half=half_no, avoid_strings=[w for w in life_words],
                             slots=[dict(slot_id=t["id"] + "." + s, turn_id=t["id"], turn_no=t["turn_no"], kind=t["kind"], slot=s,
                                         contract=dict(c, **{k: v for k, v in t.items()
                                                             if k in ("owner_ref", "pronoun", "mode", "topic", "ask_kind", "size", "order", "owner", "rel")},
                                                       facts=[{"owner": f["owner"], "rel": f["rel"], "value": f["value"]} for f in t.get("facts", [])] or None))
                                    for t in turns for s, c in t["slots"].items()]))
    return skeleton, truth_rows, jobs, dict(held_marks_source=held_src, held_marks=held)


def count_items(truth_rows):
    c = Counter(r["item"] for r in truth_rows)
    return {k: c.get(k, 0) for k in ITEM_KEYS + ["fact"]}


def sha256_of(p: Path) -> str:
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def write_jsonl(p: Path, rows):
    p.write_text("".join(json.dumps(r, ensure_ascii=False) + "\n" for r in rows), encoding="utf-8")


def write_turns(out: Path, skeleton, wording):
    """wording: {slot_id: text}. Returns the turn rows written (no truth in them)."""
    rows = []
    for life in skeleton:
        for t in life["turns"]:
            texts = {s: wording[t["id"] + "." + s] for s in t["slots"] if (t["id"] + "." + s) in wording}
            for s, c in t["slots"].items():
                if s not in texts:
                    if c.get("optional"):
                        texts[s] = ""
                    else:
                        raise SystemExit("missing wording for " + t["id"] + "." + s)
            rows.append(dict(id=t["id"], life_id=t["life_id"], half=t["half"], turn_no=t["turn_no"], text=assemble(t, texts)))
    write_jsonl(out / "turns.jsonl", rows)
    return rows


def cmd_make(a):
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    if a.mode == "dev":
        if a.profile == "dev6":
            specs = [(1, DEV_SEEDS["dev6"], "dev6", "d6")]
        elif a.profile == "dev60":
            specs = [(1, DEV_SEEDS["h1"], "half", "h1"), (2, DEV_SEEDS["h2"], "half", "h2")]
        else:
            raise SystemExit("dev mode profiles: dev6, dev60")
    else:
        if not a.seeds_file or not a.truth_dir:
            raise SystemExit("sealed mode needs --seeds-file and --truth-dir")
        s = json.loads(Path(a.seeds_file).read_text())
        if s["h1"] in DEV_SEEDS.values() or s["h2"] in DEV_SEEDS.values() or s["h1"] == s["h2"]:
            raise SystemExit("sealed seeds must be fresh, distinct and not the dev seeds")
        specs = [(1, s["h1"], "half", "h1"), (2, s["h2"], "half", "h2")]
    skeleton, truth_rows, jobs, meta = build_panel(specs, a.mode)
    (out / "skeleton.json").write_text(json.dumps(skeleton, ensure_ascii=False), encoding="utf-8")
    write_jsonl(out / "wording_jobs.jsonl", jobs)
    tdir = Path(a.truth_dir) if a.truth_dir else out
    tdir.mkdir(parents=True, exist_ok=True)
    write_jsonl(tdir / "answers.jsonl", truth_rows)
    if a.mode == "sealed":
        os.chmod(tdir / "answers.jsonl", 0o600)
        # skeleton.json holds the truth-bearing fields (facts, block) too; the Director keeps it with the truth
        os.chmod(out / "skeleton.json", 0o600)
    if a.mode == "dev":
        wording = {}
        for life in skeleton:
            for t in life["turns"]:
                for sl, c in t["slots"].items():
                    wording[t["id"] + "." + sl] = dev_slot_text(t, sl, c)
        write_turns(out, skeleton, wording)
    counts = count_items(truth_rows)
    lay = Counter(r.get("layout_class") for r in truth_rows if r.get("layout_class"))
    info = dict(mode=a.mode, profile=a.profile, lives=len(skeleton), turns=len(truth_rows), counts=counts, layout_class=dict(lay),
                text_source="DEV plumbing (code key=value dump)" if a.mode == "dev" else "EMPTY: wording slots await Luna/GLM",
                **meta)
    (out / "panel_counts.json").write_text(json.dumps(info, indent=1, ensure_ascii=False), encoding="utf-8")
    files = ["wording_jobs.jsonl", "panel_counts.json"] + (["turns.jsonl"] if a.mode == "dev" else [])
    (out / "SHA256.txt").write_text("".join("%s  %s\n" % (sha256_of(out / f), f) for f in files)
                                    + "%s  answers.jsonl\n" % sha256_of(tdir / "answers.jsonl"), encoding="utf-8")
    print(json.dumps(info, ensure_ascii=False))


# ------------------------------------------------------------------------------------------------ wording validation (used by merge)
DIGIT = re.compile(r"\d")


def wb(text, needle):
    return re.search(r"(?<![A-Za-z0-9])" + re.escape(needle) + r"(?![A-Za-z0-9])", text, re.I) is not None


def validate_wording(jobs, wording):
    """code checks on Luna/GLM output. Returns a list of problems (empty = fine)."""
    bad = []
    seen = set()
    for job in jobs:
        for s in job["slots"]:
            sid, c = s["slot_id"], s["contract"]
            seen.add(sid)
            txt = wording.get(sid)
            if txt is None:
                if not c.get("optional"):
                    bad.append((sid, "missing"))
                continue
            if not isinstance(txt, str):
                bad.append((sid, "not a string"))
                continue
            if txt == "" and not c.get("optional"):
                bad.append((sid, "empty"))
            if "\n" in txt or "\r" in txt:
                bad.append((sid, "newline in slot text (blocks are code-made)"))
            if DIGIT.search(txt):
                bad.append((sid, "digit in wording"))
            if len(txt) > 400:
                bad.append((sid, "longer than 400 characters"))
            for m in c.get("must_include") or []:
                if not wb(txt, m):
                    bad.append((sid, "missing required string " + m))
            for m in c.get("must_not_include") or []:
                if wb(txt, m):
                    bad.append((sid, "contains forbidden string " + m))
            allowed = {w.lower() for m in (c.get("must_include") or []) for w in re.findall(r"[A-Za-z0-9]+", m)}
            for w in job["avoid_strings"]:
                if w not in allowed and wb(txt, w):
                    bad.append((sid, "uses a life word it may not: " + w))
    extra = set(wording) - seen
    bad += [(x, "unknown slot") for x in sorted(extra)]
    return bad


def cmd_merge(a):
    out = Path(a.out)
    skeleton = json.loads(Path(a.skeleton).read_text())
    jobs = [json.loads(x) for x in (Path(a.skeleton).parent / "wording_jobs.jsonl").read_text().splitlines() if x.strip()]
    wording = {}
    for line in Path(a.wording).read_text().splitlines():
        if line.strip():
            r = json.loads(line)
            wording.update(r["slots"])
    bad = validate_wording(jobs, wording)
    if bad:
        Path(out / "wording_problems.json").write_text(json.dumps(bad, indent=1))
        raise SystemExit("wording rejected: %d problems, see wording_problems.json (first: %s)" % (len(bad), bad[0]))
    rows = write_turns(out, skeleton, wording)
    print("wrote turns.jsonl rows=%d sha256=%s" % (len(rows), sha256_of(out / "turns.jsonl")))


# ------------------------------------------------------------------------------------------------ selftest
def selftest():
    import tempfile
    ok = {}
    rng = random.Random(1)
    for s in (5, 6, 7):
        sol, puz = make_puzzle(rng, s)
        ok["unique %d" % s] = count_solutions(puz) == 1 and all(set(r) == set(range(1, s + 1)) for r in sol)
        bp, cl = break_puzzle(rng, puz)
        ok["broken has no solution %d" % s] = count_solutions(bp) == 0
    with tempfile.TemporaryDirectory() as d:
        d = Path(d)
        ns = argparse.Namespace(mode="dev", profile="dev60", out=str(d / "p"), truth_dir=None, seeds_file=None)
        cmd_make(ns)
        info = json.loads((d / "p/panel_counts.json").read_text())
        c = info["counts"]
        want = {"solve5": 20, "solve6": 20, "solve7": 10, "broken": 12, "sq_lookalike": 12, "num_lookalike": 20, "ask_plain": 30,
                "ask_corrected": 15, "ask_backref": 15, "ask_never": 30, "smalltalk": 40}
        ok["full-size counts equal H4's table"] = all(c[k] == v for k, v in want.items())
        ok["60 lives"] = info["lives"] == 60
        ans = [json.loads(x) for x in (d / "p/answers.jsonl").read_text().splitlines()]
        turns = [json.loads(x) for x in (d / "p/turns.jsonl").read_text().splitlines()]
        ok["turns carry no truth field"] = all(set(t) == {"id", "life_id", "half", "turn_no", "text"} for t in turns)
        ok["turn ids match truth ids"] = [t["id"] for t in turns] == [r["id"] for r in ans]
        # each half has half of each item (corrected/backref may differ by 1)
        for k, v in want.items():
            h1 = sum(1 for r in ans if r["item"] == k and r["half"] == 1)
            h2 = sum(1 for r in ans if r["item"] == k and r["half"] == 2)
            ok["halves balanced " + k] = abs(h1 - h2) <= 2
        sq = [r for r in ans if r["item"] in ("solve5", "solve6", "solve7", "broken", "sq_lookalike")]
        ok["half the squares use held-out layouts"] = abs(sum(r["layout_class"] == "held" for r in sq) - len(sq) / 2) <= 1
        # facts come before the ask that needs them; asks never leak gold
        pos = {r["id"]: i for i, r in enumerate(ans)}
        good = True
        for r in ans:
            if r["item"].startswith("ask_") and r["item"] != "ask_never":
                tx = next(t["text"] for t in turns if t["id"] == r["id"])
                good &= all(g not in tx for g in r["gold"])
        ok["dev asks do not contain the gold value"] = good
        told = {}
        for r in ans:
            if r["kind"] == "fact":
                for f in r["facts"]:
                    told.setdefault(r["life_id"], set()).add((f["owner"], f["rel"]))
        nt = [r for r in ans if r["item"] == "ask_never"]
        ok["never-told asks: relation told nowhere for that owner"] = all((r["owner"], r["rel"]) not in told.get(r["life_id"], set()) for r in nt)
        ok["squares: one square per message, grid lines exactly s cells"] = True
        for t, r in ((next(t for t in turns if t["id"] == r["id"]), r) for r in sq):
            import claude_puzzle_reader as P
            if r["layout"] in ("row", "bare", "comma", "pipe"):
                g = P.read_latin(t["text"])
                ok["squares: one square per message, grid lines exactly s cells"] &= (g is not None and g["grid"] == r["puzzle"])
        # names: fictional, none on the avoid list
        av = avoid_names()
        names = set()
        for r in ans:
            if r["kind"] == "fact":
                for f in r["facts"]:
                    names.add(f["value"].split()[0].lower())
        ok["no name on the avoid list"] = not (names & av)
        # dev6 sample
        ns6 = argparse.Namespace(mode="dev", profile="dev6", out=str(d / "s"), truth_dir=None, seeds_file=None)
        cmd_make(ns6)
        i6 = json.loads((d / "s/panel_counts.json").read_text())
        ok["dev6 has 6 lives"] = i6["lives"] == 6
        ok["deterministic"] = True
        cmd_make(argparse.Namespace(mode="dev", profile="dev6", out=str(d / "s2"), truth_dir=None, seeds_file=None))
        ok["deterministic"] = (d / "s/turns.jsonl").read_bytes() == (d / "s2/turns.jsonl").read_bytes()
        # sealed mode refuses dev seeds
        sf = d / "seeds.json"
        sf.write_text(json.dumps({"h1": DEV_SEEDS["h1"], "h2": 5}))
        try:
            cmd_make(argparse.Namespace(mode="sealed", profile="half", out=str(d / "x"), truth_dir=str(d / "t"), seeds_file=str(sf)))
            ok["sealed refuses dev seeds"] = False
        except SystemExit:
            ok["sealed refuses dev seeds"] = True
        # wording validator
        jobs = [json.loads(x) for x in (d / "s/wording_jobs.jsonl").read_text().splitlines()]
        slot = next(s for j in jobs for s in j["slots"] if s["kind"] == "ask")
        good_w = {s["slot_id"]: "x" for j in jobs for s in j["slots"]}
        problems = validate_wording(jobs, {slot["slot_id"]: "has 3 digits"})
        smalltalk = next(s for j in jobs for s in j["slots"] if s["kind"] == "smalltalk")
        life_word = next(j["avoid_strings"][0] for j in jobs if any(s2["slot_id"] == smalltalk["slot_id"] for s2 in j["slots"]))
        pw = validate_wording(jobs, {smalltalk["slot_id"]: "talking about " + life_word + " again"})
        ok["validator flags a life word in small talk"] = any("life word" in p[1] for p in pw)
        ok["validator flags digits and missing slots"] = any("digit" in p[1] for p in problems) and any(p[1] == "missing" for p in problems)
    for k, v in ok.items():
        print(("PASS " if v else "FAIL ") + k)
    print("selftest: %d of %d checks pass" % (sum(ok.values()), len(ok)))
    if not all(ok.values()):
        raise SystemExit(1)


def main():
    ap = argparse.ArgumentParser()
    sp = ap.add_subparsers(dest="cmd", required=True)
    sp.add_parser("selftest")
    m = sp.add_parser("make")
    m.add_argument("--mode", choices=["dev", "sealed"], required=True)
    m.add_argument("--profile", default="dev6")
    m.add_argument("--out", required=True)
    m.add_argument("--truth-dir", default=None)
    m.add_argument("--seeds-file", default=None)
    g = sp.add_parser("merge")
    g.add_argument("--skeleton", required=True)
    g.add_argument("--wording", required=True)
    g.add_argument("--out", required=True)
    a = ap.parse_args()
    if a.cmd == "selftest":
        selftest()
    elif a.cmd == "make":
        cmd_make(a)
    else:
        cmd_merge(a)


if __name__ == "__main__":
    main()
