#!/usr/bin/env python3
"""Exp 252 dev cases (own wordings, fictional names; never copied from any
panel). Writes artifacts/claude-correct252-20260922/dev252.jsonl in the
corrpanel252 item shape (+ dev-only "restart" and "extra").

extra = [[question, must_not_contain, must_contain], ...] asked after the
followup (reverse lookups; the question itself names the value, so the
check is on the removed SUBJECT, whole word)."""
from __future__ import annotations

import json
import sys
from pathlib import Path

OUT = Path("artifacts/claude-correct252-20260922/dev252.jsonl")
E, CI, L, PB = "employer", "city", "language", "place_of_birth"


def it(fam, setup, turn, follow, stated, gone, store, gold, note,
       **kw):
    d = {"family": fam, "setup": setup, "turn": turn, "followup": follow,
         "stated_facts": stated, "expect_gone": gone,
         "expect_store": store, "gold_followup": gold, "note": note}
    d.update(kw)
    return d


I = []
# ---------------------------------------------------------------- verb_denial
I += [
    it("verb_denial", ["Orla works at Venncastle."],
       "Orla doesn't work at Venncastle.", "Where does Orla work?",
       [["Orla", E, "Venncastle"]], [["Orla", E, "Venncastle"]], [], None,
       "doesn't work at",
       extra=[["Whose employer is Venncastle?", ["Orla"], []]]),
    it("verb_denial", ["Brann lives in Tessary."],
       "Brann doesn't live in Tessary anymore.", "Where does Brann live?",
       [["Brann", CI, "Tessary"]], [["Brann", CI, "Tessary"]], [], None,
       "doesn't ... anymore"),
    it("verb_denial", ["Kesta speaks Wendish.", "Kesta speaks Arvic."],
       "Kesta does not speak Arvic.", "What language does Kesta speak?",
       [["Kesta", L, "Wendish"], ["Kesta", L, "Arvic"]],
       [["Kesta", L, "Arvic"]], [["Kesta", L, "Wendish"]], "Wendish",
       "does not speak, one of two values"),
    it("verb_denial", ["Dallo works for Pemberwick."],
       "dallo no longer works for pemberwick.", "Where does Dallo work?",
       [["Dallo", E, "Pemberwick"]], [["Dallo", E, "Pemberwick"]], [], None,
       "lowercase no longer"),
    it("verb_denial", ["Yselle was born in Carrowmere."],
       "Yselle wasn't born in Carrowmere.", "Where was Yselle born?",
       [["Yselle", PB, "Carrowmere"]], [["Yselle", PB, "Carrowmere"]], [],
       None, "wasn't born in"),
    it("verb_denial", ["Fenwick lives in Oldmarsh.",
                       "Fenwick works at Thornlake."],
       "Actually Fenwick doesn't live in Oldmarsh.",
       "Where does Fenwick live?",
       [["Fenwick", CI, "Oldmarsh"], ["Fenwick", E, "Thornlake"]],
       [["Fenwick", CI, "Oldmarsh"]], [["Fenwick", E, "Thornlake"]], None,
       "prefix actually, other fact kept"),
    it("verb_denial", ["Marro works at Quenby."],
       "Not true, Marro doesn't work at Quenby.",
       "Where does Marro work?",
       [["Marro", E, "Quenby"]], [["Marro", E, "Quenby"]], [], None,
       "not true prefix",
       extra=[["Who works at Quenby?", ["Marro"], []]]),
    it("verb_denial", ["Tavi speaks Olvish."],
       "tavi doesn't speak olvish", "What language does Tavi speak?",
       [["Tavi", L, "Olvish"]], [["Tavi", L, "Olvish"]], [], None,
       "lowercase, no period"),
    it("verb_denial", ["Ruen lives in Hallowdeep."],
       "Wrong, Ruen does not live in Hallowdeep.", "Where does Ruen live?",
       [["Ruen", CI, "Hallowdeep"]], [["Ruen", CI, "Hallowdeep"]], [], None,
       "wrong prefix"),
    it("verb_denial", ["Corvin works at Ashgrove.", "Pell works at Ashgrove."],
       "Corvin doesn't work at Ashgrove.", "Where does Corvin work?",
       [["Corvin", E, "Ashgrove"], ["Pell", E, "Ashgrove"]],
       [["Corvin", E, "Ashgrove"]], [["Pell", E, "Ashgrove"]], None,
       "reverse lookup keeps the other person",
       extra=[["Whose employer is Ashgrove?", ["Corvin"], ["Pell"]]]),
]
# ---------------------------------------------------------- possessive_denial
I += [
    it("possessive_denial", ["Nilo's boss is Harth."],
       "Harth isn't Nilo's boss.", "Who is Nilo's boss?",
       [["Nilo", "boss", "Harth"]], [["Nilo", "boss", "Harth"]], [], None,
       "Y isn't X's R",
       extra=[["Whose boss is Harth?", ["Nilo"], []]]),
    it("possessive_denial", ["Wren's sister is Ottilie."],
       "Ottilie is not Wren's sister.", "Who is Wren's sister?",
       [["Wren", "sister", "Ottilie"]], [["Wren", "sister", "Ottilie"]], [],
       None, "Y is not X's R"),
    it("possessive_denial", ["Gaspar's city is Lindmoor."],
       "That's not true, Gaspar's city is not Lindmoor.",
       "Where does Gaspar live?",
       [["Gaspar", CI, "Lindmoor"]], [["Gaspar", CI, "Lindmoor"]], [], None,
       "prefixed X's R is not Y"),
    it("possessive_denial", ["Sabin's manager is Druce."],
       "sabin's manager isn't druce", "Who is Sabin's manager?",
       [["Sabin", "manager", "Druce"]], [["Sabin", "manager", "Druce"]], [],
       None, "lowercase X's R isn't Y"),
    it("possessive_denial", ["Ivo's teacher is Marlet."],
       "Marlet was never Ivo's teacher.", "Who is Ivo's teacher?",
       [["Ivo", "teacher", "Marlet"]], [["Ivo", "teacher", "Marlet"]], [],
       None, "was never"),
    it("possessive_denial", ["Pim's cousin is Adra."],
       "No, Adra is not Pim's cousin.", "Who is Pim's cousin?",
       [["Pim", "cousin", "Adra"]], [["Pim", "cousin", "Adra"]], [], None,
       "no prefix + Y is not X's R"),
]
# ---------------------------------------------------------- contextual_denial
I += [
    it("contextual_denial", ["Hollis works at Brackenridge.",
                             "Where does Hollis work?"],
       "That's not right.", "Where does Hollis work?",
       [["Hollis", E, "Brackenridge"]], [["Hollis", E, "Brackenridge"]], [],
       None, "that's not right"),
    it("contextual_denial", ["Emmet lives in Coldharbour.",
                             "Where does Emmet live?"],
       "wrong", "Where does Emmet live?",
       [["Emmet", CI, "Coldharbour"]], [["Emmet", CI, "Coldharbour"]], [],
       None, "bare lowercase wrong"),
    it("contextual_denial", ["Jora's boss is Keeble.", "Who is Jora's boss?"],
       "No, that's incorrect.", "Who is Jora's boss?",
       [["Jora", "boss", "Keeble"]], [["Jora", "boss", "Keeble"]], [], None,
       "no, that's incorrect"),
    it("contextual_denial", ["Lune speaks Harric.",
                             "What language does Lune speak?"],
       "You've got that wrong.", "What language does Lune speak?",
       [["Lune", L, "Harric"]], [["Lune", L, "Harric"]], [], None,
       "you've got that wrong"),
    it("contextual_denial", ["Tamsin was born in Greywater.",
                             "Where was Tamsin born?"],
       "nope, that's false", "Where was Tamsin born?",
       [["Tamsin", PB, "Greywater"]], [["Tamsin", PB, "Greywater"]], [],
       None, "nope, that's false"),
    it("contextual_denial", ["Oakes works at Fennimore.",
                             "Oakes lives in Brightwell.",
                             "Where does Oakes live?"],
       "That isn't true.", "Where does Oakes live?",
       [["Oakes", E, "Fennimore"], ["Oakes", CI, "Brightwell"]],
       [["Oakes", CI, "Brightwell"]], [["Oakes", E, "Fennimore"]], None,
       "that isn't true, other fact kept"),
    it("contextual_denial", ["Vesna's sister is Irla.",
                             "Who is Vesna's sister?"],
       "That's not correct!", "Who is Vesna's sister?",
       [["Vesna", "sister", "Irla"]], [["Vesna", "sister", "Irla"]], [],
       None, "that's not correct!"),
    it("contextual_denial", ["Bram works at Kettleby.",
                             "Whose employer is Kettleby?"],
       "That's wrong.", "Where does Bram work?",
       [["Bram", E, "Kettleby"]], [["Bram", E, "Kettleby"]], [], None,
       "after a reverse answer"),
]
# ------------------------------------------------------ contextual_correction
I += [
    it("contextual_correction", ["Cato lives in Pellham.",
                                 "Where does Cato live?"],
       "No, it's Rookwell.", "Where does Cato live?",
       [["Cato", CI, "Pellham"]], [["Cato", CI, "Pellham"]],
       [["Cato", CI, "Rookwell"]], "Rookwell", "no, it's Z"),
    it("contextual_correction", ["Idris works at Harrowgate.",
                                 "Where does Idris work?"],
       "Actually it's Stonemere.", "Where does Idris work?",
       [["Idris", E, "Harrowgate"]], [["Idris", E, "Harrowgate"]],
       [["Idris", E, "Stonemere"]], "Stonemere", "actually it's Z"),
    it("contextual_correction", ["Maela lives in Dunhollow.",
                                 "Where does Maela live?"],
       "No, she lives in Farrowby now.", "Where does Maela live?",
       [["Maela", CI, "Dunhollow"]], [["Maela", CI, "Dunhollow"]],
       [["Maela", CI, "Farrowby"]], "Farrowby", "pronoun clause + now"),
    it("contextual_correction", ["Teodor's boss is Grisel.",
                                 "Who is Teodor's boss?"],
       "It's Wenna, not Grisel.", "Who is Teodor's boss?",
       [["Teodor", "boss", "Grisel"]], [["Teodor", "boss", "Grisel"]],
       [["Teodor", "boss", "Wenna"]], "Wenna", "it's Z, not Y"),
    it("contextual_correction", ["Aurek speaks Solvan.",
                                 "What language does Aurek speak?"],
       "nope, it's brisic", "What language does Aurek speak?",
       [["Aurek", L, "Solvan"]], [["Aurek", L, "Solvan"]],
       [["Aurek", L, "brisic"]], "brisic", "lowercase nope it's z"),
    it("contextual_correction", ["Lysa was born in Morrowgate.",
                                 "Where was Lysa born?"],
       "Wrong, it was Eddervale.", "Where was Lysa born?",
       [["Lysa", PB, "Morrowgate"]], [["Lysa", PB, "Morrowgate"]],
       [["Lysa", PB, "Eddervale"]], "Eddervale", "wrong, it was Z"),
    it("contextual_correction", ["Quill works at Barrowdyne.",
                                 "Where does Quill work?"],
       "No, he works at Halvercross.", "Where does Quill work?",
       [["Quill", E, "Barrowdyne"]], [["Quill", E, "Barrowdyne"]],
       [["Quill", E, "Halvercross"]], "Halvercross", "he works at Z"),
    it("contextual_correction", ["Runa's sister is Delphine.",
                                 "Who is Runa's sister?"],
       "No, her sister is Mirelle.", "Who is Runa's sister?",
       [["Runa", "sister", "Delphine"]], [["Runa", "sister", "Delphine"]],
       [["Runa", "sister", "Mirelle"]], "Mirelle", "her R is Z"),
    it("contextual_correction", ["Soren lives in Ivybridge.",
                                 "Where does Soren live?"],
       "Not Ivybridge, Cardenmoor.", "Where does Soren live?",
       [["Soren", CI, "Ivybridge"]], [["Soren", CI, "Ivybridge"]],
       [["Soren", CI, "Cardenmoor"]], "Cardenmoor", "not Y, Z"),
    it("contextual_correction", ["Elka's manager is Porrit.",
                                 "Who is Elka's manager?"],
       "no - it should be Varga", "Who is Elka's manager?",
       [["Elka", "manager", "Porrit"]], [["Elka", "manager", "Porrit"]],
       [["Elka", "manager", "Varga"]], "Varga", "it should be Z"),
]
# -------------------------------------------------------- explicit_correction
I += [
    it("explicit_correction", ["Hesper lives in Tallowfen."],
       "Actually, Hesper lives in Morwick, not Tallowfen.",
       "Where does Hesper live?",
       [["Hesper", CI, "Tallowfen"]], [["Hesper", CI, "Tallowfen"]],
       [["Hesper", CI, "Morwick"]], "Morwick", "actually X verb Z, not Y"),
    it("explicit_correction", ["Dace works at Glimmerholt."],
       "Dace doesn't work at Glimmerholt, he works at Ravensby.",
       "Where does Dace work?",
       [["Dace", E, "Glimmerholt"]], [["Dace", E, "Glimmerholt"]],
       [["Dace", E, "Ravensby"]], "Ravensby", "denial + pronoun positive"),
    it("explicit_correction", ["Olwen speaks Tarric."],
       "I was wrong, Olwen speaks Mennish.",
       "What language does Olwen speak?",
       [["Olwen", L, "Tarric"]], [["Olwen", L, "Tarric"]],
       [["Olwen", L, "Mennish"]], "Mennish", "i was wrong + multi key"),
    it("explicit_correction", ["Keir's boss is Fallon."],
       "Correction: Keir's boss is Aldous.", "Who is Keir's boss?",
       [["Keir", "boss", "Fallon"]], [["Keir", "boss", "Fallon"]],
       [["Keir", "boss", "Aldous"]], "Aldous", "correction colon"),
    it("explicit_correction", ["Brisa lives in Coldmere."],
       "sorry, Brisa lives in Oxhollow.", "Where does Brisa live?",
       [["Brisa", CI, "Coldmere"]], [["Brisa", CI, "Coldmere"]],
       [["Brisa", CI, "Oxhollow"]], "Oxhollow",
       "lowercase sorry prefix (base teach refuses lowercase verb values)"),
    it("explicit_correction", ["Thane was born in Harrowmere."],
       "Thane wasn't born in Harrowmere, he was born in Sallowby.",
       "Where was Thane born?",
       [["Thane", PB, "Harrowmere"]], [["Thane", PB, "Harrowmere"]],
       [["Thane", PB, "Sallowby"]], "Sallowby", "wasn't born, was born"),
    it("explicit_correction", ["Merrin works at Dovecote."],
       "My mistake - Merrin works at Blackwater.", "Where does Merrin work?",
       [["Merrin", E, "Dovecote"]], [["Merrin", E, "Dovecote"]],
       [["Merrin", E, "Blackwater"]], "Blackwater", "my mistake dash"),
    it("explicit_correction", ["Ansa's sister is Coralie."],
       "Ansa's sister isn't Coralie, it's Brienne.", "Who is Ansa's sister?",
       [["Ansa", "sister", "Coralie"]], [["Ansa", "sister", "Coralie"]],
       [["Ansa", "sister", "Brienne"]], "Brienne", "isn't Y, it's Z"),
]
# ------------------------------------------------------------ unstored_denial
I += [
    it("unstored_denial", ["Pavo works at Linthorpe."],
       "Pavo doesn't work at Garrowden.", "Where does Pavo work?",
       [["Pavo", E, "Linthorpe"]], [], [["Pavo", E, "Linthorpe"]],
       "Linthorpe", "known person, other value"),
    it("unstored_denial", ["Kell lives in Marrowby."],
       "Zandor doesn't live in Marrowby.", "Where does Kell live?",
       [["Kell", CI, "Marrowby"]], [], [["Kell", CI, "Marrowby"]],
       "Marrowby", "unknown person"),
    it("unstored_denial", ["Ilse's boss is Horne."],
       "Brevik isn't Ilse's boss.", "Who is Ilse's boss?",
       [["Ilse", "boss", "Horne"]], [], [["Ilse", "boss", "Horne"]],
       "Horne", "possessive, other value"),
    it("unstored_denial", ["Tobin speaks Carric."],
       "Tobin does not speak Vellish.", "What language does Tobin speak?",
       [["Tobin", L, "Carric"]], [], [["Tobin", L, "Carric"]], "Carric",
       "language other value"),
    it("unstored_denial", ["Nessa works at Holloway."],
       "That's not true, Nessa doesn't live in Holloway.",
       "Where does Nessa work?",
       [["Nessa", E, "Holloway"]], [], [["Nessa", E, "Holloway"]],
       "Holloway", "same value, other relation"),
    it("unstored_denial", ["Garet lives in Wyndham."],
       "Garet no longer lives in Ostermere.", "Where does Garet live?",
       [["Garet", CI, "Wyndham"]], [], [["Garet", CI, "Wyndham"]], "Wyndham",
       "no longer, other value"),
]
# ------------------------------------------------------------------ ambiguous
I += [
    it("ambiguous", ["Pirra speaks Oltan.", "Pirra speaks Venn.",
                     "What language does Pirra speak?"],
       "That's wrong.", "What language does Pirra speak?",
       [["Pirra", L, "Oltan"], ["Pirra", L, "Venn"]], [],
       [["Pirra", L, "Oltan"], ["Pirra", L, "Venn"]], "Oltan; Venn",
       "two values stated"),
    it("ambiguous", ["Hale works at Corrin.", "Hale lives in Ashby.",
                     "Tell me about Hale."],
       "No, that's not right.", "Where does Hale live?",
       [["Hale", E, "Corrin"], ["Hale", CI, "Ashby"]], [],
       [["Hale", E, "Corrin"], ["Hale", CI, "Ashby"]], "Ashby",
       "tell me about, two facts"),
    it("ambiguous", ["Maddox lives in Pennyfold."],
       "That's wrong.", "Where does Maddox live?",
       [["Maddox", CI, "Pennyfold"]], [], [["Maddox", CI, "Pennyfold"]],
       "Pennyfold", "previous reply was a save, not a stated answer"),
    it("ambiguous", ["Lisel works at Orrin.", "Hello"],
       "No, it's Tanner.", "Where does Lisel work?",
       [["Lisel", E, "Orrin"]], [], [["Lisel", E, "Orrin"]], "Orrin",
       "no stated fact"),
    it("ambiguous", ["Cass speaks Druvic.", "Cass speaks Olm.",
                     "What language does Cass speak?"],
       "No, it's Pellish.", "What language does Cass speak?",
       [["Cass", L, "Druvic"], ["Cass", L, "Olm"]], [],
       [["Cass", L, "Druvic"], ["Cass", L, "Olm"]], "Druvic; Olm",
       "correction after two values"),
    it("ambiguous", ["Wystan's employer is Brackley.",
                     "Brackley's city is Norhaven.",
                     "Which city is Wystan's employer in?"],
       "That's not true.", "Where does Wystan work?",
       [["Wystan", E, "Brackley"], ["Brackley", CI, "Norhaven"]], [],
       [["Wystan", E, "Brackley"], ["Brackley", CI, "Norhaven"]],
       "Brackley", "inferred two-hop answer: ask"),
    it("ambiguous", ["Ronan works at Gilder.", "Where does Ronan work?"],
       "No, Hattie.", "Where does Ronan work?",
       [["Ronan", E, "Gilder"]], [], [["Ronan", E, "Gilder"]], "Gilder",
       "bare name after no: could be a vocative, ask"),
]
# -------------------------------------------------------------- question_trap
I += [
    it("question_trap", ["Rhian lives in Kestle."],
       "Doesn't Rhian live in Kestle?", "Where does Rhian live?",
       [["Rhian", CI, "Kestle"]], [], [["Rhian", CI, "Kestle"]], "Kestle",
       "doesn't X"),
    it("question_trap", ["Otto's boss is Brenna."],
       "Isn't Brenna Otto's boss?", "Who is Otto's boss?",
       [["Otto", "boss", "Brenna"]], [], [["Otto", "boss", "Brenna"]],
       "Brenna", "isn't Y X's R"),
    it("question_trap", ["Ferris works at Umber."],
       "Is it true that Ferris doesn't work at Umber?",
       "Where does Ferris work?",
       [["Ferris", E, "Umber"]], [], [["Ferris", E, "Umber"]], "Umber",
       "is it true that"),
    it("question_trap", ["Gilda was born in Tarn."],
       "Wasn't Gilda born in Tarn?", "Where was Gilda born?",
       [["Gilda", PB, "Tarn"]], [], [["Gilda", PB, "Tarn"]], "Tarn",
       "wasn't"),
    it("question_trap", ["Hob speaks Cantic."],
       "doesn't hob speak cantic", "What language does Hob speak?",
       [["Hob", L, "Cantic"]], [], [["Hob", L, "Cantic"]], "Cantic",
       "no question mark, lowercase"),
    it("question_trap", ["Ysolt lives in Brae.", "Where does Ysolt live?"],
       "That's wrong?", "Where does Ysolt live?",
       [["Ysolt", CI, "Brae"]], [], [["Ysolt", CI, "Brae"]], "Brae",
       "denial phrase as a question"),
    it("question_trap", ["Arvo works at Penlow."],
       "Does Arvo not work at Penlow?", "Where does Arvo work?",
       [["Arvo", E, "Penlow"]], [], [["Arvo", E, "Penlow"]], "Penlow",
       "does X not"),
    it("question_trap", ["Jessamy's sister is Rook."],
       "Is Rook not Jessamy's sister?", "Who is Jessamy's sister?",
       [["Jessamy", "sister", "Rook"]], [], [["Jessamy", "sister", "Rook"]],
       "Rook", "is Y not X's R"),
    it("question_trap", ["Linnet lives in Farthing."],
       "Why doesn't Linnet live in Farthing anymore?",
       "Where does Linnet live?",
       [["Linnet", CI, "Farthing"]], [], [["Linnet", CI, "Farthing"]],
       "Farthing", "why doesn't"),
    it("question_trap", ["Corra works at Ellwood."],
       "So Corra doesn't work at Ellwood?", "Where does Corra work?",
       [["Corra", E, "Ellwood"]], [], [["Corra", E, "Ellwood"]], "Ellwood",
       "statement-shaped question with ?"),
]
# -------------------------------------------------------------------- control
I += [
    it("control", ["Ambrose works at Kilnworth."], "Where does Ambrose work?",
       "Whose employer is Kilnworth?",
       [["Ambrose", E, "Kilnworth"]], [], [["Ambrose", E, "Kilnworth"]],
       "Ambrose", "plain question"),
    it("control", ["Delia lives in Oxmoor."], "Delia's city is not Oxmoor.",
       "Where does Delia live?",
       [["Delia", CI, "Oxmoor"]], [["Delia", CI, "Oxmoor"]], [], None,
       "base 154f negation"),
    it("control", ["Finch lives in Harlow."], "No, Finch lives in Moorcombe.",
       "Where does Finch live?",
       [["Finch", CI, "Harlow"]], [["Finch", CI, "Harlow"]],
       [["Finch", CI, "Moorcombe"]], "Moorcombe", "base named correction"),
    it("control", ["Greer's boss is Tully."], "Actually, Greer's boss is Vance.",
       "Who is Greer's boss?",
       [["Greer", "boss", "Tully"]], [["Greer", "boss", "Tully"]],
       [["Greer", "boss", "Vance"]], "Vance", "base actually correction"),
    it("control", ["Hannes speaks Lorric."], "Hannes works at Crane.",
       "Where does Hannes work?",
       [["Hannes", L, "Lorric"]], [],
       [["Hannes", L, "Lorric"], ["Hannes", E, "Crane"]], "Crane",
       "plain teach"),
    it("control", ["Ivor lives in Beckton."], "Who is Ivor's boss?",
       "Where does Ivor live?",
       [["Ivor", CI, "Beckton"]], [], [["Ivor", CI, "Beckton"]], "Beckton",
       "unknown relation question"),
    it("control", ["Jude's sister is Pella."], "Jude's sister is not Pella.",
       "Who is Jude's sister?",
       [["Jude", "sister", "Pella"]], [["Jude", "sister", "Pella"]], [], None,
       "base 154f negation person"),
    it("control", ["Kasimir works at Holt."], "Thanks!",
       "Where does Kasimir work?",
       [["Kasimir", E, "Holt"]], [], [["Kasimir", E, "Holt"]], "Holt",
       "thanks"),
    it("control", ["Lark lives in Tamberly."], "Tell me about Lark.",
       "Where does Lark live?",
       [["Lark", CI, "Tamberly"]], [], [["Lark", CI, "Tamberly"]],
       "Tamberly", "tell me about"),
    it("control", ["My name is Oren."], "Actually, my name is Jorvell.",
       "no", [["USER", "name", "Oren"]], [], [["USER", "name", "Oren"]],
       None, "own name keeps the confirm flow; followup answers no"),
    it("control", ["Sully lives in Pembry.", "Where does Sully live?"],
       "It's Tuesday.", "Where does Sully live?",
       [["Sully", CI, "Pembry"]], [], [["Sully", CI, "Pembry"]], "Pembry",
       "small talk after an answer, no correction word"),
]
# -------------------------------------------------------------------- restart
I += [
    it("restart", ["Mabry works at Stellan."], "Mabry doesn't work at Stellan.",
       "Where does Mabry work?",
       [["Mabry", E, "Stellan"]], [["Mabry", E, "Stellan"]], [], None,
       "deny, restart, both directions", restart=True,
       extra=[["Whose employer is Stellan?", ["Mabry"], []]]),
    it("restart", ["Nyle lives in Corbet.", "Where does Nyle live?"],
       "That's wrong.", "Where does Nyle live?",
       [["Nyle", CI, "Corbet"]], [["Nyle", CI, "Corbet"]], [], None,
       "contextual deny, restart", restart=True,
       extra=[["Who lives in Corbet?", ["Nyle"], []]]),
    it("restart", ["Oona speaks Fennic.", "What language does Oona speak?"],
       "No, it's Garrish.", "What language does Oona speak?",
       [["Oona", L, "Fennic"]], [["Oona", L, "Fennic"]],
       [["Oona", L, "Garrish"]], "Garrish", "contextual correct, restart",
       restart=True, extra=[["What language does Oona speak?",
                             ["Fennic"], ["Garrish"]]]),
    it("restart", ["Pryce's boss is Wilder."], "Wilder isn't Pryce's boss.",
       "Who is Pryce's boss?",
       [["Pryce", "boss", "Wilder"]], [["Pryce", "boss", "Wilder"]], [], None,
       "possessive deny, restart", restart=True,
       extra=[["Whose boss is Wilder?", ["Pryce"], []]]),
    it("restart", ["Quinta lives in Aldwick."],
       "Actually, Quinta lives in Bexley, not Aldwick.",
       "Where does Quinta live?",
       [["Quinta", CI, "Aldwick"]], [["Quinta", CI, "Aldwick"]],
       [["Quinta", CI, "Bexley"]], "Bexley", "explicit correct, restart",
       restart=True, extra=[["Whose city is Aldwick?", ["Quinta"], []]]),
]


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    for n, d in enumerate(I, 1):
        d = {"id": f"d252-{n:03d}", **d}
        lines.append(json.dumps(d, ensure_ascii=False))
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    fams: dict[str, int] = {}
    for d in I:
        fams[d["family"]] = fams.get(d["family"], 0) + 1
    print(len(I), fams)
    return 0


if __name__ == "__main__":
    sys.exit(main())
