#!/usr/bin/env python3
"""Exp 293 dev dialogs: DIAG 61 (ids dh-/ip-/ii-/dl-/dw-/df-/h-/s-/w-) + 50 new (n-*).
New file only. Fictional names. Never a panel; never tuned-on test material.")
D61 + N50 = 111 dialogs: (id, setup turns, question, arm, shape).
"""
D61 = [
    ('dh-true1', ["Bex's dog is Biscuit."], 'Does Bex have a dog?', 'taught-true', 'does-have'),
    ('dh-true2', ["Lena's mother is Wren."], 'Does Lena have a mother?', 'taught-true', 'does-have'),
    ('dh-true-2word', ["Mary Ann's mother is Wren."], 'Does Mary Ann have a mother?', 'taught-true', 'does-have'),
    ('dh-never1', ["Bex's mother is Talia."], 'Does Bex have a dog?', 'unknown', 'does-have'),
    ('dh-never2', ["Rin's boss is Lee."], 'Does Rin have a brother?', 'unknown', 'does-have'),
    ('dh-never-2word', ["Anna Lee's city is Oslo."], 'Does Anna Lee have a dog?', 'unknown', 'does-have'),
    ('dh-taken-forget', ["Bex's dog is Biscuit.", "Forget Bex's dog."], 'Does Bex have a dog?', 'taken-back', 'does-have'),
    ('dh-taken-isnot', ["Lena's mother is Wren.", "Lena's mother is not Wren."], 'Does Lena have a mother?', 'taken-back', 'does-have'),
    ('dh-corrected', ["Lena's mother is Wren.", "Actually Lena's mother is Pell.", 'Yes.'], 'Does Lena have a mother?', 'taught-true', 'does-have'),
    ('dh-noart', ["Lena's mother is Wren."], 'Does Lena have mother?', 'taught-true', 'does-noart'),
    ('ip-true1', ["Bex's mother is Talia."], "Is Bex's mother Talia?", 'taught-true', 'is-poss'),
    ('ip-true2', ["Rin's city is Bergen."], "Is Rin's city Bergen?", 'taught-true', 'is-poss'),
    ('ip-true-2word', ["Mary Ann's mother is Wren."], "Is Mary Ann's mother Wren?", 'taught-true', 'is-poss'),
    ('ip-false1', ["Bex's mother is Talia."], "Is Bex's mother Wren?", 'taught-false', 'is-poss'),
    ('ip-false2', ["Rin's city is Bergen."], "Is Rin's city Oslo?", 'taught-false', 'is-poss'),
    ('ip-false-multi', ["Bex's sister is Ada."], "Is Bex's sister Bea?", 'taught-false', 'is-poss'),
    ('ip-unknown-rel', ["Bex's mother is Talia."], "Is Bex's father Talia?", 'unknown', 'is-poss'),
    ('ip-unknown-subj', ["Bex's mother is Talia."], "Is Zane's mother Talia?", 'unknown', 'is-poss'),
    ('ip-taken-forget', ["Bex's dog is Biscuit.", "Forget Bex's dog."], "Is Bex's dog Biscuit?", 'taken-back', 'is-poss'),
    ('ip-taken-isnot', ["Lena's mother is Wren.", "Lena's mother is not Wren."], "Is Lena's mother Wren?", 'taken-back', 'is-poss'),
    ('ip-correct-new', ["Lena's mother is Wren.", "Actually Lena's mother is Pell.", 'Yes.'], "Is Lena's mother Pell?", 'taught-true', 'is-poss'),
    ('ip-correct-old', ["Lena's mother is Wren.", "Actually Lena's mother is Pell.", 'Yes.'], "Is Lena's mother Wren?", 'taught-false', 'is-poss'),
    ('ip-ofform', ["Bex's mother is Talia."], 'Is Talia the mother of Bex?', 'taught-true', 'is-of'),
    ('ii-true1', ["Bex's mother is Talia."], "Is Talia Bex's mother?", 'taught-true', 'is-inv'),
    ('ii-false1', ["Bex's mother is Talia."], "Is Wren Bex's mother?", 'taught-false', 'is-inv'),
    ('ii-unknown-subj', ["Bex's mother is Talia."], "Is Talia Zane's mother?", 'unknown', 'is-inv'),
    ('ii-unknown-rel', ["Bex's mother is Talia."], "Is Talia Bex's father?", 'unknown', 'is-inv'),
    ('ii-2word', ["Mary Ann's mother is Wren."], "Is Wren Mary Ann's mother?", 'taught-true', 'is-inv'),
    ('ii-taken', ["Bex's dog is Biscuit.", "Forget Bex's dog."], "Is Biscuit Bex's dog?", 'taken-back', 'is-inv'),
    ('ii-true2', ["Zane's city is Porto."], "Is Porto Zane's city?", 'taught-true', 'is-inv'),
    ('ii-false2', ["Zane's city is Porto."], "Is Oslo Zane's city?", 'taught-false', 'is-inv'),
    ('dl-true', ["Rin's city is Bergen."], 'Does Rin live in Bergen?', 'taught-true', 'does-live'),
    ('dl-false', ["Rin's city is Bergen."], 'Does Rin live in Oslo?', 'taught-false', 'does-live'),
    ('dl-unknown', ["Bex's mother is Talia."], 'Does Bex live in Oslo?', 'unknown', 'does-live'),
    ('dl-2word-true', ["Anna Lee's city is Oslo."], 'Does Anna Lee live in Oslo?', 'taught-true', 'does-live'),
    ('dl-taken-forget', ["Zane's city is Porto.", "Forget Zane's city."], 'Does Zane live in Porto?', 'taken-back', 'does-live'),
    ('dl-correct-new', ["Rin's city is Bergen.", "Actually Rin's city is Oslo.", 'Yes.'], 'Does Rin live in Oslo?', 'taught-true', 'does-live'),
    ('dl-taken-isnot', ["Rin's city is Bergen.", "Rin's city is not Bergen."], 'Does Rin live in Bergen?', 'taken-back', 'does-live'),
    ('dw-sameval', ["Rin's city is Halden."], 'Does Rin work at Halden?', 'taught-true', 'does-work'),
    ('dw-diffval', ["Rin's city is Halden."], 'Does Rin work at Oslo?', 'taught-false', 'does-work'),
    ('dw-unknown', ["Bex's mother is Talia."], 'Does Rin work at Halden?', 'unknown', 'does-work'),
    ('dw-2word', ["Anna Lee's city is Oslo."], 'Does Anna Lee work at Oslo?', 'taught-true', 'does-work'),
    ('dw-taken', ["Rin's city is Halden.", "Forget Rin's city."], 'Does Rin work at Halden?', 'taken-back', 'does-work'),
    ('df-sameval', ["Rin's city is Bergen."], 'Does Rin come from Bergen?', 'taught-true', 'does-from'),
    ('df-diffval', ["Rin's city is Bergen."], 'Does Rin come from Oslo?', 'taught-false', 'does-from'),
    ('df-unknown', ["Bex's mother is Talia."], 'Does Zane come from Porto?', 'unknown', 'does-from'),
    ('df-2word', ["Jo Marlowe's city is Oslo."], 'Does Jo Marlowe come from Oslo?', 'taught-true', 'does-from'),
    ('df-taken', ["Zane's city is Porto.", "Zane's city is not Porto."], 'Does Zane come from Porto?', 'taken-back', 'does-from'),
    ('h-true', ["Bex's dog is Biscuit."], 'Has Bex a dog?', 'taught-true', 'has'),
    ('h-never', ["Bex's mother is Talia."], 'Has Bex a dog?', 'unknown', 'has'),
    ('h-taken', ["Bex's dog is Biscuit.", "Forget Bex's dog."], 'Has Bex a dog?', 'taken-back', 'has'),
    ('s-does1', [], 'Bex does judo on Tuesdays.', 'control', 'stmt'),
    ('s-does2', [], 'Sam does the dishes every night.', 'control', 'stmt'),
    ('s-is1', [], 'Ana is happy.', 'control', 'stmt'),
    ('s-is2', [], 'The sky is blue.', 'control', 'stmt'),
    ('w-what-taught', ["Bex's mother is Talia."], "What is Bex's mother?", 'control', 'wh'),
    ('w-where-never', ["Bex's mother is Talia."], 'Where does Zane live?', 'control', 'wh'),
    ('w-who-taken', ["Marko's boss is Lee.", "Forget Marko's boss."], "Who is Marko's boss?", 'control', 'wh'),
    ('w-inv-boundary', ["Bex's city is Oslo."], 'Where lives Bex?', 'control', 'wh'),
    ('w-where-taught', ["Rin's city is Bergen."], 'Where does Rin live?', 'control', 'wh'),
    ('w-born-never', ["Bex's mother is Talia."], 'Where was Bex born?', 'control', 'wh'),
]
N50 = [
    ('n-hasgot-true', ["Suki's dentist is Vera."], 'Has Suki got a dentist?', 'taught-true', 'has-got'),
    ('n-hasgot-uncle', ["Dario's uncle is Per."], 'Has Dario got an uncle?', 'taught-true', 'has-got'),
    ('n-hasgot-unknown', ["Suki's dentist is Vera."], 'Has Suki got a coach?', 'unknown', 'has-got'),
    ('n-hasgot-2word', ["Nora Field's coach is Nils."], 'Has Nora Field got a coach?', 'taught-true', 'has-got'),
    ('n-hasgot-taken', ["Suki's dentist is Vera.", "Forget Suki's dentist."], 'Has Suki got a dentist?', 'taken-back', 'has-got'),
    ('n-dh-multi-yes', ["Willa's sister is Liv."], 'Does Willa have a sister?', 'taught-true', 'does-have'),
    ('n-dh-multi-unknown', ["Willa's sister is Liv."], 'Does Willa have a brother?', 'unknown', 'does-have'),
    ('n-dh-corrected', ["Hugo's boss is Lee.", "Actually Hugo's boss is Jon.", 'Yes.'], 'Does Hugo have a boss?', 'taught-true', 'does-have'),
    ('n-dh-2word-emp', ["Sam Reyes's employer is Kestrel."], 'Does Sam Reyes have an employer?', 'taught-true', 'does-have'),
    ('n-dh-neverrel', ["Nadia's city is Alta."], 'Does Nadia have a yacht?', 'unknown', 'does-have'),
    ('n-dh-taken-born', ["Felix's birthplace is Narvik.", "Forget Felix's birthplace."], 'Does Felix have a birthplace?', 'taken-back', 'does-have'),
    ('n-dh-noart2', ["Petra's dentist is Vera."], 'Does Petra have dentist?', 'taught-true', 'does-noart'),
    ('n-dl-2word-false', ["Eva Stone's city is Molde."], 'Does Eva Stone live in Alta?', 'taught-false', 'does-live'),
    ('n-dl-emp-only', ["Otto's employer is Lumen."], 'Does Otto live in Bodo?', 'unknown', 'does-live'),
    ('n-dl-taken', ["Priya's city is Alta.", "Priya's city is not Alta."], 'Does Priya live in Alta?', 'taken-back', 'does-live'),
    ('n-dl-corrected', ["Quinn's city is Alta.", "Actually Quinn's city is Bodo.", 'Yes.'], 'Does Quinn live in Bodo?', 'taught-true', 'does-live'),
    ('n-dw-yes', ["Tomas's employer is Meridian."], 'Does Tomas work at Meridian?', 'taught-true', 'does-work'),
    ('n-dw-no', ["Tomas's employer is Meridian."], 'Does Tomas work at Bluefin?', 'taught-false', 'does-work'),
    ('n-dw-for', ["Ines's employer is Bluefin."], 'Does Ines work for Bluefin?', 'taught-true', 'does-work'),
    ('n-dw-2word', ["Ari Vale's employer is Kestrel."], 'Does Ari Vale work at Kestrel?', 'taught-true', 'does-work'),
    ('n-dw-taken', ["Tomas's employer is Meridian.", "Forget Tomas's employer."], 'Does Tomas work at Meridian?', 'taken-back', 'does-work'),
    ('n-dw-unknown', ["Tomas's city is Alta."], 'Does Quinn work at Meridian?', 'unknown', 'does-work'),
    ('n-df-yes', ["Nadia's birthplace is Stavanger."], 'Does Nadia come from Stavanger?', 'taught-true', 'does-from'),
    ('n-df-no', ["Nadia's birthplace is Stavanger."], 'Does Nadia come from Trondheim?', 'taught-false', 'does-from'),
    ('n-born-was', ["Felix's birthplace is Narvik."], 'Was Felix born in Narvik?', 'taught-true', 'was-born'),
    ('n-born-was-no', ["Felix's birthplace is Narvik."], 'Was Felix born in Alta?', 'taught-false', 'was-born'),
    ('n-born-2word', ["Mia Frost's birthplace is Drammen."], 'Does Mia Frost come from Drammen?', 'taught-true', 'does-from'),
    ('n-born-taken', ["Nadia's birthplace is Stavanger.", "Nadia's birthplace is not Stavanger."], 'Does Nadia come from Stavanger?', 'taken-back', 'does-from'),
    ('n-ip-multivalue', ["Willa's dentist is Ava Lind."], "Is Willa's dentist Ava Lind?", 'taught-true', 'is-poss'),
    ('n-ip-multivalue-no', ["Willa's dentist is Ava Lind."], "Is Willa's dentist Vera?", 'taught-false', 'is-poss'),
    ('n-ii-multivalue', ["Sam Reyes's boss is Jon."], "Is Jon Sam Reyes's boss?", 'taught-true', 'is-inv'),
    ('n-ii-multivalue-no', ["Sam Reyes's boss is Jon."], "Is Per Sam Reyes's boss?", 'taught-false', 'is-inv'),
    ('n-of-2word', ["Nora Field's mother is Liv."], 'Is Liv the mother of Nora Field?', 'taught-true', 'is-of'),
    ('n-of-no', ["Nora Field's mother is Liv."], 'Is Ava the mother of Nora Field?', 'taught-false', 'is-of'),
    ('n-ip-employer', ["Tomas's employer is Meridian."], "Is Tomas's employer Meridian?", 'taught-true', 'is-poss'),
    ('n-ip-birth', ["Felix's birthplace is Narvik."], "Is Felix's birthplace Narvik?", 'taught-true', 'is-poss'),
    ('n-ip-sister-corrected', ["Willa's sister is Liv.", "Actually Willa's sister is Sana.", 'Yes.'], "Is Willa's sister Sana?", 'taught-true', 'is-poss'),
    ('n-chain-live', ["Suki's boss is Jon.", "Jon's city is Bodo."], "Does Suki's boss live in Bodo?", 'control-chain', 'chain'),
    ('n-chain-is', ["Suki's boss is Jon.", "Jon's city is Bodo."], "Is Bodo the city of Suki's boss?", 'control-chain', 'chain'),
    ('n-chain-have', ["Willa's sister is Liv.", "Liv's city is Alta."], "Does Willa's sister have a city?", 'control-chain', 'chain'),
    ('n-chain-work', ["Tomas's boss is Jon.", "Jon's employer is Kestrel."], "Does Tomas's boss work at Kestrel?", 'control-chain', 'chain'),
    ('n-chain-inv', ["Nora Field's mother is Liv.", "Liv's city is Alta."], "Is Alta Nora Field's mother's city?", 'control-chain', 'chain'),
    ('n-stmt-does', [], 'Petra does pottery on Fridays.', 'control', 'stmt'),
    ('n-stmt-has', [], 'Dario has big plans for winter.', 'control', 'stmt'),
    ('n-stmt-is', [], 'Nora is tired today.', 'control', 'stmt'),
    ('n-wh-who', ["Suki's dentist is Vera."], "Who is Suki's dentist?", 'control', 'wh'),
    ('n-wh-where', ["Petra's city is Alta."], 'Where does Petra live?', 'control', 'wh'),
    ('n-wh-what', ["Dario's employer is Meridian."], "What is Dario's employer?", 'control', 'wh'),
    ('n-wh-2word', ["Nora Field's coach is Nils."], "Who is Nora Field's coach?", 'control', 'wh'),
    ('n-lower', ["Suki's dentist is Vera."], 'Does suki have a dentist?', 'control', 'stmt'),
]
D = D61 + N50
