#!/usr/bin/env python3
"""bm-riv: the rival arms for chat-asked grid puzzles (benchmarks thread, 2026-09-26). One runner for Sleep research's
rsn-358b3 gate panel and Month-end's 0.2d headline row A (design/v3/30-modes/02d-gates-ADDENDUM-7.md), which reuses it.

Interface agreed with Sleep research (14:45 UTC 09-26), taken from scripts/claude_rsn358b2_bridge.py (sealed 483b62ad5):
- Panel: JSONL rows {"size", "puz", "sol", "text"}; "text" is the chat message.
- Prompt: row["text"] + the bridge's ALONE_TAIL, as the one user turn; no system text. Greedy, thinking off, each
  model's own chat template, at most 160 new tokens. Generated by the bridge's own Talker class (bf16, left-padded
  batches of 16), exactly as the bridge's own "1B alone" arm, so every "alone" arm is prompted the same way.
- Scoring is the panel owner's: bridge.score(rows, replies). Replies are returned in panel order.
Arms (bm-390's pinned models): plain MiniCPM5-1B @87179e5c, Qwen3.5-2B @15852e8c, LFM2.5-1.2B-Instruct @0f604ada.
Report-only extra (--think on): the same prompt with the model's thinking on and a larger budget (--max-new), through
this file's own encoding (one item at a time); the reply is the text after </think>.

The panel is TEST-ONLY: this script reads each row's "text" (and "size" only for --score), never prints a panel row
or a reply, and prints counts only.

  python -B scripts/claude_bmriv_rivals.py run --panel PANEL.jsonl --model DIR --name NAME --out OUT
      [--think off|on] [--max-new 160] [--score]
  python -B scripts/claude_bmriv_rivals.py smoke-panel --seed S --n N --size s --out PANEL.jsonl   (the bridge's
      make_requests with this thread's own seeds; never 35900-35999)
  python -B scripts/claude_bmriv_rivals.py selftest --tok DIR   (a tiny random model with DIR's tokenizer, CPU)
Writes OUT/rival_<NAME>.jsonl: {"i", "reply"} per panel row, in panel order.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import claude_rsn358b2_bridge as BR  # noqa: E402

MAX_NEW = 160
RESERVED_SEEDS = range(35900, 36000)


def panel_rows(path: str) -> list[dict]:
    return [json.loads(x) for x in Path(path).read_text(encoding="utf-8").splitlines() if x.strip()]


def prompts_of(rows: list[dict]) -> list[str]:
    return [r["text"] + BR.ALONE_TAIL for r in rows]


def think_on(model_dir: str, prompts: list[str], max_new: int) -> list[str]:
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer
    dev = "cuda" if torch.cuda.is_available() else "cpu"
    tok = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(model_dir, dtype=torch.bfloat16, trust_remote_code=True).to(dev).eval()
    out = []
    for p in prompts:
        enc = tok.apply_chat_template([{"role": "user", "content": p}], tokenize=True, add_generation_prompt=True,
                                      enable_thinking=True, return_dict=True, return_tensors="pt").to(dev)
        with torch.no_grad():
            gen = model.generate(**enc, max_new_tokens=max_new, do_sample=False,
                                 pad_token_id=tok.pad_token_id if tok.pad_token_id is not None else tok.eos_token_id)
        text = tok.decode(gen[0][enc["input_ids"].shape[1]:], skip_special_tokens=True)
        out.append(text.split("</think>")[-1].strip() if "</think>" in text else "")
    return out


def run(a) -> int:
    import torch
    rows = panel_rows(a.panel)
    prompts = prompts_of(rows)
    t0 = time.time()
    if a.think == "on":
        replies = think_on(a.model, prompts, a.max_new)
    else:
        talker = BR.Talker(a.model, "cuda" if torch.cuda.is_available() else "cpu")
        replies = talker.say(prompts, max_new=a.max_new)
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    f = out / f"rival_{a.name}.jsonl"
    f.write_text("".join(json.dumps({"i": i, "reply": r}, ensure_ascii=False) + "\n" for i, r in enumerate(replies)),
                 encoding="utf-8")
    res = {"name": a.name, "rows": len(replies), "think": a.think, "max_new": a.max_new,
           "seconds": round(time.time() - t0), "sha256": hashlib.sha256(f.read_bytes()).hexdigest()}
    if a.score:
        res["score"] = BR.score(rows, replies)
    print(json.dumps(res), flush=True)
    return 0


def smoke_panel(a) -> int:
    if a.seed in RESERVED_SEEDS:
        raise SystemExit("bmriv: seeds 35900-35999 belong to Sleep research's panels")
    reqs = BR.make_requests(a.seed, a.n, a.size, False)
    Path(a.out).write_text("".join(json.dumps(r) + "\n" for r in reqs), encoding="utf-8")
    print(json.dumps({"rows": len(reqs), "size": a.size}))
    return 0


def selftest(a) -> int:
    import tempfile
    import torch
    from transformers import AutoTokenizer, LlamaConfig, LlamaForCausalLM
    ok = {}
    tok = AutoTokenizer.from_pretrained(a.tok)
    with tempfile.TemporaryDirectory() as d:
        torch.manual_seed(0)
        cfg = LlamaConfig(vocab_size=len(tok), hidden_size=16, intermediate_size=32, num_hidden_layers=1,
                          num_attention_heads=2, num_key_value_heads=1, max_position_embeddings=4096,
                          bos_token_id=tok.bos_token_id, eos_token_id=tok.eos_token_id, pad_token_id=tok.pad_token_id)
        LlamaForCausalLM(cfg).save_pretrained(Path(d) / "m")
        tok.save_pretrained(Path(d) / "m")
        panel = Path(d) / "panel.jsonl"
        smoke_panel(argparse.Namespace(seed=4101, n=3, size=5, out=str(panel)))
        rows = panel_rows(str(panel))
        ok["smoke panel has the bridge's row shape"] = all(set(r) == {"size", "puz", "sol", "text"} for r in rows)
        ok["prompt = text + the bridge's ALONE_TAIL"] = prompts_of(rows)[0] == rows[0]["text"] + BR.ALONE_TAIL
        for think, mx in (("off", 8), ("on", 6)):
            run(argparse.Namespace(panel=str(panel), model=str(Path(d) / "m"), name="F" + think,
                                   out=str(Path(d) / "o"), think=think, max_new=mx, score=True))
            back = [json.loads(x) for x in (Path(d) / "o" / f"rival_F{think}.jsonl").read_text().splitlines()]
            ok[f"think {think}: one row per panel row, in order"] = [r["i"] for r in back] == [0, 1, 2]
        ok["the bridge's scorer takes the replies"] = BR.score(rows, ["x"] * 3)["n"] == 3
        try:
            smoke_panel(argparse.Namespace(seed=35950, n=1, size=5, out=str(Path(d) / "z.jsonl")))
            ok["Sleep research's seeds refused"] = False
        except SystemExit:
            ok["Sleep research's seeds refused"] = True
    for k, v in ok.items():
        print(("PASS " if v else "FAIL ") + k)
    print("BMRIV-SELFTEST " + ("PASS" if all(ok.values()) else "FAIL") + f" {sum(ok.values())}/{len(ok)}")
    return 0 if all(ok.values()) else 1


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["run", "smoke-panel", "selftest"])
    ap.add_argument("--panel", default="")
    ap.add_argument("--model", default="")
    ap.add_argument("--name", default="")
    ap.add_argument("--out", default="")
    ap.add_argument("--think", choices=["off", "on"], default="off")
    ap.add_argument("--max-new", type=int, default=MAX_NEW)
    ap.add_argument("--score", action="store_true")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--n", type=int, default=0)
    ap.add_argument("--size", type=int, default=0)
    ap.add_argument("--tok", default="")
    a = ap.parse_args()
    return {"run": run, "smoke-panel": smoke_panel, "selftest": selftest}[a.cmd](a)


if __name__ == "__main__":
    sys.exit(main())
