#!/usr/bin/env python3
"""Exp 268b new dev dialogs: 46 own dialogs for 138nb's table reader shapes.

New file only. CPU only. Fictional names (none reused from 268's dev).
Fresh agent + isolated temp state dir per dialog, never the repo notebook.

Shapes: backwards verb questions the 221/237 table reader understands
("What has/did V written/write/founded/found?", "Who works at V?",
"Who does V coach?"), whose/has_as/married-to shapes on cued relations
(spouse, author, founder, employer, child, coach), no-chain controls,
uncued-relation controls (boss, mother, friend: no composer frame),
forward controls (possessive, who-wrote-X over-walk, forward 2-hop "of"),
multi-word names, a my-subject dialog, and abstain controls.

expect classes: WRONG-nhop (base predicted to answer V's own forward
fact from stage loop138-nhop) | CORRECT (base predicted right or
honestly non-committal) | RECORD (observe only). These are pre-pilot
guesses; the sealed predictions come from the pilot rows.
"""
from __future__ import annotations

# (dialog id, turns, gold final reply, expect class)
NEW268B: list[tuple[str, list[str], str, str]] = [
    # -- author verb shapes (table reader territory) --
    ("b01-author-whatwritten",
     ["Harbor Light's author is Nadia Ferreira.",
      "Nadia Ferreira's author is Tomas Ibarra.",
      "What has Nadia Ferreira written?"],
     "Harbor Light's author is Nadia Ferreira.", "WRONG-nhop"),
    ("b02-author-whatdid-write",
     ["Harbor Light's author is Nadia Ferreira.",
      "Nadia Ferreira's author is Tomas Ibarra.",
      "What did Nadia Ferreira write?"],
     "", "RECORD"),
    ("b03-author-whose",
     ["Harbor Light's author is Nadia Ferreira.",
      "Nadia Ferreira's author is Tomas Ibarra.",
      "Whose author is Nadia Ferreira?"],
     "Harbor Light's author is Nadia Ferreira.", "WRONG-nhop"),
    ("b04-author-who-has-as",
     ["Harbor Light's author is Nadia Ferreira.",
      "Nadia Ferreira's author is Tomas Ibarra.",
      "Who has Nadia Ferreira as their author?"],
     "Harbor Light's author is Nadia Ferreira.", "WRONG-nhop"),
    # -- founder verb shapes --
    ("b05-founder-whatdid-found",
     ["The Meridian Press's founder is Priya Nair.",
      "Priya Nair's founder is Joren Maas.",
      "What did Priya Nair found?"],
     "The Meridian Press's founder is Priya Nair.", "WRONG-nhop"),
    ("b06-founder-whathas-founded",
     ["The Meridian Press's founder is Priya Nair.",
      "Priya Nair's founder is Joren Maas.",
      "What has Priya Nair founded?"],
     "The Meridian Press's founder is Priya Nair.", "WRONG-nhop"),
    ("b07-founder-whose",
     ["The Meridian Press's founder is Priya Nair.",
      "Priya Nair's founder is Joren Maas.",
      "Whose founder is Priya Nair?"],
     "The Meridian Press's founder is Priya Nair.", "WRONG-nhop"),
    # -- employer shapes --
    ("b08-employer-who-works-at",
     ["Beacon Yard's employer is Keshi Adeyemi.",
      "Keshi Adeyemi's employer is Runa Ishikawa.",
      "Who works at Keshi Adeyemi?"],
     "", "RECORD"),
    ("b09-employer-whose",
     ["Beacon Yard's employer is Keshi Adeyemi.",
      "Keshi Adeyemi's employer is Runa Ishikawa.",
      "Whose employer is Keshi Adeyemi?"],
     "Beacon Yard's employer is Keshi Adeyemi.", "WRONG-nhop"),
    # -- coach shapes --
    ("b10-coach-who-does-coach",
     ["Harbor United's coach is Pavel Novak.",
      "Pavel Novak's coach is Ida Sorensen.",
      "Who does Pavel Novak coach?"],
     "", "RECORD"),
    ("b11-coach-whose",
     ["Harbor United's coach is Pavel Novak.",
      "Pavel Novak's coach is Ida Sorensen.",
      "Whose coach is Pavel Novak?"],
     "Harbor United's coach is Pavel Novak.", "WRONG-nhop"),
    # -- spouse shapes on the table base --
    ("b12-spouse-whose",
     ["Malik Haddad's spouse is Sanne Verhoeven.",
      "Sanne Verhoeven's spouse is Tariq Aziz.",
      "Whose spouse is Sanne Verhoeven?"],
     "Malik Haddad's spouse is Sanne Verhoeven.", "WRONG-nhop"),
    ("b13-spouse-married",
     ["Malik Haddad's spouse is Sanne Verhoeven.",
      "Sanne Verhoeven's spouse is Tariq Aziz.",
      "Who is married to Sanne Verhoeven?"],
     "", "RECORD"),
    ("b14-spouse-who-has-as",
     ["Malik Haddad's spouse is Sanne Verhoeven.",
      "Sanne Verhoeven's spouse is Tariq Aziz.",
      "Who has Sanne Verhoeven as their spouse?"],
     "Malik Haddad's spouse is Sanne Verhoeven.", "WRONG-nhop"),
    ("b15-spouse-was-married",
     ["Malik Haddad's spouse is Sanne Verhoeven.",
      "Sanne Verhoeven's spouse is Tariq Aziz.",
      "Who was married to Sanne Verhoeven?"],
     "", "RECORD"),
    # -- child shapes --
    ("b16-child-whose",
     ["Lena Fischer's child is Niko Papadopoulos.",
      "Niko Papadopoulos's child is Anya Petrova.",
      "Whose child is Niko Papadopoulos?"],
     "Lena Fischer's child is Niko Papadopoulos.", "WRONG-nhop"),
    ("b17-child-whose-son",
     ["Lena Fischer's child is Niko Papadopoulos.",
      "Niko Papadopoulos's child is Anya Petrova.",
      "Whose son is Niko Papadopoulos?"],
     "", "RECORD"),
    # -- 3-link mid-chain --
    ("b18-author-3link-whatwritten",
     ["The Glass Meridian's author is Felix Wagner.",
      "Felix Wagner's author is Amara Diallo.",
      "Amara Diallo's author is Boris Kessler.",
      "What has Felix Wagner written?"],
     "The Glass Meridian's author is Felix Wagner.", "WRONG-nhop"),
    ("b19-spouse-3link-whose",
     ["Elif Demir's spouse is Gustav Lund.",
      "Gustav Lund's spouse is Hana Sato.",
      "Hana Sato's spouse is Ivan Petrov.",
      "Whose spouse is Gustav Lund?"],
     "Elif Demir's spouse is Gustav Lund.", "WRONG-nhop"),
    # -- two subjects share V --
    ("b20-spouse-2subj-whose",
     ["Elif Demir's spouse is Gustav Lund.",
      "Hana Sato's spouse is Gustav Lund.",
      "Whose spouse is Gustav Lund?"],
     "", "RECORD"),
    ("b21-author-2subj-whose",
     ["The Glass Meridian's author is Felix Wagner.",
      "The Tin Orchard's author is Felix Wagner.",
      "Whose author is Felix Wagner?"],
     "", "RECORD"),
    # -- tense variants --
    ("b22-spouse-whose-was",
     ["Malik Haddad's spouse is Sanne Verhoeven.",
      "Sanne Verhoeven's spouse is Tariq Aziz.",
      "Whose spouse was Sanne Verhoeven?"],
     "Malik Haddad's spouse is Sanne Verhoeven.", "WRONG-nhop"),
    ("b23-author-what-had-written",
     ["Harbor Light's author is Nadia Ferreira.",
      "Nadia Ferreira's author is Tomas Ibarra.",
      "What had Nadia Ferreira written?"],
     "Harbor Light's author is Nadia Ferreira.", "WRONG-nhop"),
    ("b24-founder-whose-was",
     ["The Meridian Press's founder is Priya Nair.",
      "Priya Nair's founder is Joren Maas.",
      "Whose founder was Priya Nair?"],
     "The Meridian Press's founder is Priya Nair.", "WRONG-nhop"),
    ("b25-author-who-has-as-his",
     ["Harbor Light's author is Nadia Ferreira.",
      "Nadia Ferreira's author is Tomas Ibarra.",
      "Who has Nadia Ferreira as his author?"],
     "Harbor Light's author is Nadia Ferreira.", "WRONG-nhop"),
    ("b26-founder-who-has-as-their",
     ["The Meridian Press's founder is Priya Nair.",
      "Priya Nair's founder is Joren Maas.",
      "Who has Priya Nair as their founder?"],
     "The Meridian Press's founder is Priya Nair.", "WRONG-nhop"),
    # -- forward controls (guard must never fire) --
    ("b27-spouse-forward-possessive",
     ["Malik Haddad's spouse is Sanne Verhoeven.",
      "Sanne Verhoeven's spouse is Tariq Aziz.",
      "Who is Sanne Verhoeven's spouse?"],
     "Sanne Verhoeven's spouse is Tariq Aziz.", "CORRECT"),
    ("b28-author-forward-onehop",
     ["Harbor Light's author is Nadia Ferreira.",
      "Nadia Ferreira's author is Tomas Ibarra.",
      "Who is Harbor Light's author?"],
     "Harbor Light's author is Nadia Ferreira.", "CORRECT"),
    ("b29-founder-who-founded-subject",
     ["The Meridian Press's founder is Priya Nair.",
      "Priya Nair's founder is Joren Maas.",
      "Who founded The Meridian Press?"],
     "", "RECORD"),
    ("b30-author-who-wrote-overwalk",
     ["Harbor Light's author is Nadia Ferreira.",
      "Nadia Ferreira's author is Tomas Ibarra.",
      "Who wrote Harbor Light?"],
     "", "RECORD"),
    ("b31-spouse-forward-of",
     ["Malik Haddad's spouse is Sanne Verhoeven.",
      "Sanne Verhoeven's spouse is Tariq Aziz.",
      "Who is the spouse of Sanne Verhoeven?"],
     "", "RECORD"),
    ("b32-employer-forward-possessive",
     ["Beacon Yard's employer is Keshi Adeyemi.",
      "Keshi Adeyemi's employer is Runa Ishikawa.",
      "Who is Keshi Adeyemi's employer?"],
     "Keshi Adeyemi's employer is Runa Ishikawa.", "CORRECT"),
    ("b33-child-forward-possessive",
     ["Lena Fischer's child is Niko Papadopoulos.",
      "Niko Papadopoulos's child is Anya Petrova.",
      "Who is Niko Papadopoulos's child?"],
     "Niko Papadopoulos's child is Anya Petrova.", "CORRECT"),
    ("b34-yesno-control",
     ["Malik Haddad's spouse is Sanne Verhoeven.",
      "Sanne Verhoeven's spouse is Tariq Aziz.",
      "Is Tariq Aziz Sanne Verhoeven's spouse?"],
     "", "RECORD"),
    # -- no-chain controls (no composer frame without a chain) --
    ("b35-spouse-nochain-whose",
     ["Malik Haddad's spouse is Sanne Verhoeven.",
      "Whose spouse is Sanne Verhoeven?"],
     "Malik Haddad's spouse is Sanne Verhoeven.", "CORRECT"),
    ("b36-author-nochain-whatwritten",
     ["Harbor Light's author is Nadia Ferreira.",
      "What has Nadia Ferreira written?"],
     "", "RECORD"),
    # -- uncued relations (no n-hop cue word: guard cannot fire) --
    ("b37-boss-whose",
     ["Dmitri Volkov's boss is Ingrid Johansson.",
      "Ingrid Johansson's boss is Karim Nasser.",
      "Whose boss is Ingrid Johansson?"],
     "", "RECORD"),
    ("b38-mother-whose",
     ["Olivia Bennett's mother is Rosa Jimenez.",
      "Rosa Jimenez's mother is Ingrid Johansson.",
      "Whose mother is Rosa Jimenez?"],
     "", "RECORD"),
    ("b39-friend-whose",
     ["Samuel Okafor's friend is Yuki Tanaka.",
      "Yuki Tanaka's friend is Zara Ahmed.",
      "Whose friend is Yuki Tanaka?"],
     "", "RECORD"),
    # -- multi-word names --
    ("b40-author-multiword-whatwritten",
     ["The Glass Meridian's author is Mary Ellen Carter.",
      "Mary Ellen Carter's author is Jean Paul Sartre.",
      "What has Mary Ellen Carter written?"],
     "", "RECORD"),
    ("b41-spouse-multiword-whose",
     ["Anna Maria Silva's spouse is John Paul Meyer.",
      "John Paul Meyer's spouse is Li Wei Chen.",
      "Whose spouse is John Paul Meyer?"],
     "", "RECORD"),
    # -- my-subject --
    ("b42-my-spouse-whose",
     ["My spouse is Sanne Verhoeven.",
      "Malik Haddad's spouse is Sanne Verhoeven.",
      "Whose spouse is Sanne Verhoeven?"],
     "", "RECORD"),
    # -- abstain controls --
    ("b43-spouse-nomatch",
     ["Malik Haddad's mother is Sanne Verhoeven.",
      "Whose spouse is Sanne Verhoeven?"],
     "", "RECORD"),
    ("b44-author-unknown-value",
     ["Harbor Light's author is Nadia Ferreira.",
      "Whose author is Quinn Faber?"],
     "", "RECORD"),
    # -- statement control (questions never write) --
    ("b45-teach-after-chain",
     ["Malik Haddad's spouse is Sanne Verhoeven.",
      "Sanne Verhoeven's spouse is Tariq Aziz.",
      "Tariq Aziz's spouse is Wren Delacroix."],
     "", "RECORD"),
    ("b46-author-forward-2subj-yn",
     ["The Glass Meridian's author is Felix Wagner.",
      "The Tin Orchard's author is Amara Diallo.",
      "Is Felix Wagner The Glass Meridian's author?"],
     "", "RECORD"),
]

if __name__ == "__main__":
    print(f"dialogs={len(NEW268B)}")
    assert len(NEW268B) >= 40, len(NEW268B)
