#!/usr/bin/env python3
"""Experiment 65, builder: Fable-Edit-200 (seed 6500, fixed).

Reads the downloaded open-licence raw files (MQuAKE-Remastered CC-BY-4.0,
TwoHopFact CC-BY-4.0) and writes data/open/bench65/fable_edit_200.jsonl:

  100 MQuAKE-Remastered CF-3k two-hop SINGLE-edit instances
   50 reversal pairs (25 fictitious facts x both directions, Berglund format)
   50 abstention items (25 absent subject/relation, 25 broken chains)

Every item carries: id, source, type, taught triples (subject, relation,
object) with the ORIGINAL English sentence kept alongside, question, gold
answer(s). Relations are stored both as the original label and as the
normalised notebook key the arm teaches/asks with.

Additive, offline, CPU, stdlib + pyarrow/pandas (read-only on raw files).
CounterFact / zsRE / Reversal-Curse DATA ARE NEVER DOWNLOADED HERE
(licence not found); reversal items are generated by us from fictitious
names, in Berglund's sentence format.
"""

from __future__ import annotations

import hashlib
import json
import random
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "open" / "bench65"
RAW_MQUAKE = DATA / "raw" / "data" / "CF3k-00000-of-00001.parquet"
RAW_TWOHOP = DATA / "raw" / "TwoHopFact.csv"
OUT = DATA / "fable_edit_200.jsonl"

SEED = 6500
N_MQUAKE, N_REV_FACTS, N_ABSENT, N_BROKEN = 100, 25, 25, 25


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def rel_key(label: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", label.strip().lower()).strip("_")


def triple(subj: str, rel_label: str, obj: str, sentence_en: str) -> dict:
    return {"subject": subj, "relation": rel_key(rel_label),
            "relation_label": rel_label, "object": obj,
            "sentence_en": sentence_en}


# ------------------------------------------------------------- name pools
FIRST = ("Uriah Casimar Elowen Thaddeus Marisol Branwen Caspian Delphine "
         "Edmund Fenella Gareth Hester Ivo Jessamine Kellan Linnea Magnus "
         "Nerissa Orson Petra Quillan Rowena Silas Tamora Ulric Vesper "
         "Wren Ysolde Zephyr Anselm Briar Cressida Dunstan Eira Falco "
         "Greta Hadrian Isolde Joren Kira Leander Mirabel Nolan Odette "
         "Percival Rosalind Stellan Tilda Osric Yara Damon").split()
LAST = ("Hawthorne Vell Quill Frostmere Ashdown Blackwood Cinderhall "
        "Driftmere Emberlin Foxglove Grimshaw Holloway Inkwell Juniper "
        "Kingsfoil Larkspur Moonrake Nightingale Owlcrest Pemberton "
        "Quarrybank Ravenhill Stonebridge Thornbury Underbough Vexley "
        "Windrow Yarwood Zanderfield Aldercroft Birchmere Corvane "
        "Dunmore Eldermist Fairwind Gallowglass Harrowgate Ironbark "
        "Kestrelmere Loxley Marshwick Nettlestone Osgood Pikehall "
        "Rookwood Sablemere Tallowmere Umberfold").split()
WORK_ADJ = ("Abyssal Crimson Gilded Hollow Ivory Jagged Lantern Marble "
            "Ninth Obsidian Pearl Quiet Rustic Silver Thorn Umber Velvet "
            "Woven Amber Bleak Copper Dusky Ember Frost Golden Hushed "
            "Iron Lurid Misty Northern Oaken").split()
WORK_NOUN = ("Melodies Chronicles Tapestries Voyages Sonnets Gardens "
             "Lanterns Mirrors Echoes Compasses Bells Maps Thrones Feasts "
             "Bridges Candles Dances Flutes Harbours Journals Keys Looms "
             "Masks Odes Pillars Quilts Rivers Sails Towers Veils Wheels").split()


def make_pools(rng: random.Random):
    persons, works = [], []
    while len(persons) < 400:
        n = f"{rng.choice(FIRST)} {rng.choice(LAST)}"
        if n not in persons:
            persons.append(n)
    while len(works) < 200:
        n = f"{rng.choice(WORK_ADJ)} {rng.choice(WORK_NOUN)}"
        if n not in works:
            works.append(n)
    return persons, works


# ------------------------------------------------------------------ MQuAKE
def L(x):
    if x is None:
        return []
    return [el.tolist() if hasattr(el, "tolist") else el for el in list(x)]


def build_mquake(rng: random.Random):
    import pandas as pd
    df = pd.read_parquet(RAW_MQUAKE)
    elig = []
    for _, r in df.iterrows():
        rew, newt = L(r["requested_rewrite"]), L(r["new_triples"])
        if len(rew) == 1 and len(newt) == 2:
            nt = [list(t) for t in newt]
            if nt[0][2] == nt[1][0] and all(t[0] and t[1] and t[2] for t in nt):
                elig.append(r)
    assert len(elig) >= N_MQUAKE, f"only {len(elig)} eligible single-edit two-hop cases"
    picks = sorted(rng.sample(elig, N_MQUAKE), key=lambda r: int(r["case_id"]))
    items = []
    for k, r in enumerate(picks, 1):
        orig = [list(t) for t in L(r["orig_triples_labeled"])]
        new = [list(t) for t in L(r["new_triples_labeled"])]
        ohops, nhops = L(r["single_hops"]), L(r["new_single_hops"])
        assert len(ohops) == 2 and len(nhops) == 2
        taught = []
        for (s, rl, o), h in zip(orig, ohops):
            taught.append(triple(s, rl, o,
                                 f"{h['cloze']} {h['answer']}".strip()))
        for (s, rl, o), h in zip(new, nhops):
            sent = f"{h['cloze']} {h['answer']}".strip()
            taught.append({**triple(s, rl, o, sent), "edit": True})
        items.append({
            "id": f"bench65-mquake-{k:03d}",
            "source": "mquake-remastered-cf3k",
            "type": "mquake-twohop",
            "case_id": int(r["case_id"]),
            "frame": {"name": new[0][0],
                      "relations": [rel_key(new[0][1]), rel_key(new[1][1])]},
            "taught": taught,
            "question": L(r["questions"])[0],
            "gold": [r["new_answer"]],
            "gold_aliases": L(r["new_answer_alias"]),
            "expected": "answer",
        })
    return items, [int(r["case_id"]) for r in picks]


# ---------------------------------------------------------------- reversal
REV_PAIRS = (
    ("composer of", "composer_of", "composed by", "composed_by"),
    ("author of", "author_of", "written by", "written_by"),
    ("discoverer of", "discoverer_of", "discovered by", "discovered_by"),
    ("founder of", "founder_of", "founded by", "founded_by"),
    ("inventor of", "inventor_of", "invented by", "invented_by"),
)
FWD_TMPL = "{A} is the {R} {B}."
REV_TMPL = "{B} was {Ri} {A}."


def build_reversal(rng: random.Random, persons, works):
    items = []
    for i in range(N_REV_FACTS):
        a = persons[i]
        b = f"{works[i]}"
        rp, rk, rip, rik = REV_PAIRS[i % len(REV_PAIRS)]
        fwd = FWD_TMPL.format(A=a, R=rp, B=b)
        rev = REV_TMPL.format(A=a, B=b, Ri=rip)
        base = {
            "source": "reversal-ours-fictitious",
            "fact_index": i,
            "templates": {"forward": FWD_TMPL, "reverse": REV_TMPL,
                          "relation": [rp, rk], "relation_inverse": [rip, rik]},
            "taught": [triple(a, rp, b, fwd), triple(b, rip, a, rev)],
            "gold": [],
        }
        items.append({**base, "id": f"bench65-rev-f{i:02d}-fwd",
                      "type": "reversal",
                      "frame": {"name": a, "relations": [rk]},
                      "question": f"Who is the {rp} {b}?",
                      "gold": [b], "expected": "answer"})
        items.append({**base, "id": f"bench65-rev-f{i:02d}-rev",
                      "type": "reversal",
                      "frame": {"name": b, "relations": [rik]},
                      "question": f"Who {rip} {b}?",
                      "gold": [a], "expected": "answer"})
    return items


# --------------------------------------------------------------- abstention
ABS_REL = ("apprentice of", "mentor of", "herald of", "warden of",
           "keeper of", "rival of", "scout of", "envoy of")


def build_abstention(rng: random.Random, persons):
    items = []
    pool = persons[50:]
    assert len(pool) >= 250
    # 25 absent: notebook holds filler facts; the asked subject/relation is absent
    for i in range(N_ABSENT):
        f1, f2, f3 = pool[10 * i:10 * i + 3]
        asked = pool[10 * i + 3]
        rel = ABS_REL[i % len(ABS_REL)]
        taught = [
            triple(f1, ABS_REL[(i + 1) % len(ABS_REL)], f2,
                   f"{f1} is the {ABS_REL[(i + 1) % len(ABS_REL)]} {f2}."),
            triple(f2, ABS_REL[(i + 2) % len(ABS_REL)], f3,
                   f"{f2} is the {ABS_REL[(i + 2) % len(ABS_REL)]} {f3}."),
        ]
        if i % 2 == 0:  # unknown subject entirely
            frame = {"name": asked, "relations": [rel_key(rel)]}
            q = f"Who is the {rel} {asked}?"
        else:  # known subject, untaught relation
            frame = {"name": f1, "relations": [f"never_taught_rel_{i}"]}
            q = f"What is the never-taught relation {i} of {f1}?"
        items.append({"id": f"bench65-abs-absent-{i:02d}",
                      "source": "abstention-ours-fictitious",
                      "type": "abstain-absent",
                      "frame": frame, "taught": taught, "question": q,
                      "gold": [], "gold_aliases": [], "expected": "abstain"})
    # 25 broken chains: first hop taught (entity-valued), second hop untaught
    for i in range(N_BROKEN):
        a, b = pool[250 + 2 * i], pool[250 + 2 * i + 1]
        r1 = ABS_REL[i % len(ABS_REL)]
        r2 = f"never_taught_rel_b{i}"
        taught = [triple(a, r1, b, f"{a} is the {r1} {b}.")]
        items.append({"id": f"bench65-abs-broken-{i:02d}",
                      "source": "abstention-ours-fictitious",
                      "type": "abstain-broken",
                      "frame": {"name": a,
                                "relations": [rel_key(r1), r2]},
                      "taught": taught,
                      "question": f"What is the never-taught relation of the {r1} {a}?",
                      "gold": [], "gold_aliases": [], "expected": "abstain"})
    return items


def main() -> int:
    rng = random.Random(SEED)
    for p in (RAW_MQUAKE, RAW_TWOHOP):
        if not p.exists():
            print(f"MISSING raw file: {p}", file=sys.stderr)
            return 2
    persons, works = make_pools(rng)
    mquake, case_ids = build_mquake(rng)
    rev = build_reversal(rng, persons, works)
    abst = build_abstention(rng, persons)
    items = mquake + rev + abst
    assert len(items) == 200, len(items)
    assert len({it["id"] for it in items}) == 200
    DATA.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        for it in items:
            fh.write(json.dumps(it, ensure_ascii=False, sort_keys=True) + "\n")
    manifest = {
        "seed": SEED,
        "counts": {"mquake-twohop": len(mquake), "reversal": len(rev),
                   "abstain-absent": N_ABSENT, "abstain-broken": N_BROKEN},
        "mquake_case_ids": case_ids,
        "raw": {p.name: {"path": str(p.relative_to(ROOT)),
                         "sha256": sha256_of(p),
                         "bytes": p.stat().st_size} for p in (RAW_MQUAKE, RAW_TWOHOP)},
        "out": {"path": str(OUT.relative_to(ROOT)),
                "sha256": sha256_of(OUT), "bytes": OUT.stat().st_size},
    }
    (DATA / "fable_bench65_build_manifest.json").write_text(
        json.dumps(manifest, indent=1) + "\n", encoding="utf-8")
    print(json.dumps({k: v for k, v in manifest.items() if k != "mquake_case_ids"},
                     indent=1))
    print("mquake_case_ids:", case_ids)
    return 0


if __name__ == "__main__":
    sys.exit(main())
