#!/usr/bin/env python3
"""Experiment 92, builder: Fable-Edit-SCALE (seed 9200, fixed).

Reads the SAME downloaded open-licence raw file as exp 65
(MQuAKE-Remastered CC-BY-4.0 CF-3k parquet; TwoHopFact is hash-recorded
but not sampled, exactly as in bench65) and writes data/open/bench92/:

  S1 fable_edit92_s1_3hop.jsonl       3-hop single-edit (up to 200)
  S2 fable_edit92_s2_4hop.jsonl       4-hop single-edit (up to 200)
  S3 fable_edit92_s3_multiedit.jsonl  multi-edit, 2-4 edits, same chain (up to 200)
  S4 fable_edit92_s4_batch.jsonl      all 1,000 chain-linked 2-hop cases (batch test)
  S5 fable_edit92_s5_conflict.jsonl   conflicting edits: source edit then an
                                      override back to the ORIGINAL value
                                      (latest must win; gold = orig answer)
  S6 fable_edit92_s6_rev3hop.jsonl    reversal at 3 hops, ours-fictitious
                                      (100 chains x fwd/rev = 200 items)

Never invents MQuAKE items: every S1-S5 triple/sentence comes from the
source parquet; S5's "second edit" re-uses the case's own ORIGINAL triple
value (a revert). S6 is generated by us from fictitious names (no real
person or fact), like exp 65's reversal half.

Additive, offline, CPU, stdlib + pandas/pyarrow (read-only on raw files).

Run with:
  export OMP_NUM_THREADS=1 MKL_NUM_THREADS=1
  uv run --offline --no-project --python 3.12 --with pandas --with pyarrow \\
    python -B scripts/fable_bench92_build.py
"""

from __future__ import annotations

import hashlib
import json
import random
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA65 = ROOT / "data" / "open" / "bench65"
DATA = ROOT / "data" / "open" / "bench92"
RAW_MQUAKE = DATA65 / "raw" / "data" / "CF3k-00000-of-00001.parquet"
RAW_TWOHOP = DATA65 / "raw" / "TwoHopFact.csv"

SEED = 9200
N_S1, N_S2, N_S3, N_S5 = 200, 200, 200, 200
# S3 stratification over (hops, n_edits): sums to 200
S3_PLAN = {(2, 2): 60, (3, 2): 40, (3, 3): 40, (4, 2): 20, (4, 3): 20, (4, 4): 20}


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def rel_key(label: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", label.strip().lower()).strip("_")


def triple(subj: str, rel_label: str, obj: str, sentence_en: str) -> dict:
    return {"subject": subj, "relation": rel_key(rel_label),
            "relation_label": rel_label, "object": obj,
            "sentence_en": sentence_en}


def L(x):
    if x is None:
        return []
    return [el.tolist() if hasattr(el, "tolist") else el for el in list(x)]


def chain_linked(newt: list[list]) -> bool:
    if not all(t[0] and t[1] and t[2] for t in newt):
        return False
    return all(newt[i][2] == newt[i + 1][0] for i in range(len(newt) - 1))


def mquake_item(r, tag: str, k: int, extra: dict | None = None) -> dict:
    orig = [list(t) for t in L(r["orig_triples_labeled"])]
    new = [list(t) for t in L(r["new_triples_labeled"])]
    ohops, nhops = L(r["single_hops"]), L(r["new_single_hops"])
    assert len(orig) == len(ohops) == len(new) == len(nhops)
    taught = []
    for (s, rl, o), h in zip(orig, ohops):
        taught.append(triple(s, rl, o, f"{h['cloze']} {h['answer']}".strip()))
    for (s, rl, o), h in zip(new, nhops):
        sent = f"{h['cloze']} {h['answer']}".strip()
        taught.append({**triple(s, rl, o, sent), "edit": True})
    item = {
        "id": f"bench92-{tag}-{k:03d}",
        "source": "mquake-remastered-cf3k",
        "type": f"mquake-{tag}",
        "case_id": int(r["case_id"]),
        "frame": {"name": new[0][0],
                  "relations": [rel_key(t[1]) for t in new]},
        "taught": taught,
        "question": L(r["questions"])[0],
        "gold": [r["new_answer"]],
        "gold_aliases": L(r["new_answer_alias"]),
        "expected": "answer",
    }
    if extra:
        item.update(extra)
    return item


# ------------------------------------------------------------- name pools (S6)
FIRST = ("Uriah Casimar Elowen Thaddeus Marisol Branwen Caspian Delphine "
         "Edmund Fenella Gareth Hester Ivo Jessamine Kellan Linnea Magnus "
         "Nerissa Orson Petra Quillan Rowena Silas Tamora Ulric Vesper "
         "Wren Ysolde Zephyr Anselm Briar Cressida Dunstan Eira Falco "
         "Greta Hadrian Isolde Joren Kira Leander Mirabel Nolan Odette "
         "Percival Rosalind Stellan Tilda Osric Yara Damon").split()
LAST = ("Hawthorne Vell Quill Frostmere Ashdown Blackwood Cinderhall "
        "Driftmere Emberlin Foxglove Grimshaw Holloway Inkwell Juniper "
        "Kingsfoil Larkspur Moonrake Nightingale Owlcrest Pemberton "
        "Quarrybank Ravenhill Stonebridge Thornbury Underbough Vexley "
        "Windrow Yarwood Zanderfield Aldercroft Birchmere Corvane "
        "Dunmore Eldermist Fairwind Gallowglass Harrowgate Ironbark "
        "Kestrelmere Loxley Marshwick Nettlestone Osgood Pikehall "
        "Rookwood Sablemere Tallowmere Umberfold").split()
WORK_ADJ = ("Abyssal Crimson Gilded Hollow Ivory Jagged Lantern Marble "
            "Ninth Obsidian Pearl Quiet Rustic Silver Thorn Umber Velvet "
            "Woven Amber Bleak Copper Dusky Ember Frost Golden Hushed "
            "Iron Lurid Misty Northern Oaken").split()
WORK_NOUN = ("Melodies Chronicles Tapestries Voyages Sonnets Gardens "
             "Lanterns Mirrors Echoes Compasses Bells Maps Thrones Feasts "
             "Bridges Candles Dances Flutes Harbours Journals Keys Looms "
             "Masks Odes Pillars Quilts Rivers Sails Towers Veils Wheels").split()

REV_PAIRS = (
    ("composer of", "composer_of", "composed by", "composed_by"),
    ("author of", "author_of", "written by", "written_by"),
    ("discoverer of", "discoverer_of", "discovered by", "discovered_by"),
    ("founder of", "founder_of", "founded by", "founded_by"),
    ("inventor of", "inventor_of", "invented by", "invented_by"),
)
FWD_TMPL = "{A} is the {R} {B}."
REV_TMPL = "{B} was {Ri} {A}."


def build_s6(rng: random.Random):  # noqa: ARG001 (deterministic pools)
    persons, works = [], []
    r2 = random.Random(SEED + 6)
    while len(persons) < 400:
        n = f"{r2.choice(FIRST)} {r2.choice(LAST)}"
        if n not in persons:
            persons.append(n)
    while len(works) < 300:
        n = f"{r2.choice(WORK_ADJ)} {r2.choice(WORK_NOUN)}"
        if n not in works:
            works.append(n)
    items = []
    for i in range(100):
        a, b, c, d = persons[4 * i:4 * i + 4]
        trio = [REV_PAIRS[(i + j) % len(REV_PAIRS)] for j in range(3)]
        taught, fwd_rels, rev_rels = [], [], []
        nodes = [a, b, c, d]
        for j, (rp, rk, rip, rik) in enumerate(trio):
            x, y = nodes[j], nodes[j + 1]
            taught.append(triple(x, rp, y, FWD_TMPL.format(A=x, R=rp, B=y)))
            taught.append(triple(y, rip, x, REV_TMPL.format(A=x, B=y, Ri=rip)))
            fwd_rels.append(rk)
            rev_rels.append(rik)
        rev_rels = rev_rels[::-1]
        base = {
            "source": "reversal-ours-fictitious-3hop",
            "fact_index": i,
            "taught": taught,
            "gold": [],
        }
        items.append({**base, "id": f"bench92-s6-f{i:02d}-fwd",
                       "type": "reversal-3hop",
                       "frame": {"name": a, "relations": fwd_rels},
                       "question": f"fwd-chain-{i}",
                       "gold": [d], "expected": "answer"})
        items.append({**base, "id": f"bench92-s6-f{i:02d}-rev",
                       "type": "reversal-3hop",
                       "frame": {"name": d, "relations": rev_rels},
                       "question": f"rev-chain-{i}",
                       "gold": [a], "expected": "answer"})
    return items


def main() -> int:
    rng = random.Random(SEED)
    for p in (RAW_MQUAKE, RAW_TWOHOP):
        if not p.exists():
            print(f"MISSING raw file: {p}", file=sys.stderr)
            return 2
    import pandas as pd
    df = pd.read_parquet(RAW_MQUAKE)

    buckets: dict[tuple[int, int], list] = {}
    for _, r in df.iterrows():
        rew, newt = L(r["requested_rewrite"]), L(r["new_triples"])
        nh = L(r["new_single_hops"])
        if len(nh) != len(newt) or not chain_linked([list(t) for t in newt]):
            continue
        buckets.setdefault((len(nh), len(rew)), []).append(r)

    def pick(bucket, n, tag):
        elig = buckets.get(bucket, [])
        assert len(elig) >= n, f"{tag}: only {len(elig)} eligible, need {n}"
        return sorted(rng.sample(elig, n), key=lambda r: int(r["case_id"]))

    s1 = [mquake_item(r, "s1-3hop", k + 1)
          for k, r in enumerate(pick((3, 1), N_S1, "S1"))]
    s2 = [mquake_item(r, "s2-4hop", k + 1)
          for k, r in enumerate(pick((4, 1), N_S2, "S2"))]
    s3 = []
    k = 0
    for (hops, ned), n in sorted(S3_PLAN.items()):
        for r in pick((hops, ned), n, f"S3{(hops, ned)}"):
            k += 1
            s3.append(mquake_item(r, "s3-multiedit", k, extra={
                "id": f"bench92-s3-multiedit-{k:03d}",
                "n_edits": ned, "hops": hops}))
    # S4: every chain-linked 2-hop case (single + multi edit), case_id order
    s4rows = sorted(buckets.get((2, 1), []) + buckets.get((2, 2), []),
                    key=lambda r: int(r["case_id"]))
    assert len(s4rows) == 1000, f"S4: {len(s4rows)} != 1000"
    s4 = [mquake_item(r, "s4-batch", k + 1) for k, r in enumerate(s4rows)]
    # S5: conflicting edits — source edit, then override to ORIGINAL value
    s5 = []
    for k, r in enumerate(pick((2, 1), N_S5, "S5"), 1):
        item = mquake_item(r, "s5-conflict", k)
        orig = [list(t) for t in L(r["orig_triples_labeled"])]
        new = [list(t) for t in L(r["new_triples_labeled"])]
        ohops = L(r["single_hops"])
        # the overridden triple: first new triple whose (subj, rel) differs
        # in object from the original at the same position
        over = None
        for (os_, orl, oo), (ns, nrl, no) in zip(orig, new):
            if os_ == ns and rel_key(orl) == rel_key(nrl) and oo != no:
                over = (ns, nrl, oo)
                break
        assert over is not None, f"S5 case {r['case_id']}: no changed slot"
        ns, nrl, _ = over
        oo = next(o for (s, rl, o) in orig
                  if s == ns and rel_key(rl) == rel_key(nrl))
        oh = next(h for (s, rl, o), h in zip(orig, ohops)
                  if s == ns and rel_key(rl) == rel_key(nrl))
        sent = f"{oh['cloze']} {oh['answer']}".strip()
        item["taught"].append({**triple(ns, nrl, oo, sent),
                               "edit": True, "override": True})
        item["gold"] = [r["answer"]]
        item["gold_aliases"] = L(r["answer_alias"])
        item["id"] = f"bench92-s5-conflict-{k:03d}"
        item["type"] = "mquake-s5-conflict"
        s5.append(item)
    s6 = build_s6(rng)

    DATA.mkdir(parents=True, exist_ok=True)
    splits = {"fable_edit92_s1_3hop.jsonl": s1,
              "fable_edit92_s2_4hop.jsonl": s2,
              "fable_edit92_s3_multiedit.jsonl": s3,
              "fable_edit92_s4_batch.jsonl": s4,
              "fable_edit92_s5_conflict.jsonl": s5,
              "fable_edit92_s6_rev3hop.jsonl": s6}
    manifest = {"seed": SEED, "splits": {}}
    for fname, items in splits.items():
        assert len({it["id"] for it in items}) == len(items), fname
        out = DATA / fname
        with open(out, "w", encoding="utf-8") as fh:
            for it in items:
                fh.write(json.dumps(it, ensure_ascii=False, sort_keys=True)
                         + "\n")
        manifest["splits"][fname] = {
            "n": len(items), "sha256": sha256_of(out),
            "bytes": out.stat().st_size}
        print(f"{fname}: n={len(items)}")
    manifest["raw"] = {
        p.name: {"sha256": sha256_of(p), "bytes": p.stat().st_size}
        for p in (RAW_MQUAKE, RAW_TWOHOP)}
    manifest["s3_plan"] = {f"{h}hop-{e}ed": n
                           for (h, e), n in sorted(S3_PLAN.items())}
    (DATA / "fable_bench92_build_manifest.json").write_text(
        json.dumps(manifest, indent=1) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
