"""Exp 97 (independent panel for the exp-63 relation canonicalizer).

BLIND panel: written WITHOUT opening scripts/fable_relcanon63_canon.py,
scripts/fable_relcanon63_testdata.py, any alias/denylist table, or exp-63's
test JSONs. Only inputs: the 60 canonical relation names (+PIDs) and their
plain Wikidata descriptions.

Regenerates (byte-identical):
  artifacts/fable-relcanon97-20260921/test_paraphrases.json  (300 items)
  artifacts/fable-relcanon97-20260921/test_fabricated.json   (150 items)
  artifacts/fable-relcanon97-20260921/test_nearmiss.json     (50 items)

Stdlib only. Never imports canon().
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTDIR = ROOT / "artifacts" / "fable-relcanon97-20260921"

# (phrase, gold canonical WebRED name). 5 per relation x 60 = 300.
PARAPHRASES: list[tuple[str, str]] = [
    ("country it sits in is", "country"),
    ("lies in the country of", "country"),
    ("is in the nation of", "country"),
    ("sits inside the state of", "country"),
    ("is located in the country of", "country"),
    ("has diplomatic ties with", "diplomatic relation"),
    ("keeps an embassy open in", "diplomatic relation"),
    ("holds formal relations with", "diplomatic relation"),
    ("exchanges ambassadors with", "diplomatic relation"),
    ("maintains ties of diplomacy with", "diplomatic relation"),
    ("lies inside the district of", "located in the administrative territorial entity"),
    ("sits in the borough of", "located in the administrative territorial entity"),
    ("is in the county of", "located in the administrative territorial entity"),
    ("falls under the province of", "located in the administrative territorial entity"),
    ("is within the municipality of", "located in the administrative territorial entity"),
    ("borders on", "shares border with"),
    ("shares a frontier with", "shares border with"),
    ("has a common border with", "shares border with"),
    ("adjoins directly", "shares border with"),
    ("is bordered by", "shares border with"),
    ("is split into districts of", "contains administrative territorial entity"),
    ("has as a subdivision", "contains administrative territorial entity"),
    ("contains the province of", "contains administrative territorial entity"),
    ("is made of counties like", "contains administrative territorial entity"),
    ("covers the region of", "contains administrative territorial entity"),
    ("holds citizenship of", "country of citizenship"),
    ("is a citizen of", "country of citizenship"),
    ("carries the passport of", "country of citizenship"),
    ("is a national of", "country of citizenship"),
    ("has the nationality of", "country of citizenship"),
    ("has as its capital", "capital"),
    ("whose capital is", "capital"),
    ("with capital city", "capital"),
    ("capital city being", "capital"),
    ("has its seat of government at", "capital"),
    ("is headquartered in", "headquarters location"),
    ("has its head office in", "headquarters location"),
    ("bases its HQ at", "headquarters location"),
    ("main office sits in", "headquarters location"),
    ("is run from offices in", "headquarters location"),
    ("serves as capital to", "capital of"),
    ("is capital city of", "capital of"),
    ("is the seat of government for", "capital of"),
    ("is the administrative centre of", "capital of"),
    ("does duty as capital of", "capital of"),
    ("prices are rising at", "inflation rate"),
    ("inflation runs at", "inflation rate"),
    ("the CPI is up by", "inflation rate"),
    ("the cost of living climbs at", "inflation rate"),
    ("shop prices grow at", "inflation rate"),
    ("plays for the side", "member of sports team"),
    ("is on the books of the club", "member of sports team"),
    ("turns out for the team", "member of sports team"),
    ("is signed to the squad", "member of sports team"),
    ("represents the club", "member of sports team"),
    ("includes as a part", "has part"),
    ("has as a component", "has part"),
    ("is composed of", "has part"),
    ("comprises the section", "has part"),
    ("contains as a division", "has part"),
    ("has oxidation number", "oxidation state"),
    ("oxidation level of", "oxidation state"),
    ("takes the oxidation value of", "oxidation state"),
    ("shows an oxidation state of", "oxidation state"),
    ("has an oxidation number of", "oxidation state"),
    ("forms part of", "part of"),
    ("is a section of", "part of"),
    ("is a component of", "part of"),
    ("belongs as a piece to", "part of"),
    ("is a division of", "part of"),
    ("is on the continent of", "continent"),
    ("lies within the continent of", "continent"),
    ("belongs to the continent of", "continent"),
    ("sits on the continent of", "continent"),
    ("is situated in the continent of", "continent"),
    ("is married to", "spouse"),
    ("is wedded to", "spouse"),
    ("took as a spouse", "spouse"),
    ("is the husband of", "spouse"),
    ("is the wife of", "spouse"),
    ("was born in the village of", "place of birth"),
    ("first saw light in", "place of birth"),
    ("birthplace is", "place of birth"),
    ("entered the world in", "place of birth"),
    ("was delivered in", "place of birth"),
    ("belongs to the party", "member of political party"),
    ("is a card-carrying member of", "member of political party"),
    ("sits for the party", "member of political party"),
    ("joined the party", "member of political party"),
    ("is affiliated with the party", "member of political party"),
    ("belongs to the society", "member of"),
    ("holds membership of the club", "member of"),
    ("is enrolled in the association", "member of"),
    ("is on the roll of the group", "member of"),
    ("is a fellow of the society", "member of"),
    ("is performed by", "performer"),
    ("was performed by", "performer"),
    ("has as its performer", "performer"),
    ("was sung by", "performer"),
    ("was played by the musician", "performer"),
    ("is owned by", "owned by"),
    ("is the property of", "owned by"),
    ("belongs to as property", "owned by"),
    ("is held by its owner", "owned by"),
    ("ownership rests with", "owned by"),
    ("was born on the date", "date of birth"),
    ("birthday falls on", "date of birth"),
    ("date of birth is", "date of birth"),
    ("was born on the day of", "date of birth"),
    ("birth date reads", "date of birth"),
    ("codes for the protein", "encodes"),
    ("carries the code for", "encodes"),
    ("gives rise to the protein", "encodes"),
    ("is the gene behind", "encodes"),
    ("produces the protein", "encodes"),
    ("stars in the cast of", "cast member"),
    ("appears in the cast of", "cast member"),
    ("is billed in the cast of", "cast member"),
    ("plays a part in the film", "cast member"),
    ("is credited in the cast of", "cast member"),
    ("comes from the country of", "country of origin"),
    ("originates in the land of", "country of origin"),
    ("is a product of the nation", "country of origin"),
    ("hails from the country of", "country of origin"),
    ("was first made in the land of", "country of origin"),
    ("died in the town of", "place of death"),
    ("passed away at", "place of death"),
    ("breathed last in", "place of death"),
    ("met death in", "place of death"),
    ("death place is", "place of death"),
    ("works for the firm", "employer"),
    ("is employed by", "employer"),
    ("is on the payroll of", "employer"),
    ("does shifts for", "employer"),
    ("earns a wage from", "employer"),
    ("was formed in the city", "location of formation"),
    ("came together in", "location of formation"),
    ("first got together in", "location of formation"),
    ("started out in", "location of formation"),
    ("first met in", "location of formation"),
    ("owns outright", "owner of"),
    ("is the owner of", "owner of"),
    ("holds the deeds to", "owner of"),
    ("has in its portfolio", "owner of"),
    ("is proprietor of", "owner of"),
    ("wrote the book", "author"),
    ("is the author of", "author"),
    ("penned the novel", "author"),
    ("authored the piece", "author"),
    ("is credited as writer of", "author"),
    ("has as its official tongue", "official language"),
    ("uses officially", "official language"),
    ("recognises as official", "official language"),
    ("does business officially in", "official language"),
    ("is administered in", "official language"),
    ("plays in the division", "league"),
    ("competes in the competition", "league"),
    ("turns out in the league", "league"),
    ("takes part in the tournament", "league"),
    ("is in the top flight of", "league"),
    ("is run by", "operator"),
    ("is operated by", "operator"),
    ("is managed as a service by", "operator"),
    ("the enterprise behind it is", "operator"),
    ("is kept going by", "operator"),
    ("went to school at", "educated at"),
    ("studied at the college", "educated at"),
    ("attended the academy", "educated at"),
    ("was schooled at", "educated at"),
    ("read history at", "educated at"),
    ("joblessness stands at", "unemployment rate"),
    ("share out of work is", "unemployment rate"),
    ("unemployment sits at", "unemployment rate"),
    ("portion without jobs is", "unemployment rate"),
    ("out-of-work rate is", "unemployment rate"),
    ("was set up by", "founded by"),
    ("was started by", "founded by"),
    ("was launched by", "founded by"),
    ("owes its founding to", "founded by"),
    ("was established by", "founded by"),
    ("has as prime minister", "head of government"),
    ("is led by the premier", "head of government"),
    ("has as chancellor", "head of government"),
    ("is governed by the first minister", "head of government"),
    ("premiership is held by", "head of government"),
    ("is sited at", "location"),
    ("stands at the spot", "location"),
    ("is found at", "location"),
    ("happened at", "location"),
    ("takes place at", "location"),
    ("has as its parent body", "parent organization"),
    ("answers to the parent group", "parent organization"),
    ("is a branch of the wider group", "parent organization"),
    ("comes under the head organisation", "parent organization"),
    ("is a unit of the parent firm", "parent organization"),
    ("school becomes compulsory at age", "compulsory education (minimum age)"),
    ("kids must start school at", "compulsory education (minimum age)"),
    ("compulsory schooling begins at", "compulsory education (minimum age)"),
    ("schooling is mandatory from age", "compulsory education (minimum age)"),
    ("children must enter school at", "compulsory education (minimum age)"),
    ("came into being in", "inception"),
    ("dates back to", "inception"),
    ("originated in the year", "inception"),
    ("was created back in", "inception"),
    ("got its start in", "inception"),
    ("holds as law in", "applies to jurisdiction"),
    ("is enforced across", "applies to jurisdiction"),
    ("applies within the territory", "applies to jurisdiction"),
    ("covers legally", "applies to jurisdiction"),
    ("is on the books in", "applies to jurisdiction"),
    ("died on the day", "date of death"),
    ("passed on the date", "date of death"),
    ("death date reads", "date of death"),
    ("lost life on", "date of death"),
    ("drew last breath on", "date of death"),
    ("is grouped under the family", "parent taxon"),
    ("falls within the order", "parent taxon"),
    ("belongs to the genus", "parent taxon"),
    ("sits in the family", "parent taxon"),
    ("is classed in the taxon", "parent taxon"),
    ("was developed by", "developer"),
    ("was built by the studio", "developer"),
    ("was made by the developer", "developer"),
    ("comes from the software house", "developer"),
    ("was coded by", "developer"),
    ("was followed by", "followed by"),
    ("was succeeded by", "followed by"),
    ("gave way next to", "followed by"),
    ("had as its successor", "followed by"),
    ("next up after it was", "followed by"),
    ("is twinned with", "twinned administrative body"),
    ("has as its twin town", "twinned administrative body"),
    ("is a sister city of", "twinned administrative body"),
    ("is paired in friendship with", "twinned administrative body"),
    ("holds a twinning link with", "twinned administrative body"),
    ("is famed for", "notable work"),
    ("best-known work is", "notable work"),
    ("made a name with", "notable work"),
    ("is remembered for", "notable work"),
    ("signature piece is", "notable work"),
    ("is a type of", "subclass of"),
    ("is a kind of", "subclass of"),
    ("counts as a subtype of", "subclass of"),
    ("falls in the class of", "subclass of"),
    ("is a variety of", "subclass of"),
    ("has as its subsidiary", "subsidiary"),
    ("runs a subordinate outfit", "subsidiary"),
    ("owns the daughter firm", "subsidiary"),
    ("controls the child company", "subsidiary"),
    ("has a spin-off unit under it", "subsidiary"),
    ("sits beside the lake", "located in or next to body of water"),
    ("stands on the shore of", "located in or next to body of water"),
    ("lies on the banks of", "located in or next to body of water"),
    ("is on the coast of", "located in or next to body of water"),
    ("looks over the bay of", "located in or next to body of water"),
    ("can speak the tongue", "languages spoken, written or signed"),
    ("is fluent in", "languages spoken, written or signed"),
    ("chats in", "languages spoken, written or signed"),
    ("writes in", "languages spoken, written or signed"),
    ("uses at home", "languages spoken, written or signed"),
    ("comes after", "follows"),
    ("comes right after", "follows"),
    ("is next after", "follows"),
    ("takes over from in the list", "follows"),
    ("succeeds in the running order", "follows"),
    ("serves as president of", "head of state"),
    ("reigns as monarch over", "head of state"),
    ("holds the presidency of", "head of state"),
    ("is the ceremonial head of", "head of state"),
    ("is king over", "head of state"),
    ("is mum to", "child"),
    ("is dad to", "child"),
    ("has as a son", "child"),
    ("is the father of", "child"),
    ("is the parent of", "child"),
    ("was directed by", "director"),
    ("had as director", "director"),
    ("was helmed by", "director"),
    ("was shot by the filmmaker", "director"),
    ("direction was by", "director"),
    ("has a day-long exposure cap of", "time-weighted average exposure limit"),
    ("safe shift dose is", "time-weighted average exposure limit"),
    ("workers can face at most", "time-weighted average exposure limit"),
    ("exposure ceiling at work is", "time-weighted average exposure limit"),
    ("allowed dose over the shift is", "time-weighted average exposure limit"),
    ("takes its name from", "named after"),
    ("is named for", "named after"),
    ("owes its name to", "named after"),
    ("was christened after", "named after"),
    ("borrows its name from", "named after"),
    ("plays internationally for", "country for sport"),
    ("turns out for the national side of", "country for sport"),
    ("represents at sport", "country for sport"),
    ("wears the national shirt of", "country for sport"),
    ("is capped by the country", "country for sport"),
    ("was crafted by", "creator"),
    ("was made by the maker", "creator"),
    ("is the creation of", "creator"),
    ("was dreamed up by", "creator"),
    ("was put together by", "creator"),
]

# Fabricated everyday phrases naming no Wikidata relation (gold UNKNOWN).
FABRICATED: list[str] = [
    "had chips with",
    "shared chips with",
    "burnt the toast for",
    "pinched a chip from",
    "licked the spoon for",
    "made a brew for",
    "poured a cuppa for",
    "saved the last biscuit for",
    "argued over the last slice with",
    "did the washing-up for",
    "dried the dishes with",
    "peeled the spuds with",
    "stirred the gravy for",
    "fetched the milk for",
    "left the crusts for",
    "waved across the street to",
    "shouted hello to",
    "blew a kiss to",
    "nodded good morning to",
    "tipped a hat to",
    "shook hands with",
    "hugged goodbye to",
    "waved off at the stop with",
    "saw to the gate with",
    "walked to the corner with",
    "waited at the shelter with",
    "shared a brolly with",
    "got soaked beside",
    "sheltered with",
    "dripped all over",
    "texted goodnight to",
    "rang for a natter with",
    "left a voicemail for",
    "sent a postcard to",
    "scribbled a note for",
    "slipped a note under the door of",
    "emailed the photos to",
    "forwarded the meme to",
    "liked the photo of",
    "commented under the snap of",
    "tagged in the group snap",
    "hearted the message of",
    "saved a seat for",
    "sat opposite on the bus to",
    "queued behind",
    "waved through in the queue",
    "missed the bus with",
    "caught the early train with",
    "stood all the way with",
    "gave up a seat for",
    "squeezed up for",
    "shared the armrest with",
    "tapped off beside",
    "waited three stops with",
    "had a row with",
    "fell out over the remote with",
    "made it up with",
    "said sorry first to",
    "forgave the dent in the car of",
    "laughed it off with",
    "sulked till teatime with",
    "slammed the door on",
    "made peace over chips with",
    "agreed to disagree with",
    "shook on it with",
    "sneezed all over",
    "coughed beside",
    "snored next to",
    "trod on the toes of",
    "stood on the foot of",
    "brushed past",
    "bumped trolleys with",
    "nudged gently",
    "yawned through the meeting with",
    "hiccuped beside",
    "shivered beside",
    "dreamt about",
    "had a nightmare featuring",
    "woke grinning about",
    "felt chuffed for",
    "felt gutted for",
    "was cross about the queue with",
    "fretted over the bill with",
    "gloated gently over",
    "cheered up with a brew for",
    "sat quiet beside",
    "gazed out the window with",
    "hummed in the queue with",
    "lent the mower to",
    "brought the ladder round for",
    "returned the shears to",
    "posted the parcel for",
    "queued at the parcel counter with",
    "carried the bags for",
    "held the ladder for",
    "passed the spanner to",
    "fetched the paper for",
    "watered the tomatoes of",
    "fed the neighbour's cat for",
    "took in the parcel for",
    "got rained off with",
    "waited out the shower with",
    "slipped on the ice beside",
    "crunched through the frost with",
    "paddled beside",
    "skimmed stones with",
    "flew a kite with",
    "chased a hat for",
    "lost a hat with",
    "shared the shade with",
    "sipped water beside",
    "fanned with the menu for",
    "laughed at the joke of",
    "groaned at the pun of",
    "retold the gossip to",
    "swore to keep the secret of",
    "kept schtum for",
    "spilled the beans to",
    "put the kettle on for",
    "nattered over the fence with",
    "gossiped over chips with",
    "moaned about the traffic with",
    "bragged about the tomatoes to",
    "shared the holiday snaps with",
    "dreamt the same dream as",
    "sneezed in threes with",
    "snored in harmony with",
    "sleepwalked past",
    "talked in sleep beside",
    "hogged the duvet from",
    "stole the pillow of",
    "set two alarms for",
    "hit snooze with",
    "made the morning pot for",
    "buttered soldiers for",
    "cut the toast into soldiers for",
    "counted sheep with",
    "shared the blanket with",
    "argued over the thermostat with",
    "hogged the remote from",
    "fought over the window seat with",
    "raced to the gate with",
    "slogged through the mud with",
    "paddled in the shallows with",
    "built a snowman with",
    "had a snowball fight with",
    "came in from the cold with",
    "warmed hands beside",
    "shared the thermos with",
    "poured a second cup for",
]

# (phrase, gold canonical name or UNKNOWN, why it is a trap).
NEAR_MISS: list[tuple[str, str, str]] = [
    ("is the capital city of", "capital of", "surface resembles 'capital' but direction is capital-of"),
    ("has as its capital city", "capital", "surface resembles 'capital of' but direction is capital"),
    ("a capital idea", "UNKNOWN", "idiom; resembles 'capital'"),
    ("was born in the town of", "place of birth", "born-frame trap vs date of birth"),
    ("was born on the morning of", "date of birth", "born-frame trap vs place of birth"),
    ("died in the city of", "place of death", "death-frame trap vs date of death"),
    ("died on the date of", "date of death", "death-frame trap vs place of death"),
    ("walked down the aisle with", "spouse", "wedding frame without the word married"),
    ("got married in the chapel at", "UNKNOWN", "states the venue, not the spouse"),
    ("is engaged to", "UNKNOWN", "unmarried partner; resembles spouse"),
    ("is the mother of", "child", "parent word, child direction"),
    ("mothers the toddler", "child", "verb form of mother, child direction"),
    ("fathers a son", "child", "verb form of father, child direction"),
    ("was followed by the sequel", "followed by", "passive follow frame"),
    ("comes just before the finale", "followed by", "before-phrasing means followed-by"),
    ("comes just after the opener", "follows", "after-phrasing means follows"),
    ("is next in the list after", "follows", "next-after means follows"),
    ("is next in the list before", "followed by", "next-before means followed-by"),
    ("owns the corner shop", "owner of", "own-frame, owner direction"),
    ("is owned by the corner shop", "owned by", "own-frame, owned direction"),
    ("belongs to the landlord", "owned by", "belong-frame means owned-by, not member-of"),
    ("includes the appendix as a part", "has part", "whole-to-part direction"),
    ("is included as a part of", "part of", "part-to-whole direction"),
    ("is a member of the first team", "member of sports team", "member subtype trap"),
    ("is a member of the local party branch", "member of political party", "member subtype trap"),
    ("is a member of the choir", "member of", "musical group, generic member-of"),
    ("runs the ferry crossing", "operator", "run-frame vs head-of-government"),
    ("runs the country day to day", "head of government", "run-frame vs operator"),
    ("school of fish", "UNKNOWN", "school as shoal; resembles educated-at"),
    ("wrote the screenplay for", "author", "write-frame vs creator/developer"),
    ("dreamed up the character for", "creator", "create-frame vs author"),
    ("built the game engine for", "developer", "build-frame vs creator/founded-by"),
    ("was behind the camera on", "director", "film frame vs performer/cast"),
    ("works the tills for", "employer", "work-frame vs owner-of"),
    ("set the firm up", "founded by", "setup frame vs inception year"),
    ("got the firm going in the year", "inception", "year frame vs founded-by person"),
    ("sits in the county", "located in the administrative territorial entity", "in-frame vs contains/border"),
    ("covers the county", "contains administrative territorial entity", "cover-frame vs located-in"),
    ("touches the county line", "shares border with", "touch-frame vs located-in"),
    ("lies within the nation of", "country", "nation-frame vs citizenship/origin"),
    ("votes as a citizen of", "country of citizenship", "citizen-frame vs country/origin"),
    ("was first brewed in the land of", "country of origin", "origin-frame vs country/citizenship"),
    ("is capped at senior level by", "country for sport", "sport-frame vs citizenship"),
    ("speaks at home", "languages spoken, written or signed", "speak-frame vs official language"),
    ("is the tongue of administration in", "official language", "tongue-frame vs spoken language"),
    ("studied law at", "educated at", "study-frame vs teaches-at"),
    ("gave a guest lecture at", "UNKNOWN", "one-off lecture; resembles educated-at/employer"),
    ("followed the band on tour", "UNKNOWN", "fan behaviour; resembles follows"),
    ("follows online", "UNKNOWN", "social media; resembles follows"),
    ("is part of the deal", "UNKNOWN", "idiom; resembles part of"),
]

TOP60 = [
    "country", "diplomatic relation", "located in the administrative territorial entity",
    "shares border with", "contains administrative territorial entity", "country of citizenship",
    "capital", "headquarters location", "capital of", "inflation rate", "member of sports team",
    "has part", "oxidation state", "part of", "continent", "spouse", "place of birth",
    "member of political party", "member of", "performer", "owned by", "date of birth",
    "encodes", "cast member", "country of origin", "place of death", "employer",
    "location of formation", "owner of", "author", "official language", "league", "operator",
    "educated at", "unemployment rate", "founded by", "head of government", "location",
    "parent organization", "compulsory education (minimum age)", "inception",
    "applies to jurisdiction", "date of death", "parent taxon", "developer", "followed by",
    "twinned administrative body", "notable work", "subclass of", "subsidiary",
    "located in or next to body of water", "languages spoken, written or signed", "follows",
    "head of state", "child", "director", "time-weighted average exposure limit", "named after",
    "country for sport", "creator",
]

# Relation-vocabulary stoplist: no fabricated phrase may contain these stems.
STOPLIST = [
    "capital", "birth", "born", "death", "died", "marr", "wed", "spouse", "husband",
    "wife", "mother", "father", "son", "daughter", "child", "parent", "citizen",
    "passport", "nation", "countr", "employ", "payroll", "boss", "work", "job",
    "career", "offic", "member", "team", "club", "societ", "school", "colleg",
    "stud", "teach", "lectur", "direct", "film", "author", "novel", "penn",
    "creat", "maker", "develop", "studio", "found", "launch", "establish",
    "border", "locat", "situat", "headquar", "leagu", "tourna", "divis",
    "languag", "speak", "fluent", "tongue", "operat", "manag", "follow",
    "succeed", "successor", "twin", "sister", "presid", "monarch", "minist",
    "chancel", "premier", "taxon", "genus", "famil", "compos", "compris",
    "section", "piece", "compon", "branch", "compan", "serve", "repres",
    "cast", "role", "perform", "sung", "sing", "song", "music", "band",
    "head", "lead", "chief", "juris", "enforce", "inflat", "cpi", "price",
    "unemploy", "jobless", "compuls", "expos", "dose", "ppm", "shift",
    "origin", "hail", "discov", "invent", "populat", "currenc", "anthem",
    "flag", "nick", "motto", "colou", "color", "height", "degree", "occup",
    "fianc", "divorce", "reign", "crown", "throne", "award", "prize",
    "medal", "elect", "vote", "govern", "mayor", "senat", "parliament",
    "court", "judge", "prison", "jail", "landlord", "tenant", "rent",
    "mortgage", "wage", "salary", "pension", "strike", "union", "diploma",
    "thesis", "professor", "pupil", "exam", "campus", "tuition",
    "scholarship", "date", "calendar", "rate", "percent", "plays", "played",
    "player", "coach", "match", "tournament", "medal", "champion", "winner",
    "loser", "defeat", "captain", "keeper", "stadium", "referee", "season",
    "transfer", "relegat", "promot", "retire", "debut", "trial", "academy",
    "youth", "senior", "international", "capped", "caps", "shirt", "squad",
]


def main() -> int:
    assert len(PARAPHRASES) == 300, len(PARAPHRASES)
    assert len(FABRICATED) == 150, len(FABRICATED)
    assert len(NEAR_MISS) == 50, len(NEAR_MISS)
    assert len(TOP60) == 60
    counts = Counter(g for _, g in PARAPHRASES)
    assert set(counts) == set(TOP60), set(TOP60) ^ set(counts)
    assert all(v == 5 for v in counts.values()), counts
    for _, g in PARAPHRASES:
        assert g in TOP60, g
    for ph, g, _ in NEAR_MISS:
        assert g in TOP60 or g == "UNKNOWN", (ph, g)
    all_phrases = (
        [p for p, _ in PARAPHRASES] + FABRICATED + [p for p, _, _ in NEAR_MISS]
    )
    assert len(set(all_phrases)) == 500, "duplicate phrase strings across sets"
    bad = [
        f for f in FABRICATED
        for s in STOPLIST
        if s in f.lower()
    ]
    assert not bad, bad

    OUTDIR.mkdir(parents=True, exist_ok=True)
    par = [
        {"id": f"p{i + 1:03d}", "phrase": p, "gold": g}
        for i, (p, g) in enumerate(PARAPHRASES)
    ]
    fab = [
        {"id": f"f{i + 1:03d}", "phrase": p, "gold": "UNKNOWN"}
        for i, p in enumerate(FABRICATED)
    ]
    near = [
        {"id": f"n{i + 1:03d}", "phrase": p, "gold": g, "trap": t}
        for i, (p, g, t) in enumerate(NEAR_MISS)
    ]
    (OUTDIR / "test_paraphrases.json").write_text(
        json.dumps(par, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    (OUTDIR / "test_fabricated.json").write_text(
        json.dumps(fab, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    (OUTDIR / "test_nearmiss.json").write_text(
        json.dumps(near, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"paraphrases={len(par)} fabricated={len(fab)} nearmiss={len(near)}")
    print("relations covered:", len(counts))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
