"""Numeric fixtures only; no verified-human receipt is generated by this test."""
import copy
import json
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import torch
import claude_fewex_net as N
from sol_spatial_poc_ordered_v2 import make_ordered_source
from sol_translator_grounding_v6 import HumanInputProjection
from sol_translator_english_v6 import StatePrefix
from sol_stop_ordered_checkpoint_receipt_v1 import probe, validate_tuple, sha, source_paths
from scripts.sol_stop_adapter import module_hash

def main():
    torch.set_num_threads(2)
    records=[]; rejections=[]
    # Metadata-only rejection fixtures; these do not assert real human origin.
    digests={k:k[0]*64 for k in ('parent','reader','prefix','provenance')}
    meta={'input_version':'human-notebook-ordered-v10','order_contract':'sol-ordered-notebook-v2',
          'updates':500,'stage':'human-grounded-ordered-unqualified','human_manifest_sha256':'0'*64}
    reader={'training_origin':'verified-human-origin','input_version':meta['input_version'],
            'order_contract':meta['order_contract'],'human_manifest_sha256':'0'*64,'state_dict':{'numeric':torch.zeros(1)}}
    prefix={'training_origin':'verified-human-origin-verbatim','source_state_contract':'sol-stop-FinalLatent-v1',
            'input_version':meta['input_version'],'order_contract':meta['order_contract'],'state_width':256,'hidden':32,'prefix_tokens':8,
            'training_stage':'ordered-joint-grounding-unqualified','parent_sha256':digests['parent'],'reader_sha256':digests['reader'],
            'lm_provenance_sha256':digests['provenance'],'human_manifest_sha256':'0'*64,'adapter_state':{'numeric':torch.zeros(1)}}
    validate_tuple(meta,reader,prefix,digests)
    cases=[('wrong-parent','prefix','parent_sha256','9'*64),('wrong-reader','prefix','reader_sha256','9'*64),
           ('wrong-provenance','prefix','lm_provenance_sha256','9'*64),('wrong-manifest','reader','human_manifest_sha256','9'*64),
           ('incomplete-awake','meta','updates',499),('wrong-order','meta','order_contract','old'),
           ('zero-updates','meta','updates',0)]
    for name,target,key,value in cases:
        values={'meta':copy.deepcopy(meta),'reader':copy.deepcopy(reader),'prefix':copy.deepcopy(prefix)}
        values[target][key]=value
        try:validate_tuple(values['meta'],values['reader'],values['prefix'],digests)
        except ValueError:rejections.append(name)
        else:raise AssertionError(name)
    for seed,family in ((0,'loop'),(1,'sparse_unrolled4')):
        torch.manual_seed(seed)
        core=make_ordered_source(N.Net('loop'),family).eval()
        projection=HumanInputProjection(16).eval().requires_grad_(False)
        decoder=StatePrefix(256,16).eval().requires_grad_(False)
        before=module_hash(core)
        raw,record=probe(core,projection,decoder,seed)
        assert module_hash(core)==before
        assert raw['native_begin']['notebook_absolute_positions'].shape[1]==record['notebook_valid']
        assert torch.equal(raw['native_final'],raw['runtime_final'])
        record['fixture_family']=family
        record['additional_test_assertions']=3
        records.append(record)
    print(json.dumps({'fixture_only':True,'actual_checkpoint_receipts':0,'records':records,
        'metadata_rejections':rejections,'checks_passed':sum(r['checks_passed']+3 for r in records)+len(rejections)+1,
        'optimizer_updates':0,'human_rows':0,'stop88_reads':0,'DEV_reads':0,
        'source_pins':{p:sha(p) for p in source_paths()}},indent=2))

if __name__=='__main__':main()
